// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceNoticeBase.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/Notice/LXSliceNoticeDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.Notice = __M.module("LXGrid.App.Notice");

    Object.defineProperty(LXGrid.App.Notice, 'IObjectNoticeBaseName', {
        value: "IObjectNoticeBase"
    });

    LXGrid.App.Notice.IObjectNoticeBase = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Notice::IObjectNoticeBase",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.Notice.IObjectNoticeBasePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Notice.IObjectNoticeBase.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.Notice.IObjectNoticeBase, LXGrid.App.Notice.IObjectNoticeBasePrx,
    {
        "GetUserReceiveList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3]], [[3], ["Ice.StringSeqHelper"]], , , ],
        "GetUserPublishList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3]], [[3], ["Ice.StringSeqHelper"]], , , ],
        "GetManageNoticeList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3]], [[3], ["Ice.StringSeqHelper"]], , , ],
        "GetNoticeInfo": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.App.Notice.LXNoticeInfo", true]], , , true],
        "GetNoticeContent": [, , , , , [LXGrid.Common.LXReturn], [[7]], [[7]], , , ],
        "GetNoticeScope": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.App.Notice.LXScope", true]], , , true],
        "GetNoticeStatus": [, , , , , [LXGrid.Common.LXReturn], [[3], [7]], [["LXGrid.App.Notice.LXSubmitStatus", true]], , , true],
        "PublishNotice": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7], [7], [7], [3], [3], ["LXGrid.App.Notice.LXScope", true]], [[7]], , true, ],
        "DeleteNotice": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], , , , ],
        "ComfirmNotice": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], , , , ],
        "ReadNotice": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
