// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceNoticeStat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/Notice/LXSliceNoticeDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.Notice = __M.module("LXGrid.App.Notice");

    Object.defineProperty(LXGrid.App.Notice, 'IObjectNoticeStatName', {
        value: "IObjectNoticeStat"
    });

    LXGrid.App.Notice.IObjectNoticeStat = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectMasterSlaveBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Notice::IObjectNoticeStat",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Common::IObjectMasterSlaveBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.Notice.IObjectNoticeStatPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Notice.IObjectNoticeStat.ice_staticId, [
        LXGrid.Common.IObjectMasterSlaveBasePrx]);

    Slice.defineOperations(LXGrid.App.Notice.IObjectNoticeStat, LXGrid.App.Notice.IObjectNoticeStatPrx,
    {
        "GetNoticeStat": [, , , , , [LXGrid.Common.LXReturn], [[7], [3], [3]], [["LXGrid.App.Notice.LXScopeStatDictHelper"]], , , ],
        "GetNoticeDataStat": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3], [4]], [["LXGrid.App.Notice.LXDataStatDictHelper"]], , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
