// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `IObjectGameTable.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.App/PoemsMatch/MatchInfo",
        "LXGrid.App/PoemsMatch/GameTableInfo",
        "LXGrid.System/LXSliceBase"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.PoemsMatch = __M.module("LXGrid.App.PoemsMatch");

    Object.defineProperty(LXGrid.App.PoemsMatch, 'IObjectGameTableName', {
        value: "IObjectGameTable"
    });

    LXGrid.App.PoemsMatch.IObjectGameTable = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsMatch::IObjectGameTable",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.PoemsMatch.IObjectGameTablePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsMatch.IObjectGameTable.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.PoemsMatch.IObjectGameTable, LXGrid.App.PoemsMatch.IObjectGameTablePrx,
    {
        "GetGameTableInfo": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.App.PoemsMatch.GameTableInfo", true]], , , true],
        "StartTable": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [7], [3], [3], [3], [3], [3]], [[1]], , , ],
        "StartTableNew": [, , , , , [LXGrid.Common.LXReturn], [[7], [3], [3], ["LXGrid.App.PoemsMatch.WaitMatchPlayer", true], ["LXGrid.App.PoemsMatch.WaitMatchPlayer", true]], [[1]], , true, ],
        "SynchronousUserState": [, , , , , [LXGrid.Common.LXReturn], [[7], [3], [3], [3]], [[3], [3], [3]], , , ],
        "SubmitAnswer": [, , , , , [LXGrid.Common.LXReturn], [[7], [3], [7]], [["LXGrid.App.PoemsMatch.AnswerResponseInfo", true]], , , true],
        "GetQuestionInfo": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.App.PoemsMatch.GameTableQuestionInfo", true]], , , true],
        "GetQuestionAnswer": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.App.PoemsMatch.AnswerResponseInfo", true]], , , true],
        "GetUserPrize": [, , , , , [LXGrid.Common.LXReturn], [[7], [3]], [["LXGrid.App.PoemsMatch.GameOverPrizeInfo", true]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
