// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `IObjectMatchStatistics.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.App/PoemsMatch/MatchInfo",
        "LXGrid.App/PoemsMatch/MatchStatisticsInfo"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.PoemsMatch = __M.module("LXGrid.App.PoemsMatch");

    Object.defineProperty(LXGrid.App.PoemsMatch, 'IObjectMatchStatisticsName', {
        value: "IObjectMatchStatistics"
    });

    LXGrid.App.PoemsMatch.IObjectMatchStatistics = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsMatch::IObjectMatchStatistics",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.PoemsMatch.IObjectMatchStatisticsPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsMatch.IObjectMatchStatistics.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.PoemsMatch.IObjectMatchStatistics, LXGrid.App.PoemsMatch.IObjectMatchStatisticsPrx,
    {
        "GetByMatchId": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.PoemsMatch.MatchStatisticsInfo", true]], , , true],
        "GetMatchTopRanking": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [["LXGrid.App.PoemsMatch.intSeqHelper"]], , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
