// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `IObjectPoemsStatistics.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.App/PoemsMatch/PoemStatisticsInfo",
        "LXGrid.App/PoemsMatch/MatchInfo"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.PoemsMatch = __M.module("LXGrid.App.PoemsMatch");

    Object.defineProperty(LXGrid.App.PoemsMatch, 'IObjectPoemsStatisticsName', {
        value: "IObjectPoemsStatistics"
    });

    LXGrid.App.PoemsMatch.IObjectPoemsStatistics = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsMatch::IObjectPoemsStatistics",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.PoemsMatch.IObjectPoemsStatisticsPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsMatch.IObjectPoemsStatistics.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.PoemsMatch.IObjectPoemsStatistics, LXGrid.App.PoemsMatch.IObjectPoemsStatisticsPrx,
    {
        "GetByAreaId": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [["LXGrid.App.PoemsMatch.PoemsAreaStatisticsInfo", true]], , , true],
        "GetByUserId": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.PoemsMatch.PoemsUserStatisticsInfo", true]], , , true],
        "GetSubAreaIds": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [["LXGrid.App.PoemsMatch.intSeqHelper"]], , , ],
        "GetToken": [, , , , , [LXGrid.Common.LXReturn], [[3]], [[7]], , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
