// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `IObjectMatch.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.App/PoemsMatch/MatchInfo",
        "LXGrid.System/LXSliceBase",
        "LXGrid.App/PoemsMatch/GameTableInfo"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.PoemsMatch = __M.module("LXGrid.App.PoemsMatch");

    Object.defineProperty(LXGrid.App.PoemsMatch, 'IObjectMatchName', {
        value: "IObjectMatch"
    });

    LXGrid.App.PoemsMatch.IObjectMatch = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsMatch::IObjectMatch",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.PoemsMatch.IObjectMatchPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsMatch.IObjectMatch.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.PoemsMatch.IObjectMatch, LXGrid.App.PoemsMatch.IObjectMatchPrx,
    {
        "GetMainMatchInfo": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.PoemsMatch.MatchInfo", true]], , , true],
        "GetGoingOnSubMatchInfo": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.PoemsMatch.MatchDetailInfo", true]], , , true],
        "GetMatchIdByArea": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3], [3]], [["LXGrid.App.PoemsMatch.intSeqHelper"]], , , ],
        "FindRival": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3], [7], [3]], [["LXGrid.App.PoemsMatch.WaitMatchTable", true]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
