// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `UserStatisticsInfo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var LXGrid = __M.module("LXGrid");

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.PoemsMatch = __M.module("LXGrid.App.PoemsMatch");

    LXGrid.App.PoemsMatch.UserTableOperat = Slice.defineEnum([
        ['Add', 0], ['_Delete', 1], ['Get', 2]]);

    LXGrid.App.PoemsMatch.UserRankStatisticsInfo = Slice.defineObject(
        function(UserId, UserName, ClassName, SchoolName, MatchId, Ranking, TokenNumber, WinNumber, JoinTotalNumber)
        {
            Ice.Object.call(this);
            this.UserId = UserId !== undefined ? UserId : 0;
            this.UserName = UserName !== undefined ? UserName : "";
            this.ClassName = ClassName !== undefined ? ClassName : "";
            this.SchoolName = SchoolName !== undefined ? SchoolName : "";
            this.MatchId = MatchId !== undefined ? MatchId : 0;
            this.Ranking = Ranking !== undefined ? Ranking : 0;
            this.TokenNumber = TokenNumber !== undefined ? TokenNumber : 0;
            this.WinNumber = WinNumber !== undefined ? WinNumber : 0;
            this.JoinTotalNumber = JoinTotalNumber !== undefined ? JoinTotalNumber : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsMatch::UserRankStatisticsInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.UserId);
            __os.writeString(this.UserName);
            __os.writeString(this.ClassName);
            __os.writeString(this.SchoolName);
            __os.writeInt(this.MatchId);
            __os.writeInt(this.Ranking);
            __os.writeInt(this.TokenNumber);
            __os.writeInt(this.WinNumber);
            __os.writeInt(this.JoinTotalNumber);
        },
        function(__is)
        {
            this.UserId = __is.readInt();
            this.UserName = __is.readString();
            this.ClassName = __is.readString();
            this.SchoolName = __is.readString();
            this.MatchId = __is.readInt();
            this.Ranking = __is.readInt();
            this.TokenNumber = __is.readInt();
            this.WinNumber = __is.readInt();
            this.JoinTotalNumber = __is.readInt();
        },
        false);

    LXGrid.App.PoemsMatch.UserRankStatisticsInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsMatch.UserRankStatisticsInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsMatch.UserRankStatisticsInfo, LXGrid.App.PoemsMatch.UserRankStatisticsInfoPrx);
    Slice.defineSequence(LXGrid.App.PoemsMatch, "UserRankStatisticsInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.PoemsMatch.UserRankStatisticsInfo");

    LXGrid.App.PoemsMatch.UserJoinNumberInfo = Slice.defineObject(
        function(CurSubMatchJoinNum)
        {
            Ice.Object.call(this);
            this.CurSubMatchJoinNum = CurSubMatchJoinNum !== undefined ? CurSubMatchJoinNum : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsMatch::UserJoinNumberInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.CurSubMatchJoinNum);
        },
        function(__is)
        {
            this.CurSubMatchJoinNum = __is.readInt();
        },
        false);

    LXGrid.App.PoemsMatch.UserJoinNumberInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsMatch.UserJoinNumberInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsMatch.UserJoinNumberInfo, LXGrid.App.PoemsMatch.UserJoinNumberInfoPrx);

    LXGrid.App.PoemsMatch.UserMatchTokenStat = Slice.defineObject(
        function(MatchId, UserId, UserName, Token)
        {
            Ice.Object.call(this);
            this.MatchId = MatchId !== undefined ? MatchId : 0;
            this.UserId = UserId !== undefined ? UserId : 0;
            this.UserName = UserName !== undefined ? UserName : "";
            this.Token = Token !== undefined ? Token : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsMatch::UserMatchTokenStat"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.MatchId);
            __os.writeInt(this.UserId);
            __os.writeString(this.UserName);
            __os.writeInt(this.Token);
        },
        function(__is)
        {
            this.MatchId = __is.readInt();
            this.UserId = __is.readInt();
            this.UserName = __is.readString();
            this.Token = __is.readInt();
        },
        false);

    LXGrid.App.PoemsMatch.UserMatchTokenStatPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsMatch.UserMatchTokenStat.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsMatch.UserMatchTokenStat, LXGrid.App.PoemsMatch.UserMatchTokenStatPrx);
    Slice.defineSequence(LXGrid.App.PoemsMatch, "UserMatchTokenStatSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.PoemsMatch.UserMatchTokenStat");
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
