// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceAsset.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/Asset/LXSliceAssetDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Asset = __M.module("LXGrid.Main.Asset");

    Object.defineProperty(LXGrid.Main.Asset, 'IObjectAssetName', {
        value: "IObjectAsset"
    });

    LXGrid.Main.Asset.IObjectAsset = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::Asset::IObjectAsset"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Asset.IObjectAssetPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.IObjectAsset.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.Asset.IObjectAsset, LXGrid.Main.Asset.IObjectAssetPrx,
    {
        "GetAssetSummary": [, , , , , [LXGrid.Common.LXReturn], [[3], [LXGrid.Main.Asset.LXEnumCurrecy.__helper]], [["LXGrid.Main.Asset.LXAssetBase", true]], , , true],
        "GetAssetDetails": [, , , , , [LXGrid.Common.LXReturn], [["LXGrid.Main.Asset.LXAssetParameters", true], [3], [4], [4], [LXGrid.Main.Asset.LXEnumAssetChangeState.__helper], [3], [3]], [[3], ["LXGrid.Main.Asset.LXAssetDetailBaseSeqHelper"]], , true, true],
        "AssetChange": [, , , , , [LXGrid.Common.LXReturn], [["LXGrid.Main.Asset.LXAssetParameters", true], [3], [4], [LXGrid.Main.Asset.LXEnumAssetChangeState.__helper], [7], [7]], , , true, ],
        "AssetTransfer": [, , , , , [LXGrid.Common.LXReturn], [["LXGrid.Main.Asset.LXAssetParameters", true], [3], [3], [4], [7], [7], [7]], [[4]], , true, ],
        "AssetFreeze": [, , , , , [LXGrid.Common.LXReturn], [["LXGrid.Main.Asset.LXAssetParameters", true], [3], [4], [7], [7]], , , true, ],
        "AssetThaw": [, , , , , [LXGrid.Common.LXReturn], [["LXGrid.Main.Asset.LXAssetParameters", true], [3], [4], [7], [7]], , , true, ],
        "RefreshAssetSummaryCache": [, , , , , [LXGrid.Common.LXReturn], [[3], [4], [LXGrid.Main.Asset.LXEnumCurrecy.__helper], [LXGrid.Main.Asset.LXEnumAssetChangeState.__helper]], , , , ],
        "RemoveAssetSummaryCache": [, , , , , [LXGrid.Common.LXReturn], [[3], [LXGrid.Main.Asset.LXEnumCurrecy.__helper]], , , , ]
    });

    Object.defineProperty(LXGrid.Main.Asset, 'IObjectBusinessAssetName', {
        value: "IObjectBusinessAsset"
    });

    LXGrid.Main.Asset.IObjectBusinessAsset = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::Asset::IObjectBusinessAsset"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Asset.IObjectBusinessAssetPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.IObjectBusinessAsset.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.Asset.IObjectBusinessAsset, LXGrid.Main.Asset.IObjectBusinessAssetPrx,
    {
        "BusinessAssetChange": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [7], [7]], , , , ],
        "IsUpper": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3]], , , , ],
        "IsUpperByMonth": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [7]], , , , ]
    });

    Object.defineProperty(LXGrid.Main.Asset, 'IObjectAssetConfigName', {
        value: "IObjectAssetConfig"
    });

    LXGrid.Main.Asset.IObjectAssetConfig = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectMasterSlaveBase
        ], 3,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Common::IObjectMasterSlaveBase",
            "::LXGrid::Main::Asset::IObjectAssetConfig"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Asset.IObjectAssetConfigPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.IObjectAssetConfig.ice_staticId, [
        LXGrid.Common.IObjectMasterSlaveBasePrx]);

    Slice.defineOperations(LXGrid.Main.Asset.IObjectAssetConfig, LXGrid.Main.Asset.IObjectAssetConfigPrx,
    {
        "GetConfig": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [["LXGrid.Main.Asset.LXAssetConfigBase", true]], , , true],
        "AddConfig": [, , , , , [LXGrid.Common.LXReturn], [["LXGrid.Main.Asset.LXAssetConfigBase", true]], , , true, ],
        "ModifyConfig": [, , , , , [LXGrid.Common.LXReturn], [["LXGrid.Main.Asset.LXAssetConfigBase", true]], , , true, ],
        "RemoveConfig": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3]], , , , ],
        "GetTotalAmountAppArray": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.Main.Asset.AppIdSeqHelper"]], , , ],
        "GetUpperConfig": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.Main.Asset.LXAssetUpperBase", true]], , , true],
        "AddUpperConfig": [, , , , , [LXGrid.Common.LXReturn], [[3]], [[3]], , , ],
        "ModifyUpperConfig": [, , , , , [LXGrid.Common.LXReturn], [["LXGrid.Main.Asset.LXAssetUpperBase", true]], , , true, ]
    });

    Object.defineProperty(LXGrid.Main.Asset, 'IObjectBusinessAssetChangeLogName', {
        value: "IObjectBusinessAssetChangeLog"
    });

    LXGrid.Main.Asset.IObjectBusinessAssetChangeLog = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::Asset::IObjectBusinessAssetChangeLog"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Asset.IObjectBusinessAssetChangeLogPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.IObjectBusinessAssetChangeLog.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.Asset.IObjectBusinessAssetChangeLog, LXGrid.Main.Asset.IObjectBusinessAssetChangeLogPrx,
    {
        "Notes": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [3]], , , , ],
        "GetExecTimes": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3]], , , , ],
        "GetExecTimesBySmt": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [4], [4]], , , , ]
    });

    Object.defineProperty(LXGrid.Main.Asset, 'IObjectExpConfigName', {
        value: "IObjectExpConfig"
    });

    LXGrid.Main.Asset.IObjectExpConfig = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::Asset::IObjectExpConfig"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Asset.IObjectExpConfigPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.IObjectExpConfig.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.Asset.IObjectExpConfig, LXGrid.Main.Asset.IObjectExpConfigPrx);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
