// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceAssetDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Asset = __M.module("LXGrid.Main.Asset");

    LXGrid.Main.Asset.LXEnumAssetDbCode = Slice.defineObject(
        function(LXEnumAssetChangeCode_Success, LXEnumAssetChangeCode_MoneyNotEnough, LXEnumAssetChangeCode_DbError, LXEnumAssetChangeCode_Unknow)
        {
            Ice.Object.call(this);
            this.LXEnumAssetChangeCode_Success = LXEnumAssetChangeCode_Success !== undefined ? LXEnumAssetChangeCode_Success : 0;
            this.LXEnumAssetChangeCode_MoneyNotEnough = LXEnumAssetChangeCode_MoneyNotEnough !== undefined ? LXEnumAssetChangeCode_MoneyNotEnough : 1;
            this.LXEnumAssetChangeCode_DbError = LXEnumAssetChangeCode_DbError !== undefined ? LXEnumAssetChangeCode_DbError : 99;
            this.LXEnumAssetChangeCode_Unknow = LXEnumAssetChangeCode_Unknow !== undefined ? LXEnumAssetChangeCode_Unknow : 31;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::Asset::LXEnumAssetDbCode"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.LXEnumAssetChangeCode_Success);
            __os.writeInt(this.LXEnumAssetChangeCode_MoneyNotEnough);
            __os.writeInt(this.LXEnumAssetChangeCode_DbError);
            __os.writeInt(this.LXEnumAssetChangeCode_Unknow);
        },
        function(__is)
        {
            this.LXEnumAssetChangeCode_Success = __is.readInt();
            this.LXEnumAssetChangeCode_MoneyNotEnough = __is.readInt();
            this.LXEnumAssetChangeCode_DbError = __is.readInt();
            this.LXEnumAssetChangeCode_Unknow = __is.readInt();
        },
        false);

    LXGrid.Main.Asset.LXEnumAssetDbCodePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.LXEnumAssetDbCode.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Asset.LXEnumAssetDbCode, LXGrid.Main.Asset.LXEnumAssetDbCodePrx);

    LXGrid.Main.Asset.LXEnumAssetChangeCode = Slice.defineEnum([
        ['LXEnumAssetChangeCode_Success', 0], ['LXEnumAssetChangeCode_MoneyNotEnough', 1046001], ['LXEnumAssetChangeCode_DbError', 1046002], ['LXEnumAssetChangeCode_Unknow', 10460100]]);

    LXGrid.Main.Asset.LXEnumBusinessAssetChangeCode = Slice.defineEnum([
        ['LXEnumBusinessAssetChangeCode_NotFound', 1046101], ['LXEnumBusinessAssetChangeCode_ItemAmountUpper', 1046102], ['LXEnumBusinessAssetChangeCode_ItemTimesUpper', 1046103], ['LXEnumBusinessAssetChangeCode_TotalAmountUpper', 1046199]]);

    LXGrid.Main.Asset.LXEnumCurrecy = Slice.defineEnum([
        ['LXCurrecy_None', 0], ['LXCurrecy_RMB', 1], ['LXCurrecy_LEB', 2], ['LXCurrecy_JINB', 3], ['LXCurrecy_Exp', 4],
        ['LXCurrecy_Freeze_JINB', 21], ['LXCurrecy_Freeze_LEB', 31]]);

    LXGrid.Main.Asset.LXEnumAssetChangeState = Slice.defineEnum([
        ['LXEnumAssetChangeState_All', 0], ['LXEnumAssetChangeState_Income', 1], ['LXEnumAssetChangeState_Outcome', 2]]);

    LXGrid.Main.Asset.LXEnumExecUnit = Slice.defineEnum([
        ['LXEnumExecUnit_Day', 1], ['LXEnumExecUnit_Week', 2], ['LXEnumExecUnit_Month', 3], ['LXEnumExecUnit_Year', 4]]);

    LXGrid.Main.Asset.LXAssetParameters = Slice.defineObject(
        function(app_id, sub_id, currecy)
        {
            Ice.Object.call(this);
            this.app_id = app_id !== undefined ? app_id : 0;
            this.sub_id = sub_id !== undefined ? sub_id : 0;
            this.currecy = currecy !== undefined ? currecy : LXGrid.Main.Asset.LXEnumCurrecy.LXCurrecy_None;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::Asset::LXAssetParameters"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.app_id);
            __os.writeInt(this.sub_id);
            LXGrid.Main.Asset.LXEnumCurrecy.__write(__os, this.currecy);
        },
        function(__is)
        {
            this.app_id = __is.readInt();
            this.sub_id = __is.readInt();
            this.currecy = LXGrid.Main.Asset.LXEnumCurrecy.__read(__is);
        },
        false);

    LXGrid.Main.Asset.LXAssetParametersPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.LXAssetParameters.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Asset.LXAssetParameters, LXGrid.Main.Asset.LXAssetParametersPrx);

    LXGrid.Main.Asset.LXAssetBase = Slice.defineObject(
        function(user_id, currecy_id, amount, in_amount, out_amount)
        {
            Ice.Object.call(this);
            this.user_id = user_id !== undefined ? user_id : 0;
            this.currecy_id = currecy_id !== undefined ? currecy_id : 0;
            this.amount = amount !== undefined ? amount : 0;
            this.in_amount = in_amount !== undefined ? in_amount : 0;
            this.out_amount = out_amount !== undefined ? out_amount : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::Asset::LXAssetBase"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.user_id);
            __os.writeInt(this.currecy_id);
            __os.writeLong(this.amount);
            __os.writeLong(this.in_amount);
            __os.writeLong(this.out_amount);
        },
        function(__is)
        {
            this.user_id = __is.readInt();
            this.currecy_id = __is.readInt();
            this.amount = __is.readLong();
            this.in_amount = __is.readLong();
            this.out_amount = __is.readLong();
        },
        false);

    LXGrid.Main.Asset.LXAssetBasePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.LXAssetBase.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Asset.LXAssetBase, LXGrid.Main.Asset.LXAssetBasePrx);
    Slice.defineSequence(LXGrid.Main.Asset, "LXAssetBaseSeqHelper", "Ice.ObjectHelper", false, "LXGrid.Main.Asset.LXAssetBase");

    LXGrid.Main.Asset.LXAssetDetailBase = Slice.defineObject(
        function(detail_id, atom, app_id, sub_id, user_id, currecy_id, amount, current_amount, before_amount, amount_status, remark, uri, ip, in_time, task_time)
        {
            Ice.Object.call(this);
            this.detail_id = detail_id !== undefined ? detail_id : 0;
            this.atom = atom !== undefined ? atom : "";
            this.app_id = app_id !== undefined ? app_id : 0;
            this.sub_id = sub_id !== undefined ? sub_id : 0;
            this.user_id = user_id !== undefined ? user_id : 0;
            this.currecy_id = currecy_id !== undefined ? currecy_id : 0;
            this.amount = amount !== undefined ? amount : 0;
            this.current_amount = current_amount !== undefined ? current_amount : 0;
            this.before_amount = before_amount !== undefined ? before_amount : 0;
            this.amount_status = amount_status !== undefined ? amount_status : 0;
            this.remark = remark !== undefined ? remark : "";
            this.uri = uri !== undefined ? uri : "";
            this.ip = ip !== undefined ? ip : "";
            this.in_time = in_time !== undefined ? in_time : 0;
            this.task_time = task_time !== undefined ? task_time : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::Asset::LXAssetDetailBase"
        ],
        -1,
        function(__os)
        {
            __os.writeLong(this.detail_id);
            __os.writeString(this.atom);
            __os.writeInt(this.app_id);
            __os.writeInt(this.sub_id);
            __os.writeInt(this.user_id);
            __os.writeInt(this.currecy_id);
            __os.writeLong(this.amount);
            __os.writeLong(this.current_amount);
            __os.writeLong(this.before_amount);
            __os.writeInt(this.amount_status);
            __os.writeString(this.remark);
            __os.writeString(this.uri);
            __os.writeString(this.ip);
            __os.writeLong(this.in_time);
            __os.writeLong(this.task_time);
        },
        function(__is)
        {
            this.detail_id = __is.readLong();
            this.atom = __is.readString();
            this.app_id = __is.readInt();
            this.sub_id = __is.readInt();
            this.user_id = __is.readInt();
            this.currecy_id = __is.readInt();
            this.amount = __is.readLong();
            this.current_amount = __is.readLong();
            this.before_amount = __is.readLong();
            this.amount_status = __is.readInt();
            this.remark = __is.readString();
            this.uri = __is.readString();
            this.ip = __is.readString();
            this.in_time = __is.readLong();
            this.task_time = __is.readLong();
        },
        false);

    LXGrid.Main.Asset.LXAssetDetailBasePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.LXAssetDetailBase.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Asset.LXAssetDetailBase, LXGrid.Main.Asset.LXAssetDetailBasePrx);
    Slice.defineSequence(LXGrid.Main.Asset, "LXAssetDetailBaseSeqHelper", "Ice.ObjectHelper", false, "LXGrid.Main.Asset.LXAssetDetailBase");

    LXGrid.Main.Asset.LXAssetConfigBase = Slice.defineObject(
        function(app_id, sub_id, upper_id, group_id, currecy_id, basic_val, upper_val, by_unit, times, amount_status, remark)
        {
            Ice.Object.call(this);
            this.app_id = app_id !== undefined ? app_id : 0;
            this.sub_id = sub_id !== undefined ? sub_id : 0;
            this.upper_id = upper_id !== undefined ? upper_id : 0;
            this.group_id = group_id !== undefined ? group_id : 0;
            this.currecy_id = currecy_id !== undefined ? currecy_id : 0;
            this.basic_val = basic_val !== undefined ? basic_val : 0;
            this.upper_val = upper_val !== undefined ? upper_val : 0;
            this.by_unit = by_unit !== undefined ? by_unit : 0;
            this.times = times !== undefined ? times : 0;
            this.amount_status = amount_status !== undefined ? amount_status : 0;
            this.remark = remark !== undefined ? remark : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::Asset::LXAssetConfigBase"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.app_id);
            __os.writeInt(this.sub_id);
            __os.writeInt(this.upper_id);
            __os.writeInt(this.group_id);
            __os.writeInt(this.currecy_id);
            __os.writeInt(this.basic_val);
            __os.writeInt(this.upper_val);
            __os.writeInt(this.by_unit);
            __os.writeInt(this.times);
            __os.writeInt(this.amount_status);
            __os.writeString(this.remark);
        },
        function(__is)
        {
            this.app_id = __is.readInt();
            this.sub_id = __is.readInt();
            this.upper_id = __is.readInt();
            this.group_id = __is.readInt();
            this.currecy_id = __is.readInt();
            this.basic_val = __is.readInt();
            this.upper_val = __is.readInt();
            this.by_unit = __is.readInt();
            this.times = __is.readInt();
            this.amount_status = __is.readInt();
            this.remark = __is.readString();
        },
        false);

    LXGrid.Main.Asset.LXAssetConfigBasePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.LXAssetConfigBase.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Asset.LXAssetConfigBase, LXGrid.Main.Asset.LXAssetConfigBasePrx);
    Slice.defineSequence(LXGrid.Main.Asset, "LXAssetConfigBaseSeqHelper", "Ice.ObjectHelper", false, "LXGrid.Main.Asset.LXAssetConfigBase");

    LXGrid.Main.Asset.LXAssetUpperBase = Slice.defineObject(
        function(upper_id, amount)
        {
            Ice.Object.call(this);
            this.upper_id = upper_id !== undefined ? upper_id : 0;
            this.amount = amount !== undefined ? amount : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::Asset::LXAssetUpperBase"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.upper_id);
            __os.writeInt(this.amount);
        },
        function(__is)
        {
            this.upper_id = __is.readInt();
            this.amount = __is.readInt();
        },
        false);

    LXGrid.Main.Asset.LXAssetUpperBasePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Asset.LXAssetUpperBase.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Asset.LXAssetUpperBase, LXGrid.Main.Asset.LXAssetUpperBasePrx);
    Slice.defineSequence(LXGrid.Main.Asset, "LXAssetUpperBaseSeqHelper", "Ice.ObjectHelper", false, "LXGrid.Main.Asset.LXAssetUpperBase");
    Slice.defineSequence(LXGrid.Main.Asset, "AppIdSeqHelper", "Ice.IntHelper", true);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
