// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceZoneDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/Zone/LXSliceZoneEnum",
        "LXGrid.Main/User/LXSliceUserDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Zone = __M.module("LXGrid.Main.Zone");

    LXGrid.Main.Zone.LXZoneSimple = Slice.defineObject(
        function(zone_id, zone_name, update_time, parent_zone_id)
        {
            Ice.Object.call(this);
            this.zone_id = zone_id !== undefined ? zone_id : 0;
            this.zone_name = zone_name !== undefined ? zone_name : "";
            this.update_time = update_time !== undefined ? update_time : 0;
            this.parent_zone_id = parent_zone_id !== undefined ? parent_zone_id : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::Zone::LXZoneSimple"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.zone_id);
            __os.writeString(this.zone_name);
            __os.writeLong(this.update_time);
            __os.writeInt(this.parent_zone_id);
        },
        function(__is)
        {
            this.zone_id = __is.readInt();
            this.zone_name = __is.readString();
            this.update_time = __is.readLong();
            this.parent_zone_id = __is.readInt();
        },
        false);

    LXGrid.Main.Zone.LXZoneSimplePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Zone.LXZoneSimple.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Zone.LXZoneSimple, LXGrid.Main.Zone.LXZoneSimplePrx);
    Slice.defineSequence(LXGrid.Main.Zone, "LXZoneSimpleSeqHelper", "Ice.ObjectHelper", false, "LXGrid.Main.Zone.LXZoneSimple");

    LXGrid.Main.Zone.LXZoneInfo = Slice.defineObject(
        function(zone_id, zone_name, update_time, parent_zone_id, parent_mode, status, mode_form, mode_born, mode_open, mode_admit, mode_open_setting, members, comment, priority, creator_userid, creator_uname, in_time, province, city, county)
        {
            LXGrid.Main.Zone.LXZoneSimple.call(this, zone_id, zone_name, update_time, parent_zone_id);
            this.parent_mode = parent_mode !== undefined ? parent_mode : 0;
            this.status = status !== undefined ? status : 0;
            this.mode_form = mode_form !== undefined ? mode_form : 0;
            this.mode_born = mode_born !== undefined ? mode_born : 0;
            this.mode_open = mode_open !== undefined ? mode_open : 0;
            this.mode_admit = mode_admit !== undefined ? mode_admit : 0;
            this.mode_open_setting = mode_open_setting !== undefined ? mode_open_setting : "";
            this.members = members !== undefined ? members : 0;
            this.comment = comment !== undefined ? comment : "";
            this.priority = priority !== undefined ? priority : 0;
            this.creator_userid = creator_userid !== undefined ? creator_userid : 0;
            this.creator_uname = creator_uname !== undefined ? creator_uname : "";
            this.in_time = in_time !== undefined ? in_time : 0;
            this.province = province !== undefined ? province : 0;
            this.city = city !== undefined ? city : 0;
            this.county = county !== undefined ? county : 0;
        },
        LXGrid.Main.Zone.LXZoneSimple, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::Zone::LXZoneInfo",
            "::LXGrid::Main::Zone::LXZoneSimple"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.parent_mode);
            __os.writeInt(this.status);
            __os.writeInt(this.mode_form);
            __os.writeInt(this.mode_born);
            __os.writeInt(this.mode_open);
            __os.writeInt(this.mode_admit);
            __os.writeString(this.mode_open_setting);
            __os.writeInt(this.members);
            __os.writeString(this.comment);
            __os.writeInt(this.priority);
            __os.writeInt(this.creator_userid);
            __os.writeString(this.creator_uname);
            __os.writeLong(this.in_time);
            __os.writeInt(this.province);
            __os.writeInt(this.city);
            __os.writeInt(this.county);
        },
        function(__is)
        {
            this.parent_mode = __is.readInt();
            this.status = __is.readInt();
            this.mode_form = __is.readInt();
            this.mode_born = __is.readInt();
            this.mode_open = __is.readInt();
            this.mode_admit = __is.readInt();
            this.mode_open_setting = __is.readString();
            this.members = __is.readInt();
            this.comment = __is.readString();
            this.priority = __is.readInt();
            this.creator_userid = __is.readInt();
            this.creator_uname = __is.readString();
            this.in_time = __is.readLong();
            this.province = __is.readInt();
            this.city = __is.readInt();
            this.county = __is.readInt();
        },
        false);

    LXGrid.Main.Zone.LXZoneInfoPrx = Slice.defineProxy(LXGrid.Main.Zone.LXZoneSimplePrx, LXGrid.Main.Zone.LXZoneInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Zone.LXZoneInfo, LXGrid.Main.Zone.LXZoneInfoPrx);
    Slice.defineSequence(LXGrid.Main.Zone, "LXZoneInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.Main.Zone.LXZoneInfo");

    LXGrid.Main.Zone.LXZoneMemberCore = Slice.defineStruct(
        function(zone_id, user_id, exper, status, role, edu_role, permission, apply_time, admit_time, login_time, login_count, apply_type)
        {
            this.zone_id = zone_id !== undefined ? zone_id : 0;
            this.user_id = user_id !== undefined ? user_id : 0;
            this.exper = exper !== undefined ? exper : 0;
            this.status = status !== undefined ? status : 0;
            this.role = role !== undefined ? role : 0;
            this.edu_role = edu_role !== undefined ? edu_role : 0;
            this.permission = permission !== undefined ? permission : 0;
            this.apply_time = apply_time !== undefined ? apply_time : 0;
            this.admit_time = admit_time !== undefined ? admit_time : 0;
            this.login_time = login_time !== undefined ? login_time : 0;
            this.login_count = login_count !== undefined ? login_count : 0;
            this.apply_type = apply_type !== undefined ? apply_type : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.zone_id);
            __os.writeInt(this.user_id);
            __os.writeInt(this.exper);
            __os.writeInt(this.status);
            __os.writeInt(this.role);
            __os.writeInt(this.edu_role);
            __os.writeInt(this.permission);
            __os.writeLong(this.apply_time);
            __os.writeLong(this.admit_time);
            __os.writeLong(this.login_time);
            __os.writeInt(this.login_count);
            __os.writeInt(this.apply_type);
        },
        function(__is)
        {
            this.zone_id = __is.readInt();
            this.user_id = __is.readInt();
            this.exper = __is.readInt();
            this.status = __is.readInt();
            this.role = __is.readInt();
            this.edu_role = __is.readInt();
            this.permission = __is.readInt();
            this.apply_time = __is.readLong();
            this.admit_time = __is.readLong();
            this.login_time = __is.readLong();
            this.login_count = __is.readInt();
            this.apply_type = __is.readInt();
        },
        60, 
        true);

    LXGrid.Main.Zone.LXZoneMember = Slice.defineStruct(
        function(core, customize_name)
        {
            this.core = core !== undefined ? core : new LXGrid.Main.Zone.LXZoneMemberCore();
            this.customize_name = customize_name !== undefined ? customize_name : "";
        },
        true,
        function(__os)
        {
            LXGrid.Main.Zone.LXZoneMemberCore.write(__os, this.core);
            __os.writeString(this.customize_name);
        },
        function(__is)
        {
            this.core = LXGrid.Main.Zone.LXZoneMemberCore.read(__is, this.core);
            this.customize_name = __is.readString();
        },
        61, 
        false);
    Slice.defineSequence(LXGrid.Main.Zone, "LXZoneMemberSeqHelper", "LXGrid.Main.Zone.LXZoneMember", false);

    LXGrid.Main.Zone.LXUserZoneRelation = Slice.defineStruct(
        function(user_id, zone_id, role, edu_role, mode_form, mode_born, apply_time, admit_time, is_primary, status)
        {
            this.user_id = user_id !== undefined ? user_id : 0;
            this.zone_id = zone_id !== undefined ? zone_id : 0;
            this.role = role !== undefined ? role : 0;
            this.edu_role = edu_role !== undefined ? edu_role : 0;
            this.mode_form = mode_form !== undefined ? mode_form : 0;
            this.mode_born = mode_born !== undefined ? mode_born : 0;
            this.apply_time = apply_time !== undefined ? apply_time : 0;
            this.admit_time = admit_time !== undefined ? admit_time : 0;
            this.is_primary = is_primary !== undefined ? is_primary : 0;
            this.status = status !== undefined ? status : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.user_id);
            __os.writeInt(this.zone_id);
            __os.writeInt(this.role);
            __os.writeInt(this.edu_role);
            __os.writeInt(this.mode_form);
            __os.writeInt(this.mode_born);
            __os.writeLong(this.apply_time);
            __os.writeLong(this.admit_time);
            __os.writeInt(this.is_primary);
            __os.writeInt(this.status);
        },
        function(__is)
        {
            this.user_id = __is.readInt();
            this.zone_id = __is.readInt();
            this.role = __is.readInt();
            this.edu_role = __is.readInt();
            this.mode_form = __is.readInt();
            this.mode_born = __is.readInt();
            this.apply_time = __is.readLong();
            this.admit_time = __is.readLong();
            this.is_primary = __is.readInt();
            this.status = __is.readInt();
        },
        48, 
        true);
    Slice.defineSequence(LXGrid.Main.Zone, "LXUserZoneRelationSeqHelper", "LXGrid.Main.Zone.LXUserZoneRelation", true);

    LXGrid.Main.Zone.LXZoneMemberApply = Slice.defineStruct(
        function(zone_id, user_id, user_type, apply_date, apply_mode, admit_user_id, admit_date, course)
        {
            this.zone_id = zone_id !== undefined ? zone_id : 0;
            this.user_id = user_id !== undefined ? user_id : 0;
            this.user_type = user_type !== undefined ? user_type : 0;
            this.apply_date = apply_date !== undefined ? apply_date : 0;
            this.apply_mode = apply_mode !== undefined ? apply_mode : LXGrid.Main.Zone.LXEnumZoneApplyMode.ZAM_Unknown;
            this.admit_user_id = admit_user_id !== undefined ? admit_user_id : 0;
            this.admit_date = admit_date !== undefined ? admit_date : 0;
            this.course = course !== undefined ? course : "";
        },
        true,
        function(__os)
        {
            __os.writeInt(this.zone_id);
            __os.writeInt(this.user_id);
            __os.writeInt(this.user_type);
            __os.writeLong(this.apply_date);
            LXGrid.Main.Zone.LXEnumZoneApplyMode.__write(__os, this.apply_mode);
            __os.writeInt(this.admit_user_id);
            __os.writeLong(this.admit_date);
            __os.writeString(this.course);
        },
        function(__is)
        {
            this.zone_id = __is.readInt();
            this.user_id = __is.readInt();
            this.user_type = __is.readInt();
            this.apply_date = __is.readLong();
            this.apply_mode = LXGrid.Main.Zone.LXEnumZoneApplyMode.__read(__is);
            this.admit_user_id = __is.readInt();
            this.admit_date = __is.readLong();
            this.course = __is.readString();
        },
        34, 
        false);
    Slice.defineSequence(LXGrid.Main.Zone, "LXZoneMemberApplySeqHelper", "LXGrid.Main.Zone.LXZoneMemberApply", false);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
