// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceZoneEnum.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Zone = __M.module("LXGrid.Main.Zone");

    LXGrid.Main.Zone.LXEnumZoneParentMode = Slice.defineEnum([
        ['ZPM_Unknown', 0], ['ZPM_Main', 1], ['ZPM_Branch', 2], ['ZPM_Subordinate', 3], ['ZPM_Department', 4],
        ['ZPM_Subsidiary', 5]]);

    LXGrid.Main.Zone.LXEnumZoneState = Slice.defineEnum([
        ['ZS_Initial', 0], ['ZS_Applying', 1], ['ZS_AdmitPass', 2], ['ZS_Refuse', 3], ['ZS_Ignore', 4],
        ['ZS_Locked', 10], ['ZS_Freeze', 20], ['ZS_Normal', 200]]);

    LXGrid.Main.Zone.LXEnumModeForm = Slice.defineEnum([
        ['MF_PubSchool', 101], ['MF_PriSchool', 102], ['MF_Edu', 103], ['MF_MClass', 201], ['MF_FeMClass', 202],
        ['MF_GraduatingClass', 210], ['MF_Group', 301], ['MF_ParentGroup', 302], ['MF_TeacherGroup', 303], ['MF_TeacherMasterGroup', 304],
        ['MF_GraduatingParentGroup', 310], ['MF_ParentCommittee', 320], ['MF_Organ', 321], ['MF_Other', 322], ['MF_BusiSpace', 330],
        ['MF_AutoSchoolMasterGroup', 401], ['MF_ChatGroup', 10001]]);

    LXGrid.Main.Zone.LXEnumZoneModeBorn = Slice.defineEnum([
        ['ZMB_Unknown', 0], ['ZMB_System', 1], ['ZMB_Unite', 2], ['ZMB_Self', 4]]);

    LXGrid.Main.Zone.LXEnumZoneModeOpen = Slice.defineEnum([
        ['ZMO_Close', 1], ['ZMO_Free', 2], ['ZMO_Admit', 4], ['ZMO_Invite', 8]]);

    LXGrid.Main.Zone.LXEnumZoneModeAdmit = Slice.defineEnum([
        ['ZMA_Close', 1], ['ZMA_Free', 2], ['ZMA_Admit', 4]]);

    LXGrid.Main.Zone.LXEnumZoneRole = Slice.defineEnum([
        ['ZR_General', 1], ['ZR_Manager', 2], ['ZR_Owner', 4]]);

    LXGrid.Main.Zone.LXBitZoneEduRole = Slice.defineEnum([
        ['ZER_Student', 1], ['ZER_Student_Commissary', 2], ['ZER_Student_Monitor', 4], ['ZER_Teacher_Manager', 8], ['ZER_Teacher', 16],
        ['ZER_Teacher_Master', 32], ['ZER_School_Dean', 64], ['ZER_School_Administrator', 128], ['ZER_School_Master', 256], ['ZER_School_Party', 512],
        ['ZER_School_Vice_Master', 1024], ['ZER_Parent', 4096], ['ZER_ChairMan', 8192], ['ZER_Director', 16384], ['ZER_Edu_Admin', 32768]]);

    LXGrid.Main.Zone.LXBitZonePermission = Slice.defineEnum([
        ['ZP_WithoutPerm', 0], ['ZP_ZoneSet', 1], ['ZP_AllotPerm', 2], ['ZP_AdmitMember', 4], ['ZP_RemoveMember', 8],
        ['ZP_Posting', 16], ['ZP_Feeds', 32]]);

    LXGrid.Main.Zone.LXEnumZoneMemberApplyType = Slice.defineEnum([
        ['ZMAT_Unknown', 0], ['ZMAT_TeacherImport', 1], ['ZMAT_TeacherEnter', 2], ['ZMAT_ApplyInto', 3], ['ZMAT_SystemImport', 4],
        ['ZMAT_UserCreate', 5]]);

    LXGrid.Main.Zone.LXEnumZoneApplyMode = Slice.defineEnum([
        ['ZAM_Unknown', 0], ['ZAM_Applying', 1], ['ZAM_AdmitPass', 2], ['ZAM_Refuse', 3], ['ZAM_Ignore', 4]]);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
