// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceMachineCollection.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.OM/Monitor/LXSliceMachineDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Machine = __M.module("LXGrid.Machine");

    LXGrid.Machine.Collection = __M.module("LXGrid.Machine.Collection");

    Object.defineProperty(LXGrid.Machine.Collection, 'IObjectMachineCollectionName', {
        value: "IObjectMachineCollection"
    });

    LXGrid.Machine.Collection.IObjectMachineCollection = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Machine::Collection::IObjectMachineCollection"
        ],
        -1, undefined, undefined, false);

    LXGrid.Machine.Collection.IObjectMachineCollectionPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Machine.Collection.IObjectMachineCollection.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Machine.Collection.IObjectMachineCollection, LXGrid.Machine.Collection.IObjectMachineCollectionPrx);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
