// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceMachineMonitor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.OM/Monitor/LXSliceMachineDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Machine = __M.module("LXGrid.Machine");

    LXGrid.Machine.Monitor = __M.module("LXGrid.Machine.Monitor");

    Object.defineProperty(LXGrid.Machine.Monitor, 'IObjectMachineMonitorName', {
        value: "IObjectMachineMonitor"
    });

    LXGrid.Machine.Monitor.IObjectMachineMonitor = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectMasterSlaveBase
        ], 3,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Common::IObjectMasterSlaveBase",
            "::LXGrid::Machine::Monitor::IObjectMachineMonitor"
        ],
        -1, undefined, undefined, false);

    LXGrid.Machine.Monitor.IObjectMachineMonitorPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Machine.Monitor.IObjectMachineMonitor.ice_staticId, [
        LXGrid.Common.IObjectMasterSlaveBasePrx]);

    Slice.defineOperations(LXGrid.Machine.Monitor.IObjectMachineMonitor, LXGrid.Machine.Monitor.IObjectMachineMonitorPrx,
    {
        "SendHostInfo": [, , , 1, , , [[7], ["LXGrid.Machine.LXHostInfo", true]], , , true, ],
        "SendHostStat": [, , , 1, , , [[7], ["LXGrid.Machine.LXHostStat", true]], , , true, ],
        "SetHostName": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [7]], , , , ],
        "GetHostIDList": [, , , , , [LXGrid.Common.LXReturn], , [["Ice.StringSeqHelper"]], , , ],
        "GetHostInfo": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.Machine.LXHostInfo", true], [7]], , , true],
        "GetHostStatList": [, , , , , [LXGrid.Common.LXReturn], , [["LXGrid.Machine.LXHostStatBaseSeqHelper"]], , , true],
        "GetHostStat": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.Machine.LXHostStat", true]], , , true],
        "GetCPUCurve": [, , , , , [LXGrid.Common.LXReturn], [[7], [3]], [["LXGrid.Machine.LXCurvePointSeqHelper"]], , , true],
        "GetMEMCurve": [, , , , , [LXGrid.Common.LXReturn], [[7], [3]], [["LXGrid.Machine.LXCurvePointSeqHelper"]], , , true],
        "CreateAlarmTask": [, , , , , [LXGrid.Common.LXReturn], [["LXGrid.Machine.LXAlarmTask", true]], [[3]], , true, ],
        "ModifyAlarmTask": [, , , , , [LXGrid.Common.LXReturn], [[3], ["LXGrid.Machine.LXAlarmTask", true]], , , true, ],
        "DeleteAlarmTask": [, , , , , [LXGrid.Common.LXReturn], [[3]], , , , ],
        "GetAlarmTaskList": [, , , , , [LXGrid.Common.LXReturn], , [["Ice.IntSeqHelper"]], , , ],
        "GetAlarmTaskInfo": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.Machine.LXAlarmTask", true]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
