// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceGridDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var LXGrid = __M.module("LXGrid");

    Object.defineProperty(LXGrid, 'ThisGridName', {
        value: "LXGridOM"
    });

    Object.defineProperty(LXGrid, 'MonitorGridName', {
        value: "LXGridMonitor"
    });

    Object.defineProperty(LXGrid, 'ClusterNameEnterpriseAuth', {
        value: "LXEnterpriseAuth"
    });

    Object.defineProperty(LXGrid, 'ClusterNameEnterpriseUser', {
        value: "LXEnterpriseUser"
    });

    Object.defineProperty(LXGrid, 'ClusterNameEnterpriseApp', {
        value: "LXEnterpriseApp"
    });

    Object.defineProperty(LXGrid, 'ClusterNameEnterpriseGroup', {
        value: "LXEnterpriseGroup"
    });

    Object.defineProperty(LXGrid, 'ClusterNameEnterpriseSubscription', {
        value: "LXEnterpriseSubscription"
    });

    Object.defineProperty(LXGrid, 'ClusterNameEnterpriseAccess', {
        value: "LXEnterpriseAccess"
    });

    Object.defineProperty(LXGrid, 'ClusterNameEnterpriseOnline', {
        value: "LXEnterpriseOnline"
    });

    Object.defineProperty(LXGrid, 'ClusterNameDealerAuth', {
        value: "LXDealerAuth"
    });

    Object.defineProperty(LXGrid, 'ClusterNameDealerUser', {
        value: "LXDealerUser"
    });

    Object.defineProperty(LXGrid, 'ClusterNameStatisticsDispatcher', {
        value: "LXStatisticsDispatcher"
    });

    Object.defineProperty(LXGrid, 'ClusterNameStatisticsProcessor', {
        value: "LXStatisticsProcessor"
    });

    Object.defineProperty(LXGrid, 'ClusterNameStatisticsAnalysis', {
        value: "LXStatisticsAnalysis"
    });

    Object.defineProperty(LXGrid, 'ClusterNameMachineMonitor', {
        value: "LXMachineMonitor"
    });

    Object.defineProperty(LXGrid, 'ClusterNameMachineCollection', {
        value: "LXMachineCollection"
    });

    Object.defineProperty(LXGrid, 'ClusterNameOMAction', {
        value: "LXOMAction"
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
