// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceEnterpriseAccess.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.OM/Enterprise/LXSliceEnterpriseDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Enterprise = __M.module("LXGrid.Enterprise");

    LXGrid.Enterprise.Access = __M.module("LXGrid.Enterprise.Access");

    Object.defineProperty(LXGrid.Enterprise.Access, 'IObjectEnterpriseAccessName', {
        value: "IObjectEnterpriseAccess"
    });

    LXGrid.Enterprise.Access.IObjectEnterpriseAccess = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Enterprise::Access::IObjectEnterpriseAccess"
        ],
        -1, undefined, undefined, false);

    LXGrid.Enterprise.Access.IObjectEnterpriseAccessPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Enterprise.Access.IObjectEnterpriseAccess.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Enterprise.Access.IObjectEnterpriseAccess, LXGrid.Enterprise.Access.IObjectEnterpriseAccessPrx,
    {
        "GetAccessTree": [, , , , , [LXGrid.Common.LXReturn], [[3]], [[7]], , , ],
        "AddAccessNode": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7], [7], [7], [7]], [[7]], , , ],
        "ModifyAccessNode": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7], [7], [7]], , , , ],
        "DelAccessNode": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7]], , , , ],
        "MoveAccessNode": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7], [7], [7]], , , , ],
        "GetUserAccessTree": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3]], [[7]], , , ],
        "GetGroupAccessTree": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3]], [[7]], , , ],
        "SetGroupAccessTree": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [3], [7]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
