// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceEnterpriseApp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.OM/Enterprise/LXSliceEnterpriseDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Enterprise = __M.module("LXGrid.Enterprise");

    LXGrid.Enterprise.App = __M.module("LXGrid.Enterprise.App");

    Object.defineProperty(LXGrid.Enterprise.App, 'IObjectEnterpriseAppName', {
        value: "IObjectEnterpriseApp"
    });

    LXGrid.Enterprise.App.IObjectEnterpriseApp = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Enterprise::App::IObjectEnterpriseApp"
        ],
        -1, undefined, undefined, false);

    LXGrid.Enterprise.App.IObjectEnterpriseAppPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Enterprise.App.IObjectEnterpriseApp.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Enterprise.App.IObjectEnterpriseApp, LXGrid.Enterprise.App.IObjectEnterpriseAppPrx,
    {
        "GetAppList": [, , , , , [LXGrid.Common.LXReturn], , [["Ice.IntSeqHelper"]], , , ],
        "GetAppInfo": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.Enterprise.SJAppInfo", true]], , , true],
        "SetAppInfo": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], ["LXGrid.Common.IntStringDictHelper"]], , , , ],
        "CreateApp": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], [[3]], , , ],
        "RemoveApp": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
