// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceEnterpriseSubscription.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.OM/Enterprise/LXSliceEnterpriseDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Enterprise = __M.module("LXGrid.Enterprise");

    LXGrid.Enterprise.Subscription = __M.module("LXGrid.Enterprise.Subscription");

    Object.defineProperty(LXGrid.Enterprise.Subscription, 'IObjectEnterpriseSubscriptionName', {
        value: "IObjectEnterpriseSubscription"
    });

    LXGrid.Enterprise.Subscription.IObjectEnterpriseSubscription = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Enterprise::Subscription::IObjectEnterpriseSubscription"
        ],
        -1, undefined, undefined, false);

    LXGrid.Enterprise.Subscription.IObjectEnterpriseSubscriptionPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Enterprise.Subscription.IObjectEnterpriseSubscription.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Enterprise.Subscription.IObjectEnterpriseSubscription, LXGrid.Enterprise.Subscription.IObjectEnterpriseSubscriptionPrx,
    {
        "GetUserAppList": [, , , , , [LXGrid.Common.LXReturn], [[3], [1]], [["Ice.IntSeqHelper"]], , , ],
        "GetAppUserList": [, , , , , [LXGrid.Common.LXReturn], [[3], [1]], [["Ice.IntSeqHelper"]], , , ],
        "CheckAppAccess": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], , , , ],
        "Subscription": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [3], [1]], , , , ],
        "GetGroupAppList": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["Ice.IntSeqHelper"]], , , ],
        "GetAppGroupList": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["Ice.IntSeqHelper"]], , , ],
        "CheckGroupAppAccess": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], , , , ],
        "SubscriptionGroup": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [3], [1]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
