// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceEnterpriseGroup.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.OM/Enterprise/LXSliceEnterpriseDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Enterprise = __M.module("LXGrid.Enterprise");

    LXGrid.Enterprise.Group = __M.module("LXGrid.Enterprise.Group");

    Object.defineProperty(LXGrid.Enterprise.Group, 'IObjectEnterpriseGroupName', {
        value: "IObjectEnterpriseGroup"
    });

    LXGrid.Enterprise.Group.IObjectEnterpriseGroup = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Enterprise::Group::IObjectEnterpriseGroup"
        ],
        -1, undefined, undefined, false);

    LXGrid.Enterprise.Group.IObjectEnterpriseGroupPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Enterprise.Group.IObjectEnterpriseGroup.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Enterprise.Group.IObjectEnterpriseGroup, LXGrid.Enterprise.Group.IObjectEnterpriseGroupPrx,
    {
        "CreateGroup": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7], [7]], [[3]], , , ],
        "DeleteGroup": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3]], , , , ],
        "AddGroupUser": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [3]], , , , ],
        "AddGroupUserSeq": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], ["Ice.IntSeqHelper"]], , , , ],
        "DelGroupUser": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [3]], , , , ],
        "SetGroupName": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7]], , , , ],
        "SetGroupIntro": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7]], , , , ],
        "SetGroupAdmin": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [3]], , , , ],
        "GetGroupUsers": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["Ice.IntSeqHelper"]], , , ],
        "GetUserGroups": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.Enterprise.SJGroupInfoSeqHelper"]], , , true],
        "GetGroupList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [[3], ["LXGrid.Enterprise.SJGroupInfoSeqHelper"]], , , true],
        "GetGroupIDList": [, , , , , [LXGrid.Common.LXReturn], , [["Ice.IntSeqHelper"]], , , ],
        "GetGroupInfo": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.Enterprise.SJGroupInfo", true]], , , true],
        "GetAdminGroupList": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.Enterprise.SJGroupInfoSeqHelper"]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
