// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceUserDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.User = __M.module("LXGrid.Main.User");

    /**
     * 用户信息项定义
     * 目前用于一次性多项修改接口
     **/
    LXGrid.Main.User.LXEnumUserInfoItem = Slice.defineEnum([
        ['LXUserInfoItemUName', 0], ['LXUserInfoItemGender', 1], ['LXUserInfoItemBirth', 2], ['LXUserInfoItemHometown', 3], ['LXUserInfoItemResidence', 4],
        ['LXUserInfoItemMarital', 5], ['LXUserInfoItemBloodType', 6], ['LXUserInfoItemSign', 7]]);

    LXGrid.Main.User.LXEnumUserGender = Slice.defineEnum([
        ['LXGenderUnknown', 0], ['LXGenderMale', 1], ['LXGenderFemale', 2]]);

    /**
     * 用户类型定义
     * 与Global::LXEnumObjectType相同，将来，用户信息模块中应该去除此定义，基于：
     * 1. 用户模块获取的应该全部是个人用户
     * 2. 用户模块也不会提供ObjectType的修改操作
     **/
    LXGrid.Main.User.LXEnumUserType = Slice.defineEnum([
        ['LXUserTypeUnknown', 0], ['LXUserTypePerson', 1], ['LXUserTypeSchoolClass', 2], ['LXUserTypeSchool', 3], ['LXUserTypeEduResearchGroup', 4],
        ['LXUserTypeEduOfficialOrg', 5], ['LXUserTypeEduOrg', 6], ['LXUserTypeParentGroup', 7], ['LXUserTypeNormalGroup', 8], ['LXUserTypeTeacherGroup', 9],
        ['LXUserTypeTeacherMasterGroup', 10], ['LXUserTypeAreaAsset', 22]]);

    LXGrid.Main.User.LXEnumUserRole = Slice.defineEnum([
        ['LXUserRoleUnknown', 0], ['LXUserRoleStudent', 1], ['LXUserRoleParent', 2], ['LXUserRoleTeacher', 3], ['LXUserRoleOfficial', 4],
        ['LXUserRoleSchoolMaster', 11], ['LXUserRoleSchoolAdmin', 12], ['LXUserRoleSchoolDean', 13], ['LXUserRoleSchoolMasterAssistant', 14], ['LXUserRoleCustomerServiceT1', 1001]]);

    LXGrid.Main.User.LXEnumBloodType = Slice.defineEnum([
        ['LXBloodTypeUnknown', 0], ['LXBloodTypeA', 1], ['LXBloodTypeB', 2], ['LXBloodTypeAB', 3], ['LXBloodTypeO', 4]]);

    LXGrid.Main.User.LXEnumMaritalState = Slice.defineEnum([
        ['LXMaritalStateUnknown', 0], ['LXMaritalStateMarried', 1], ['LXMaritalStateDiscoverture', 2]]);

    LXGrid.Main.User.LXUserMember = Slice.defineObject(
        function(app_id, timeExpired)
        {
            Ice.Object.call(this);
            this.app_id = app_id !== undefined ? app_id : 0;
            this.timeExpired = timeExpired !== undefined ? timeExpired : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::User::LXUserMember"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.app_id);
            __os.writeInt(this.timeExpired);
        },
        function(__is)
        {
            this.app_id = __is.readInt();
            this.timeExpired = __is.readInt();
        },
        false);

    LXGrid.Main.User.LXUserMemberPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.User.LXUserMember.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.User.LXUserMember, LXGrid.Main.User.LXUserMemberPrx);
    Slice.defineSequence(LXGrid.Main.User, "LXUserMemberSeqHelper", "Ice.ObjectHelper", false, "LXGrid.Main.User.LXUserMember");

    /**
     * 用户信息
     * 用户等级信息由网站层计算填充后再响应给客户端。
     **/
    LXGrid.Main.User.LXUserInfo = Slice.defineObject(
        function(user_id, auth_type, exper, gender, user_role, user_type, uname, phone_no, update_time, in_time, appMembers)
        {
            Ice.Object.call(this);
            this.user_id = user_id !== undefined ? user_id : 0;
            this.auth_type = auth_type !== undefined ? auth_type : 0;
            this.exper = exper !== undefined ? exper : 0;
            this.gender = gender !== undefined ? gender : LXGrid.Main.User.LXEnumUserGender.LXGenderUnknown;
            this.user_role = user_role !== undefined ? user_role : LXGrid.Main.User.LXEnumUserRole.LXUserRoleUnknown;
            this.user_type = user_type !== undefined ? user_type : LXGrid.Main.User.LXEnumUserType.LXUserTypeUnknown;
            this.uname = uname !== undefined ? uname : "";
            this.phone_no = phone_no !== undefined ? phone_no : "";
            this.update_time = update_time !== undefined ? update_time : 0;
            this.in_time = in_time !== undefined ? in_time : 0;
            this.appMembers = appMembers;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::User::LXUserInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.user_id);
            __os.writeInt(this.auth_type);
            __os.writeInt(this.exper);
            LXGrid.Main.User.LXEnumUserGender.__write(__os, this.gender);
            LXGrid.Main.User.LXEnumUserRole.__write(__os, this.user_role);
            LXGrid.Main.User.LXEnumUserType.__write(__os, this.user_type);
            __os.writeString(this.uname);
            __os.writeString(this.phone_no);
            __os.writeLong(this.update_time);
            __os.writeLong(this.in_time);
            LXGrid.Main.User.LXUserMemberSeqHelper.writeOpt(__os, 2, this.appMembers);
        },
        function(__is)
        {
            this.user_id = __is.readInt();
            this.auth_type = __is.readInt();
            this.exper = __is.readInt();
            this.gender = LXGrid.Main.User.LXEnumUserGender.__read(__is);
            this.user_role = LXGrid.Main.User.LXEnumUserRole.__read(__is);
            this.user_type = LXGrid.Main.User.LXEnumUserType.__read(__is);
            this.uname = __is.readString();
            this.phone_no = __is.readString();
            this.update_time = __is.readLong();
            this.in_time = __is.readLong();
            this.appMembers = LXGrid.Main.User.LXUserMemberSeqHelper.readOpt(__is, 2);
        },
        false);

    LXGrid.Main.User.LXUserInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.User.LXUserInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.User.LXUserInfo, LXGrid.Main.User.LXUserInfoPrx);
    Slice.defineSequence(LXGrid.Main.User, "LXUserInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.Main.User.LXUserInfo");

    LXGrid.Main.User.LXUserInfoExtend = Slice.defineObject(
        function(user_id, auth_type, exper, gender, user_role, user_type, uname, phone_no, update_time, in_time, appMembers, birth, hometown, residence, marital, blood_type, sign, birth2)
        {
            LXGrid.Main.User.LXUserInfo.call(this, user_id, auth_type, exper, gender, user_role, user_type, uname, phone_no, update_time, in_time, appMembers);
            this.birth = birth !== undefined ? birth : 0;
            this.hometown = hometown !== undefined ? hometown : 0;
            this.residence = residence !== undefined ? residence : 0;
            this.marital = marital !== undefined ? marital : LXGrid.Main.User.LXEnumMaritalState.LXMaritalStateUnknown;
            this.blood_type = blood_type !== undefined ? blood_type : LXGrid.Main.User.LXEnumBloodType.LXBloodTypeUnknown;
            this.sign = sign !== undefined ? sign : "";
            this.birth2 = birth2;
        },
        LXGrid.Main.User.LXUserInfo, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::Main::User::LXUserInfo",
            "::LXGrid::Main::User::LXUserInfoExtend"
        ],
        -1,
        function(__os)
        {
            __os.writeLong(this.birth);
            __os.writeInt(this.hometown);
            __os.writeInt(this.residence);
            LXGrid.Main.User.LXEnumMaritalState.__write(__os, this.marital);
            LXGrid.Main.User.LXEnumBloodType.__write(__os, this.blood_type);
            __os.writeString(this.sign);
            Ice.StringHelper.writeOpt(__os, 1, this.birth2);
        },
        function(__is)
        {
            this.birth = __is.readLong();
            this.hometown = __is.readInt();
            this.residence = __is.readInt();
            this.marital = LXGrid.Main.User.LXEnumMaritalState.__read(__is);
            this.blood_type = LXGrid.Main.User.LXEnumBloodType.__read(__is);
            this.sign = __is.readString();
            this.birth2 = Ice.StringHelper.readOpt(__is, 1);
        },
        false);

    LXGrid.Main.User.LXUserInfoExtendPrx = Slice.defineProxy(LXGrid.Main.User.LXUserInfoPrx, LXGrid.Main.User.LXUserInfoExtend.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.User.LXUserInfoExtend, LXGrid.Main.User.LXUserInfoExtendPrx);
    Slice.defineSequence(LXGrid.Main.User, "LXUserInfoExtendSeqHelper", "Ice.ObjectHelper", false, "LXGrid.Main.User.LXUserInfoExtend");
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
