// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceAuthDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Auth = __M.module("LXGrid.Main.Auth");

    LXGrid.Main.Auth.LXEnumErrorAuth = Slice.defineEnum([
        ['LXBusiErrorLoginNameNotExist', 11001], ['LXBusiErrorUserIdNotExist', 11002], ['LXBusiErrorPhoneNoNotExist', 11003], ['LXBusiErrorPhoneNoExist', 11004], ['LXBusiErrorUserNameNotExist', 11005],
        ['LXBusiErrorUserNameExist', 11006], ['LXBusiErrorPhoneNoSame', 11010], ['LXBusiErrorUserNameSame', 11011], ['LXBusiErrorPasswordSame', 11012], ['LXBusiErrorUserLocked', 11100],
        ['LXBusiErrorPasswordWrong', 11101], ['LXBusiErrorDeviceChanged', 11102], ['LXBusiErrorLoginNameChanged', 11103], ['LXBusiErrorDeviceUserLimit', 11104], ['LXBusiErrorMasterDeviceNotExist', 11105],
        ['LXBusiErrorUserDeleted', 11106], ['LXBusiErrorNoDevice', 11107], ['LXBusiErrorRegister', 11200], ['LXBusiErrorParentNotExist', 11300], ['LXBusiErrorNotParent', 11301],
        ['LXBusiErrorChildExist', 11302], ['LXBusiErrorChildLimit', 11303], ['LXBusiErrorDeleteNotAllow', 11310]]);

    LXGrid.Main.Auth.LXEnumRegisterPath = Slice.defineEnum([
        ['LXRegisterPath_Unkown', 0], ['LXRegisterPath_DB', 1], ['LXRegisterPath_Admin', 2], ['LXRegisterPath_Manual', 3], ['LXRegisterPath_App', 10],
        ['LXRegisterPath_Web', 11]]);

    LXGrid.Main.Auth.LXEnumRegisterSrc = Slice.defineEnum([
        ['LXRegisterSrc_Unkown', 0], ['LXRegisterSrc_Lexue', 1]]);

    LXGrid.Main.Auth.LXLoginType = Slice.defineEnum([
        ['LXLoginType_UserPass', 1], ['LXLoginType_Token', 2], ['LXLoginType_IM', 3]]);

    LXGrid.Main.Auth.LXAuthInfo2 = Slice.defineStruct(
        function(UserId, PhoneNo, UserName, IsChild, IsInitialPasswd, IsPhoneVerified, IsLogined, LastDevice, IsLocked, IsDeleted)
        {
            this.UserId = UserId !== undefined ? UserId : 0;
            this.PhoneNo = PhoneNo !== undefined ? PhoneNo : "";
            this.UserName = UserName !== undefined ? UserName : "";
            this.IsChild = IsChild !== undefined ? IsChild : false;
            this.IsInitialPasswd = IsInitialPasswd !== undefined ? IsInitialPasswd : false;
            this.IsPhoneVerified = IsPhoneVerified !== undefined ? IsPhoneVerified : false;
            this.IsLogined = IsLogined !== undefined ? IsLogined : false;
            this.LastDevice = LastDevice !== undefined ? LastDevice : "";
            this.IsLocked = IsLocked !== undefined ? IsLocked : false;
            this.IsDeleted = IsDeleted !== undefined ? IsDeleted : false;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.UserId);
            __os.writeString(this.PhoneNo);
            __os.writeString(this.UserName);
            __os.writeBool(this.IsChild);
            __os.writeBool(this.IsInitialPasswd);
            __os.writeBool(this.IsPhoneVerified);
            __os.writeBool(this.IsLogined);
            __os.writeString(this.LastDevice);
            __os.writeBool(this.IsLocked);
            __os.writeBool(this.IsDeleted);
        },
        function(__is)
        {
            this.UserId = __is.readInt();
            this.PhoneNo = __is.readString();
            this.UserName = __is.readString();
            this.IsChild = __is.readBool();
            this.IsInitialPasswd = __is.readBool();
            this.IsPhoneVerified = __is.readBool();
            this.IsLogined = __is.readBool();
            this.LastDevice = __is.readString();
            this.IsLocked = __is.readBool();
            this.IsDeleted = __is.readBool();
        },
        13, 
        false);
    Slice.defineSequence(LXGrid.Main.Auth, "LXAuthInfo2SeqHelper", "LXGrid.Main.Auth.LXAuthInfo2", false);

    LXGrid.Main.Auth.LXRegisterExtra = Slice.defineStruct(
        function(UserRole, UserGender, RealName, IpAddr)
        {
            this.UserRole = UserRole !== undefined ? UserRole : 0;
            this.UserGender = UserGender !== undefined ? UserGender : 0;
            this.RealName = RealName !== undefined ? RealName : "";
            this.IpAddr = IpAddr !== undefined ? IpAddr : "";
        },
        true,
        function(__os)
        {
            __os.writeInt(this.UserRole);
            __os.writeInt(this.UserGender);
            __os.writeString(this.RealName);
            __os.writeString(this.IpAddr);
        },
        function(__is)
        {
            this.UserRole = __is.readInt();
            this.UserGender = __is.readInt();
            this.RealName = __is.readString();
            this.IpAddr = __is.readString();
        },
        10, 
        false);

    LXGrid.Main.Auth.LXLoginExtra = Slice.defineStruct(
        function(Mode, AppId, AppVer, DeviceType, DeviceName, DeviceToken, IpAddr)
        {
            this.Mode = Mode !== undefined ? Mode : 0;
            this.AppId = AppId !== undefined ? AppId : 0;
            this.AppVer = AppVer !== undefined ? AppVer : 0;
            this.DeviceType = DeviceType !== undefined ? DeviceType : 0;
            this.DeviceName = DeviceName !== undefined ? DeviceName : "";
            this.DeviceToken = DeviceToken !== undefined ? DeviceToken : "";
            this.IpAddr = IpAddr !== undefined ? IpAddr : "";
        },
        true,
        function(__os)
        {
            __os.writeInt(this.Mode);
            __os.writeInt(this.AppId);
            __os.writeInt(this.AppVer);
            __os.writeInt(this.DeviceType);
            __os.writeString(this.DeviceName);
            __os.writeString(this.DeviceToken);
            __os.writeString(this.IpAddr);
        },
        function(__is)
        {
            this.Mode = __is.readInt();
            this.AppId = __is.readInt();
            this.AppVer = __is.readInt();
            this.DeviceType = __is.readInt();
            this.DeviceName = __is.readString();
            this.DeviceToken = __is.readString();
            this.IpAddr = __is.readString();
        },
        19, 
        false);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
