// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `GameTableInfo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var LXGrid = __M.module("LXGrid");

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.PoemsBattle = __M.module("LXGrid.App.PoemsBattle");

    LXGrid.App.PoemsBattle.GameStateEnum = Slice.defineEnum([
        ['StartTable', 0], ['Ready', 1], ['ChallengerDrawing', 2], ['BeChallengerSubmitAswnering', 3], ['BeChallengerDrawing', 4],
        ['ChallengerSubmitAswnering', 5], ['RoundOver', 6], ['GameOver', 7], ['SelectCard', 8]]);

    LXGrid.App.PoemsBattle.OnlineStateEnum = Slice.defineEnum([
        ['Online', 0], ['OffLine', 1], ['Hosting', 2]]);

    LXGrid.App.PoemsBattle.PlayerCategoryEnum = Slice.defineEnum([
        ['Robot', 0], ['Person', 1], ['Other', 2]]);

    LXGrid.App.PoemsBattle.MatchCardInfo = Slice.defineObject(
        function(CardId, CardLevel, CardAuthorId, CardAuthor, PoemNumber, Description)
        {
            Ice.Object.call(this);
            this.CardId = CardId !== undefined ? CardId : 0;
            this.CardLevel = CardLevel !== undefined ? CardLevel : 0;
            this.CardAuthorId = CardAuthorId !== undefined ? CardAuthorId : 0;
            this.CardAuthor = CardAuthor !== undefined ? CardAuthor : "";
            this.PoemNumber = PoemNumber !== undefined ? PoemNumber : 0;
            this.Description = Description !== undefined ? Description : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::MatchCardInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.CardId);
            __os.writeInt(this.CardLevel);
            __os.writeInt(this.CardAuthorId);
            __os.writeString(this.CardAuthor);
            __os.writeInt(this.PoemNumber);
            __os.writeString(this.Description);
        },
        function(__is)
        {
            this.CardId = __is.readInt();
            this.CardLevel = __is.readInt();
            this.CardAuthorId = __is.readInt();
            this.CardAuthor = __is.readString();
            this.PoemNumber = __is.readInt();
            this.Description = __is.readString();
        },
        false);

    LXGrid.App.PoemsBattle.MatchCardInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.MatchCardInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.MatchCardInfo, LXGrid.App.PoemsBattle.MatchCardInfoPrx);
    Slice.defineSequence(LXGrid.App.PoemsBattle, "MatchCardInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.PoemsBattle.MatchCardInfo");

    LXGrid.App.PoemsBattle.WaitMatchPlayer = Slice.defineObject(
        function(UserId, ChildId, UserName, UserSchoolName, LstCard, AllMainCardLevel, BattleTitle)
        {
            Ice.Object.call(this);
            this.UserId = UserId !== undefined ? UserId : 0;
            this.ChildId = ChildId !== undefined ? ChildId : 0;
            this.UserName = UserName !== undefined ? UserName : "";
            this.UserSchoolName = UserSchoolName !== undefined ? UserSchoolName : "";
            this.LstCard = LstCard !== undefined ? LstCard : null;
            this.AllMainCardLevel = AllMainCardLevel !== undefined ? AllMainCardLevel : 0;
            this.BattleTitle = BattleTitle !== undefined ? BattleTitle : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::WaitMatchPlayer"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.UserId);
            __os.writeInt(this.ChildId);
            __os.writeString(this.UserName);
            __os.writeString(this.UserSchoolName);
            LXGrid.App.PoemsBattle.MatchCardInfoSeqHelper.write(__os, this.LstCard);
            __os.writeInt(this.AllMainCardLevel);
            __os.writeString(this.BattleTitle);
        },
        function(__is)
        {
            this.UserId = __is.readInt();
            this.ChildId = __is.readInt();
            this.UserName = __is.readString();
            this.UserSchoolName = __is.readString();
            this.LstCard = LXGrid.App.PoemsBattle.MatchCardInfoSeqHelper.read(__is);
            this.AllMainCardLevel = __is.readInt();
            this.BattleTitle = __is.readString();
        },
        false);

    LXGrid.App.PoemsBattle.WaitMatchPlayerPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.WaitMatchPlayer.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.WaitMatchPlayer, LXGrid.App.PoemsBattle.WaitMatchPlayerPrx);

    LXGrid.App.PoemsBattle.WaitMatchTable = Slice.defineObject(
        function(MatchId, MatchSubId, TableId, Challenger, BeChallenger, CrateTime)
        {
            Ice.Object.call(this);
            this.MatchId = MatchId !== undefined ? MatchId : 0;
            this.MatchSubId = MatchSubId !== undefined ? MatchSubId : 0;
            this.TableId = TableId !== undefined ? TableId : "";
            this.Challenger = Challenger !== undefined ? Challenger : null;
            this.BeChallenger = BeChallenger !== undefined ? BeChallenger : null;
            this.CrateTime = CrateTime !== undefined ? CrateTime : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::WaitMatchTable"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.MatchId);
            __os.writeInt(this.MatchSubId);
            __os.writeString(this.TableId);
            __os.writeObject(this.Challenger);
            __os.writeObject(this.BeChallenger);
            __os.writeString(this.CrateTime);
        },
        function(__is)
        {
            var self = this;
            this.MatchId = __is.readInt();
            this.MatchSubId = __is.readInt();
            this.TableId = __is.readString();
            __is.readObject(function(__o){ self.Challenger = __o; }, LXGrid.App.PoemsBattle.WaitMatchPlayer);
            __is.readObject(function(__o){ self.BeChallenger = __o; }, LXGrid.App.PoemsBattle.WaitMatchPlayer);
            this.CrateTime = __is.readString();
        },
        false);

    LXGrid.App.PoemsBattle.WaitMatchTablePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.WaitMatchTable.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.WaitMatchTable, LXGrid.App.PoemsBattle.WaitMatchTablePrx);

    LXGrid.App.PoemsBattle.BaseMatchGamePlayer = Slice.defineObject(
        function(UserID, UserName, HP, HPTotal)
        {
            Ice.Object.call(this);
            this.UserID = UserID !== undefined ? UserID : 0;
            this.UserName = UserName !== undefined ? UserName : "";
            this.HP = HP !== undefined ? HP : 0;
            this.HPTotal = HPTotal !== undefined ? HPTotal : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::BaseMatchGamePlayer"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.UserID);
            __os.writeString(this.UserName);
            __os.writeInt(this.HP);
            __os.writeInt(this.HPTotal);
        },
        function(__is)
        {
            this.UserID = __is.readInt();
            this.UserName = __is.readString();
            this.HP = __is.readInt();
            this.HPTotal = __is.readInt();
        },
        false);

    LXGrid.App.PoemsBattle.BaseMatchGamePlayerPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.BaseMatchGamePlayer.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.BaseMatchGamePlayer, LXGrid.App.PoemsBattle.BaseMatchGamePlayerPrx);

    LXGrid.App.PoemsBattle.QuestionOption = Slice.defineObject(
        function(QuestionBankId, OptionValue, OptionMark)
        {
            Ice.Object.call(this);
            this.QuestionBankId = QuestionBankId !== undefined ? QuestionBankId : 0;
            this.OptionValue = OptionValue !== undefined ? OptionValue : "";
            this.OptionMark = OptionMark !== undefined ? OptionMark : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::QuestionOption"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.QuestionBankId);
            __os.writeString(this.OptionValue);
            __os.writeString(this.OptionMark);
        },
        function(__is)
        {
            this.QuestionBankId = __is.readInt();
            this.OptionValue = __is.readString();
            this.OptionMark = __is.readString();
        },
        false);

    LXGrid.App.PoemsBattle.QuestionOptionPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.QuestionOption.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.QuestionOption, LXGrid.App.PoemsBattle.QuestionOptionPrx);
    Slice.defineSequence(LXGrid.App.PoemsBattle, "QuestionOptionsHelper", "Ice.ObjectHelper", false, "LXGrid.App.PoemsBattle.QuestionOption");

    LXGrid.App.PoemsBattle.PoemQuestionInfo = Slice.defineObject(
        function(QuestionBankId, PoemsId, Diff, QuestionType, QuestionModelId, QuestionTitle, QuestionContent, CorrectAnswer)
        {
            Ice.Object.call(this);
            this.QuestionBankId = QuestionBankId !== undefined ? QuestionBankId : 0;
            this.PoemsId = PoemsId !== undefined ? PoemsId : 0;
            this.Diff = Diff !== undefined ? Diff : 0;
            this.QuestionType = QuestionType !== undefined ? QuestionType : 0;
            this.QuestionModelId = QuestionModelId !== undefined ? QuestionModelId : 0;
            this.QuestionTitle = QuestionTitle !== undefined ? QuestionTitle : "";
            this.QuestionContent = QuestionContent !== undefined ? QuestionContent : "";
            this.CorrectAnswer = CorrectAnswer !== undefined ? CorrectAnswer : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::PoemQuestionInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.QuestionBankId);
            __os.writeInt(this.PoemsId);
            __os.writeInt(this.Diff);
            __os.writeInt(this.QuestionType);
            __os.writeInt(this.QuestionModelId);
            __os.writeString(this.QuestionTitle);
            __os.writeString(this.QuestionContent);
            __os.writeString(this.CorrectAnswer);
        },
        function(__is)
        {
            this.QuestionBankId = __is.readInt();
            this.PoemsId = __is.readInt();
            this.Diff = __is.readInt();
            this.QuestionType = __is.readInt();
            this.QuestionModelId = __is.readInt();
            this.QuestionTitle = __is.readString();
            this.QuestionContent = __is.readString();
            this.CorrectAnswer = __is.readString();
        },
        false);

    LXGrid.App.PoemsBattle.PoemQuestionInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.PoemQuestionInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.PoemQuestionInfo, LXGrid.App.PoemsBattle.PoemQuestionInfoPrx);

    LXGrid.App.PoemsBattle.GameTableQuestionInfo = Slice.defineObject(
        function(Question, Options, AnswerQuestionTime, UserAnswer, AnswerResult, SubmitAnswerTime, DrawTime)
        {
            Ice.Object.call(this);
            this.Question = Question !== undefined ? Question : null;
            this.Options = Options !== undefined ? Options : null;
            this.AnswerQuestionTime = AnswerQuestionTime !== undefined ? AnswerQuestionTime : 0;
            this.UserAnswer = UserAnswer !== undefined ? UserAnswer : "";
            this.AnswerResult = AnswerResult !== undefined ? AnswerResult : 0;
            this.SubmitAnswerTime = SubmitAnswerTime !== undefined ? SubmitAnswerTime : "";
            this.DrawTime = DrawTime !== undefined ? DrawTime : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::GameTableQuestionInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeObject(this.Question);
            LXGrid.App.PoemsBattle.QuestionOptionsHelper.write(__os, this.Options);
            __os.writeInt(this.AnswerQuestionTime);
            __os.writeString(this.UserAnswer);
            __os.writeInt(this.AnswerResult);
            __os.writeString(this.SubmitAnswerTime);
            __os.writeString(this.DrawTime);
        },
        function(__is)
        {
            var self = this;
            __is.readObject(function(__o){ self.Question = __o; }, LXGrid.App.PoemsBattle.PoemQuestionInfo);
            this.Options = LXGrid.App.PoemsBattle.QuestionOptionsHelper.read(__is);
            this.AnswerQuestionTime = __is.readInt();
            this.UserAnswer = __is.readString();
            this.AnswerResult = __is.readInt();
            this.SubmitAnswerTime = __is.readString();
            this.DrawTime = __is.readString();
        },
        false);

    LXGrid.App.PoemsBattle.GameTableQuestionInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.GameTableQuestionInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.GameTableQuestionInfo, LXGrid.App.PoemsBattle.GameTableQuestionInfoPrx);

    LXGrid.App.PoemsBattle.AnswerResponseInfo = Slice.defineObject(
        function(UserAnswer, AnswerResult, TableState, Challenger, BeChallenger)
        {
            Ice.Object.call(this);
            this.UserAnswer = UserAnswer !== undefined ? UserAnswer : "";
            this.AnswerResult = AnswerResult !== undefined ? AnswerResult : 0;
            this.TableState = TableState !== undefined ? TableState : 0;
            this.Challenger = Challenger !== undefined ? Challenger : null;
            this.BeChallenger = BeChallenger !== undefined ? BeChallenger : null;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::AnswerResponseInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.UserAnswer);
            __os.writeInt(this.AnswerResult);
            __os.writeInt(this.TableState);
            __os.writeObject(this.Challenger);
            __os.writeObject(this.BeChallenger);
        },
        function(__is)
        {
            var self = this;
            this.UserAnswer = __is.readString();
            this.AnswerResult = __is.readInt();
            this.TableState = __is.readInt();
            __is.readObject(function(__o){ self.Challenger = __o; }, LXGrid.App.PoemsBattle.BaseMatchGamePlayer);
            __is.readObject(function(__o){ self.BeChallenger = __o; }, LXGrid.App.PoemsBattle.BaseMatchGamePlayer);
        },
        false);

    LXGrid.App.PoemsBattle.AnswerResponseInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.AnswerResponseInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.AnswerResponseInfo, LXGrid.App.PoemsBattle.AnswerResponseInfoPrx);

    LXGrid.App.PoemsBattle.GameOverPrizeInfo = Slice.defineObject(
        function(IsWin, Score, Silver, CorrectNum, Round, TimeSpan)
        {
            Ice.Object.call(this);
            this.IsWin = IsWin !== undefined ? IsWin : false;
            this.Score = Score !== undefined ? Score : 0;
            this.Silver = Silver !== undefined ? Silver : 0;
            this.CorrectNum = CorrectNum !== undefined ? CorrectNum : 0;
            this.Round = Round !== undefined ? Round : 0;
            this.TimeSpan = TimeSpan !== undefined ? TimeSpan : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::GameOverPrizeInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeBool(this.IsWin);
            __os.writeInt(this.Score);
            __os.writeInt(this.Silver);
            __os.writeInt(this.CorrectNum);
            __os.writeInt(this.Round);
            __os.writeInt(this.TimeSpan);
        },
        function(__is)
        {
            this.IsWin = __is.readBool();
            this.Score = __is.readInt();
            this.Silver = __is.readInt();
            this.CorrectNum = __is.readInt();
            this.Round = __is.readInt();
            this.TimeSpan = __is.readInt();
        },
        false);

    LXGrid.App.PoemsBattle.GameOverPrizeInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.GameOverPrizeInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.GameOverPrizeInfo, LXGrid.App.PoemsBattle.GameOverPrizeInfoPrx);

    LXGrid.App.PoemsBattle.MatchCardDetailInfo = Slice.defineObject(
        function(CardId, CardAutherId, CardPlateName, CardPlateLevel, CardPlateExper, CardPlateBlood, CardMaterial, CardPlateAttack, CardPlateMagic, CardPlateWit, CardPlatePomes, NeedRoundNum, RemainingRoundNum)
        {
            Ice.Object.call(this);
            this.CardId = CardId !== undefined ? CardId : 0;
            this.CardAutherId = CardAutherId !== undefined ? CardAutherId : 0;
            this.CardPlateName = CardPlateName !== undefined ? CardPlateName : "";
            this.CardPlateLevel = CardPlateLevel !== undefined ? CardPlateLevel : 0;
            this.CardPlateExper = CardPlateExper !== undefined ? CardPlateExper : 0;
            this.CardPlateBlood = CardPlateBlood !== undefined ? CardPlateBlood : 0;
            this.CardMaterial = CardMaterial !== undefined ? CardMaterial : 0;
            this.CardPlateAttack = CardPlateAttack !== undefined ? CardPlateAttack : 0;
            this.CardPlateMagic = CardPlateMagic !== undefined ? CardPlateMagic : 0;
            this.CardPlateWit = CardPlateWit !== undefined ? CardPlateWit : 0;
            this.CardPlatePomes = CardPlatePomes !== undefined ? CardPlatePomes : 0;
            this.NeedRoundNum = NeedRoundNum !== undefined ? NeedRoundNum : 0;
            this.RemainingRoundNum = RemainingRoundNum !== undefined ? RemainingRoundNum : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::MatchCardDetailInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.CardId);
            __os.writeInt(this.CardAutherId);
            __os.writeString(this.CardPlateName);
            __os.writeInt(this.CardPlateLevel);
            __os.writeInt(this.CardPlateExper);
            __os.writeInt(this.CardPlateBlood);
            __os.writeInt(this.CardMaterial);
            __os.writeInt(this.CardPlateAttack);
            __os.writeInt(this.CardPlateMagic);
            __os.writeInt(this.CardPlateWit);
            __os.writeInt(this.CardPlatePomes);
            __os.writeInt(this.NeedRoundNum);
            __os.writeInt(this.RemainingRoundNum);
        },
        function(__is)
        {
            this.CardId = __is.readInt();
            this.CardAutherId = __is.readInt();
            this.CardPlateName = __is.readString();
            this.CardPlateLevel = __is.readInt();
            this.CardPlateExper = __is.readInt();
            this.CardPlateBlood = __is.readInt();
            this.CardMaterial = __is.readInt();
            this.CardPlateAttack = __is.readInt();
            this.CardPlateMagic = __is.readInt();
            this.CardPlateWit = __is.readInt();
            this.CardPlatePomes = __is.readInt();
            this.NeedRoundNum = __is.readInt();
            this.RemainingRoundNum = __is.readInt();
        },
        false);

    LXGrid.App.PoemsBattle.MatchCardDetailInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.MatchCardDetailInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.MatchCardDetailInfo, LXGrid.App.PoemsBattle.MatchCardDetailInfoPrx);
    Slice.defineSequence(LXGrid.App.PoemsBattle, "MatchCardDetailInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.PoemsBattle.MatchCardDetailInfo");

    LXGrid.App.PoemsBattle.MatchGamePlayer = Slice.defineObject(
        function(UserID, UserName, HP, HPTotal, PlayerCat, Level, Sex, GameState, OnlineState, CurrentBattlerCard, BattlerCards, Prize)
        {
            LXGrid.App.PoemsBattle.BaseMatchGamePlayer.call(this, UserID, UserName, HP, HPTotal);
            this.PlayerCat = PlayerCat !== undefined ? PlayerCat : LXGrid.App.PoemsBattle.PlayerCategoryEnum.Robot;
            this.Level = Level !== undefined ? Level : 0;
            this.Sex = Sex !== undefined ? Sex : 0;
            this.GameState = GameState !== undefined ? GameState : LXGrid.App.PoemsBattle.GameStateEnum.StartTable;
            this.OnlineState = OnlineState !== undefined ? OnlineState : LXGrid.App.PoemsBattle.OnlineStateEnum.Online;
            this.CurrentBattlerCard = CurrentBattlerCard !== undefined ? CurrentBattlerCard : null;
            this.BattlerCards = BattlerCards !== undefined ? BattlerCards : null;
            this.Prize = Prize !== undefined ? Prize : null;
        },
        LXGrid.App.PoemsBattle.BaseMatchGamePlayer, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::BaseMatchGamePlayer",
            "::LXGrid::App::PoemsBattle::MatchGamePlayer"
        ],
        -1,
        function(__os)
        {
            LXGrid.App.PoemsBattle.PlayerCategoryEnum.__write(__os, this.PlayerCat);
            __os.writeInt(this.Level);
            __os.writeInt(this.Sex);
            LXGrid.App.PoemsBattle.GameStateEnum.__write(__os, this.GameState);
            LXGrid.App.PoemsBattle.OnlineStateEnum.__write(__os, this.OnlineState);
            __os.writeObject(this.CurrentBattlerCard);
            LXGrid.App.PoemsBattle.MatchCardDetailInfoSeqHelper.write(__os, this.BattlerCards);
            __os.writeObject(this.Prize);
        },
        function(__is)
        {
            var self = this;
            this.PlayerCat = LXGrid.App.PoemsBattle.PlayerCategoryEnum.__read(__is);
            this.Level = __is.readInt();
            this.Sex = __is.readInt();
            this.GameState = LXGrid.App.PoemsBattle.GameStateEnum.__read(__is);
            this.OnlineState = LXGrid.App.PoemsBattle.OnlineStateEnum.__read(__is);
            __is.readObject(function(__o){ self.CurrentBattlerCard = __o; }, LXGrid.App.PoemsBattle.MatchCardDetailInfo);
            this.BattlerCards = LXGrid.App.PoemsBattle.MatchCardDetailInfoSeqHelper.read(__is);
            __is.readObject(function(__o){ self.Prize = __o; }, LXGrid.App.PoemsBattle.GameOverPrizeInfo);
        },
        false);

    LXGrid.App.PoemsBattle.MatchGamePlayerPrx = Slice.defineProxy(LXGrid.App.PoemsBattle.BaseMatchGamePlayerPrx, LXGrid.App.PoemsBattle.MatchGamePlayer.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.MatchGamePlayer, LXGrid.App.PoemsBattle.MatchGamePlayerPrx);

    LXGrid.App.PoemsBattle.GameTableInfo = Slice.defineObject(
        function(TableID, TableQuestionInfo, CurrentState, CurrentRound, Challenger, BeChallenger, TimeOutSecond, ActivationDateStr)
        {
            Ice.Object.call(this);
            this.TableID = TableID !== undefined ? TableID : "";
            this.TableQuestionInfo = TableQuestionInfo !== undefined ? TableQuestionInfo : null;
            this.CurrentState = CurrentState !== undefined ? CurrentState : LXGrid.App.PoemsBattle.GameStateEnum.StartTable;
            this.CurrentRound = CurrentRound !== undefined ? CurrentRound : 0;
            this.Challenger = Challenger !== undefined ? Challenger : null;
            this.BeChallenger = BeChallenger !== undefined ? BeChallenger : null;
            this.TimeOutSecond = TimeOutSecond !== undefined ? TimeOutSecond : 0;
            this.ActivationDateStr = ActivationDateStr !== undefined ? ActivationDateStr : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::GameTableInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.TableID);
            __os.writeObject(this.TableQuestionInfo);
            LXGrid.App.PoemsBattle.GameStateEnum.__write(__os, this.CurrentState);
            __os.writeInt(this.CurrentRound);
            __os.writeObject(this.Challenger);
            __os.writeObject(this.BeChallenger);
            __os.writeInt(this.TimeOutSecond);
            __os.writeString(this.ActivationDateStr);
        },
        function(__is)
        {
            var self = this;
            this.TableID = __is.readString();
            __is.readObject(function(__o){ self.TableQuestionInfo = __o; }, LXGrid.App.PoemsBattle.GameTableQuestionInfo);
            this.CurrentState = LXGrid.App.PoemsBattle.GameStateEnum.__read(__is);
            this.CurrentRound = __is.readInt();
            __is.readObject(function(__o){ self.Challenger = __o; }, LXGrid.App.PoemsBattle.MatchGamePlayer);
            __is.readObject(function(__o){ self.BeChallenger = __o; }, LXGrid.App.PoemsBattle.MatchGamePlayer);
            this.TimeOutSecond = __is.readInt();
            this.ActivationDateStr = __is.readString();
        },
        false);

    LXGrid.App.PoemsBattle.GameTableInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.GameTableInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.GameTableInfo, LXGrid.App.PoemsBattle.GameTableInfoPrx);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
