// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `IObjectUserStatistics.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.App/PoemsBattle/GameTableInfo",
        "LXGrid.App/PoemsBattle/UserStatisticsInfo"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.PoemsBattle = __M.module("LXGrid.App.PoemsBattle");

    Object.defineProperty(LXGrid.App.PoemsBattle, 'IObjectUserStatisticsName', {
        value: "IObjectUserStatistics"
    });

    LXGrid.App.PoemsBattle.IObjectUserStatistics = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::IObjectUserStatistics",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.PoemsBattle.IObjectUserStatisticsPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.IObjectUserStatistics.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.PoemsBattle.IObjectUserStatistics, LXGrid.App.PoemsBattle.IObjectUserStatisticsPrx,
    {
        "GetUserMainCards": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.PoemsBattle.MatchCardInfoSeqHelper"]], , , true],
        "GetUserBattleStat": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.PoemsBattle.UserBattleStat", true]], , , true],
        "GetUserAreaRanking": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3]], [[3]], , , ],
        "OperatTableId": [, , , , , [LXGrid.Common.LXReturn], [[3], [7], [LXGrid.App.PoemsBattle.UserTableOperat.__helper]], [[7]], , , ],
        "GetUserPhysicalScore": [, , , , , [LXGrid.Common.LXReturn], [[3]], [[3], [3]], , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
