// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `IObjectBattle.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.App/PoemsBattle/GameTableInfo",
        "LXGrid.App/PoemsBattle/BattleInfo",
        "LXGrid.App/PoemsBattle/BattleCommon"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.PoemsBattle = __M.module("LXGrid.App.PoemsBattle");

    Object.defineProperty(LXGrid.App.PoemsBattle, 'IObjectBattleName', {
        value: "IObjectBattle"
    });

    LXGrid.App.PoemsBattle.IObjectBattle = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::IObjectBattle",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.PoemsBattle.IObjectBattlePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.IObjectBattle.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.PoemsBattle.IObjectBattle, LXGrid.App.PoemsBattle.IObjectBattlePrx,
    {
        "GetAllBattle": [, , , , , [LXGrid.Common.LXReturn], , [["LXGrid.App.PoemsBattle.BattleInfoSeqHelper"]], , , true],
        "GetBattleById": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.PoemsBattle.BattleInfo", true]], , , true],
        "GetBattleStat": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.PoemsBattle.BattleStatistics", true]], , , true],
        "GetBattleTopRanking": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3]], [["LXGrid.App.PoemsBattle.IntSeqHelper"]], , , ],
        "FindRival": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [7], [3]], [["LXGrid.App.PoemsBattle.WaitMatchTable", true]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
