// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `IObjectGameTable.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.App/PoemsBattle/GameTableInfo",
        "LXGrid.System/LXSliceBase"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.PoemsBattle = __M.module("LXGrid.App.PoemsBattle");

    Object.defineProperty(LXGrid.App.PoemsBattle, 'IObjectGameTableName', {
        value: "IObjectGameTable"
    });

    LXGrid.App.PoemsBattle.IObjectGameTable = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::IObjectGameTable",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.PoemsBattle.IObjectGameTablePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.IObjectGameTable.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.PoemsBattle.IObjectGameTable, LXGrid.App.PoemsBattle.IObjectGameTablePrx,
    {
        "GetGameTableInfo": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.App.PoemsBattle.GameTableInfo", true]], , , true],
        "StartTable": [, , , , , [LXGrid.Common.LXReturn], [[7], [3], ["LXGrid.App.PoemsBattle.WaitMatchPlayer", true], ["LXGrid.App.PoemsBattle.WaitMatchPlayer", true]], [[1]], , true, ],
        "SynchronousUserState": [, , , , , [LXGrid.Common.LXReturn], [[7], [3], [3], [3]], [[3], [3], [3]], , , ],
        "SubmitAnswer": [, , , , , [LXGrid.Common.LXReturn], [[7], [3], [7]], [["LXGrid.App.PoemsBattle.AnswerResponseInfo", true]], , , true],
        "GetQuestionInfo": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.App.PoemsBattle.GameTableQuestionInfo", true]], , , true],
        "GetQuestionAnswer": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.App.PoemsBattle.AnswerResponseInfo", true]], , , true],
        "SetCurrentCard": [, , , , , [LXGrid.Common.LXReturn], [[7], [3], [3]], [["LXGrid.App.PoemsBattle.MatchCardDetailInfoSeqHelper"], [3]], , , true],
        "GetUserPrize": [, , , , , [LXGrid.Common.LXReturn], [[7], [3]], [["LXGrid.App.PoemsBattle.GameOverPrizeInfo", true]], , , true],
        "GetOppositeCurrentCard": [, , , , , [LXGrid.Common.LXReturn], [[7], [3]], [["LXGrid.App.PoemsBattle.MatchCardDetailInfo", true]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
