// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `MatchCardInfo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var LXGrid = __M.module("LXGrid");

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.PoemsBattle = __M.module("LXGrid.App.PoemsBattle");

    LXGrid.App.PoemsBattle.PoemLine = Slice.defineObject(
        function(LineIndex, LineContent)
        {
            Ice.Object.call(this);
            this.LineIndex = LineIndex !== undefined ? LineIndex : 0;
            this.LineContent = LineContent !== undefined ? LineContent : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::PoemLine"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.LineIndex);
            __os.writeString(this.LineContent);
        },
        function(__is)
        {
            this.LineIndex = __is.readInt();
            this.LineContent = __is.readString();
        },
        false);

    LXGrid.App.PoemsBattle.PoemLinePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.PoemLine.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.PoemLine, LXGrid.App.PoemsBattle.PoemLinePrx);
    Slice.defineSequence(LXGrid.App.PoemsBattle, "PoemLineSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.PoemsBattle.PoemLine");

    LXGrid.App.PoemsBattle.PoemLineInfo = Slice.defineObject(
        function(PoemLines, PoemAuthor, Dynasty, MP3Url)
        {
            Ice.Object.call(this);
            this.PoemLines = PoemLines !== undefined ? PoemLines : null;
            this.PoemAuthor = PoemAuthor !== undefined ? PoemAuthor : "";
            this.Dynasty = Dynasty !== undefined ? Dynasty : "";
            this.MP3Url = MP3Url !== undefined ? MP3Url : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::PoemLineInfo"
        ],
        -1,
        function(__os)
        {
            LXGrid.App.PoemsBattle.PoemLineSeqHelper.write(__os, this.PoemLines);
            __os.writeString(this.PoemAuthor);
            __os.writeString(this.Dynasty);
            __os.writeString(this.MP3Url);
        },
        function(__is)
        {
            this.PoemLines = LXGrid.App.PoemsBattle.PoemLineSeqHelper.read(__is);
            this.PoemAuthor = __is.readString();
            this.Dynasty = __is.readString();
            this.MP3Url = __is.readString();
        },
        false);

    LXGrid.App.PoemsBattle.PoemLineInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.PoemLineInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.PoemLineInfo, LXGrid.App.PoemsBattle.PoemLineInfoPrx);

    LXGrid.App.PoemsBattle.PoemInfo = Slice.defineObject(
        function(PoemId, PoemTitle, PoemIndex)
        {
            Ice.Object.call(this);
            this.PoemId = PoemId !== undefined ? PoemId : 0;
            this.PoemTitle = PoemTitle !== undefined ? PoemTitle : "";
            this.PoemIndex = PoemIndex !== undefined ? PoemIndex : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::PoemInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.PoemId);
            __os.writeString(this.PoemTitle);
            __os.writeInt(this.PoemIndex);
        },
        function(__is)
        {
            this.PoemId = __is.readInt();
            this.PoemTitle = __is.readString();
            this.PoemIndex = __is.readInt();
        },
        false);

    LXGrid.App.PoemsBattle.PoemInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.PoemInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.PoemInfo, LXGrid.App.PoemsBattle.PoemInfoPrx);
    Slice.defineSequence(LXGrid.App.PoemsBattle, "PoemInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.PoemsBattle.PoemInfo");

    LXGrid.App.PoemsBattle.MatchCardInfo = Slice.defineObject(
        function(CardId, CardLevel, CardAuthorId, CardAuthor, PoemNumber, Description, lstPoemInfo)
        {
            Ice.Object.call(this);
            this.CardId = CardId !== undefined ? CardId : 0;
            this.CardLevel = CardLevel !== undefined ? CardLevel : 0;
            this.CardAuthorId = CardAuthorId !== undefined ? CardAuthorId : 0;
            this.CardAuthor = CardAuthor !== undefined ? CardAuthor : "";
            this.PoemNumber = PoemNumber !== undefined ? PoemNumber : 0;
            this.Description = Description !== undefined ? Description : "";
            this.lstPoemInfo = lstPoemInfo !== undefined ? lstPoemInfo : null;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::MatchCardInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.CardId);
            __os.writeInt(this.CardLevel);
            __os.writeInt(this.CardAuthorId);
            __os.writeString(this.CardAuthor);
            __os.writeInt(this.PoemNumber);
            __os.writeString(this.Description);
            LXGrid.App.PoemsBattle.PoemInfoSeqHelper.write(__os, this.lstPoemInfo);
        },
        function(__is)
        {
            this.CardId = __is.readInt();
            this.CardLevel = __is.readInt();
            this.CardAuthorId = __is.readInt();
            this.CardAuthor = __is.readString();
            this.PoemNumber = __is.readInt();
            this.Description = __is.readString();
            this.lstPoemInfo = LXGrid.App.PoemsBattle.PoemInfoSeqHelper.read(__is);
        },
        false);

    LXGrid.App.PoemsBattle.MatchCardInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.MatchCardInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.MatchCardInfo, LXGrid.App.PoemsBattle.MatchCardInfoPrx);
    Slice.defineSequence(LXGrid.App.PoemsBattle, "MatchCardInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.PoemsBattle.MatchCardInfo");

    LXGrid.App.PoemsBattle.MatchCardDetailInfo = Slice.defineObject(
        function(CardId, CardAutherId, CardPlateName, CardPlateLevel, CardPlateExper, CardPlateBlood, CardMaterial, CardPlateAttack, CardPlateMagic, CardPlateWit, CardPlatePomes, NeedRounNum)
        {
            Ice.Object.call(this);
            this.CardId = CardId !== undefined ? CardId : 0;
            this.CardAutherId = CardAutherId !== undefined ? CardAutherId : 0;
            this.CardPlateName = CardPlateName !== undefined ? CardPlateName : "";
            this.CardPlateLevel = CardPlateLevel !== undefined ? CardPlateLevel : 0;
            this.CardPlateExper = CardPlateExper !== undefined ? CardPlateExper : 0;
            this.CardPlateBlood = CardPlateBlood !== undefined ? CardPlateBlood : 0;
            this.CardMaterial = CardMaterial !== undefined ? CardMaterial : 0;
            this.CardPlateAttack = CardPlateAttack !== undefined ? CardPlateAttack : 0;
            this.CardPlateMagic = CardPlateMagic !== undefined ? CardPlateMagic : 0;
            this.CardPlateWit = CardPlateWit !== undefined ? CardPlateWit : 0;
            this.CardPlatePomes = CardPlatePomes !== undefined ? CardPlatePomes : 0;
            this.NeedRounNum = NeedRounNum !== undefined ? NeedRounNum : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::PoemsBattle::MatchCardDetailInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.CardId);
            __os.writeInt(this.CardAutherId);
            __os.writeString(this.CardPlateName);
            __os.writeInt(this.CardPlateLevel);
            __os.writeInt(this.CardPlateExper);
            __os.writeInt(this.CardPlateBlood);
            __os.writeInt(this.CardMaterial);
            __os.writeInt(this.CardPlateAttack);
            __os.writeInt(this.CardPlateMagic);
            __os.writeInt(this.CardPlateWit);
            __os.writeInt(this.CardPlatePomes);
            __os.writeInt(this.NeedRounNum);
        },
        function(__is)
        {
            this.CardId = __is.readInt();
            this.CardAutherId = __is.readInt();
            this.CardPlateName = __is.readString();
            this.CardPlateLevel = __is.readInt();
            this.CardPlateExper = __is.readInt();
            this.CardPlateBlood = __is.readInt();
            this.CardMaterial = __is.readInt();
            this.CardPlateAttack = __is.readInt();
            this.CardPlateMagic = __is.readInt();
            this.CardPlateWit = __is.readInt();
            this.CardPlatePomes = __is.readInt();
            this.NeedRounNum = __is.readInt();
        },
        false);

    LXGrid.App.PoemsBattle.MatchCardDetailInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.PoemsBattle.MatchCardDetailInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.PoemsBattle.MatchCardDetailInfo, LXGrid.App.PoemsBattle.MatchCardDetailInfoPrx);
    Slice.defineSequence(LXGrid.App.PoemsBattle, "MatchCardDetailInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.PoemsBattle.MatchCardDetailInfo");
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
