// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceVote.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.App/Vote/VoteEntity"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    Object.defineProperty(LXGrid.App, 'IVoteName', {
        value: "IVote"
    });

    LXGrid.App.IVote = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::IVote",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.IVotePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.IVote.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.IVote, LXGrid.App.IVotePrx,
    {
        "PostAddVote": [, , , , , [LXGrid.Common.LXReturn], [[LXGrid.App.AddVoteParam], [7]], [[7]], , , ],
        "PostVoted": [, , , , , [LXGrid.Common.LXReturn], [[7], [7], [7], [7], [7]], [[1]], , , ],
        "GetVoteByID": [, , , , , [LXGrid.Common.LXReturn], [[7], [7]], [[LXGrid.App.VoteMainEntity]], , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
