// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceSchoolDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.School = __M.module("LXGrid.Main.School");

    LXGrid.Main.School.LXEnumErrorSchool = Slice.defineEnum([
        ['LXBusiErrorNotSchool', 22001], ['LXBusiErrorNotClass', 22002], ['LXBusiErrorNotSchoolClass', 22003]]);

    LXGrid.Main.School.LXEnumSchFindUserType = Slice.defineEnum([
        ['LXSchFindUserType_Student', 1], ['LXSchFindUserType_Teacher', 2]]);

    Object.defineProperty(LXGrid.Main.School, 'LXConstSchHintMaxNum', {
        value: 10
    });

    LXGrid.Main.School.LXSchFindStat = Slice.defineStruct(
        function(ClassNum, TeacherNum, StudentNum)
        {
            this.ClassNum = ClassNum !== undefined ? ClassNum : 0;
            this.TeacherNum = TeacherNum !== undefined ? TeacherNum : 0;
            this.StudentNum = StudentNum !== undefined ? StudentNum : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.ClassNum);
            __os.writeInt(this.TeacherNum);
            __os.writeInt(this.StudentNum);
        },
        function(__is)
        {
            this.ClassNum = __is.readInt();
            this.TeacherNum = __is.readInt();
            this.StudentNum = __is.readInt();
        },
        12, 
        true);

    LXGrid.Main.School.LXSchFindUser = Slice.defineStruct(
        function(user_id, user_type, login_name, real_name)
        {
            this.user_id = user_id !== undefined ? user_id : 0;
            this.user_type = user_type !== undefined ? user_type : 0;
            this.login_name = login_name !== undefined ? login_name : "";
            this.real_name = real_name !== undefined ? real_name : "";
        },
        true,
        function(__os)
        {
            __os.writeInt(this.user_id);
            __os.writeInt(this.user_type);
            __os.writeString(this.login_name);
            __os.writeString(this.real_name);
        },
        function(__is)
        {
            this.user_id = __is.readInt();
            this.user_type = __is.readInt();
            this.login_name = __is.readString();
            this.real_name = __is.readString();
        },
        10, 
        false);
    Slice.defineSequence(LXGrid.Main.School, "LXSchFindUserSeqHelper", "LXGrid.Main.School.LXSchFindUser", false);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
