// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceAdminAuth.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Admin/Auth/LXSliceAdminAuthDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Auth = __M.module("LXGrid.Main.Auth");

    Object.defineProperty(LXGrid.Main.Auth, 'IObjectAdminRegisterName', {
        value: "IObjectAdminRegister"
    });

    LXGrid.Main.Auth.IObjectAdminRegister = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectMasterSlaveBase
        ], 3,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Common::IObjectMasterSlaveBase",
            "::LXGrid::Main::Auth::IObjectAdminRegister"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Auth.IObjectAdminRegisterPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Auth.IObjectAdminRegister.ice_staticId, [
        LXGrid.Common.IObjectMasterSlaveBasePrx]);

    Slice.defineOperations(LXGrid.Main.Auth.IObjectAdminRegister, LXGrid.Main.Auth.IObjectAdminRegisterPrx,
    {
        "RegisterUser2": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [7], [LXGrid.Main.Auth.LXRegisterExtra]], [[LXGrid.Main.Auth.LXRegisterDetail2]], , , ],
        "RegisterChild2": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [3], [7], [LXGrid.Main.Auth.LXChildExtra]], [[LXGrid.Main.Auth.LXRegisterDetail2]], , , ],
        "GetUserId": [, , , 1, , [LXGrid.Common.LXReturn], [[7]], [[3]], , , ],
        "GetMultiUserId": [, , , 1, , [LXGrid.Common.LXReturn], [["Ice.StringSeqHelper"]], [["Ice.IntSeqHelper"]], , , ],
        "GetRegisterDetail2": [, , , 1, , [LXGrid.Common.LXReturn], [[3]], [[LXGrid.Main.Auth.LXRegisterDetail2]], , , ],
        "GetMultiRegisterDetail2": [, , , 1, , [LXGrid.Common.LXReturn], [["Ice.IntSeqHelper"]], [["LXGrid.Main.Auth.LXRegisterDetail2SeqHelper"]], , , ],
        "InitPassword": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], , , , ],
        "SetUserName": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], , , , ],
        "SetPhoneNo": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], , , , ],
        "SetUserLock": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [1]], , , , ],
        "DeleteUser": [, , , 1, , [LXGrid.Common.LXReturn], [[3]], , , , ],
        "DeleteUserForce": [, , , 1, , [LXGrid.Common.LXReturn], [[3]], , , , ],
        "CheckRegisterPhone2": [, , , 1, , [LXGrid.Common.LXReturn], [[7]], [[3]], , , ],
        "CheckRegisterChild2": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [7]], [[3]], , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
