// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceAction.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.OM/LXSliceGridDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.OM = __M.module("LXGrid.OM");

    LXGrid.OM.Action = __M.module("LXGrid.OM.Action");

    LXGrid.OM.Action.LXActionInfo = Slice.defineObject(
        function(opuid, appid, url, describe, args, result, navigator, ipaddress, usetime, actiontime, teamid, zoneid)
        {
            Ice.Object.call(this);
            this.opuid = opuid !== undefined ? opuid : 0;
            this.appid = appid !== undefined ? appid : 0;
            this.url = url !== undefined ? url : "";
            this.describe = describe !== undefined ? describe : "";
            this.args = args !== undefined ? args : "";
            this.result = result !== undefined ? result : "";
            this.navigator = navigator !== undefined ? navigator : "";
            this.ipaddress = ipaddress !== undefined ? ipaddress : "";
            this.usetime = usetime !== undefined ? usetime : 0;
            this.actiontime = actiontime !== undefined ? actiontime : 0;
            this.teamid = teamid;
            this.zoneid = zoneid;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::OM::Action::LXActionInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.opuid);
            __os.writeInt(this.appid);
            __os.writeString(this.url);
            __os.writeString(this.describe);
            __os.writeString(this.args);
            __os.writeString(this.result);
            __os.writeString(this.navigator);
            __os.writeString(this.ipaddress);
            __os.writeLong(this.usetime);
            __os.writeLong(this.actiontime);
            Ice.IntHelper.writeOpt(__os, 1, this.teamid);
            Ice.IntHelper.writeOpt(__os, 2, this.zoneid);
        },
        function(__is)
        {
            this.opuid = __is.readInt();
            this.appid = __is.readInt();
            this.url = __is.readString();
            this.describe = __is.readString();
            this.args = __is.readString();
            this.result = __is.readString();
            this.navigator = __is.readString();
            this.ipaddress = __is.readString();
            this.usetime = __is.readLong();
            this.actiontime = __is.readLong();
            this.teamid = Ice.IntHelper.readOpt(__is, 1);
            this.zoneid = Ice.IntHelper.readOpt(__is, 2);
        },
        false);

    LXGrid.OM.Action.LXActionInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.OM.Action.LXActionInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.OM.Action.LXActionInfo, LXGrid.OM.Action.LXActionInfoPrx);

    Object.defineProperty(LXGrid.OM.Action, 'IObjectOMActionName', {
        value: "IObjectOMAction"
    });

    LXGrid.OM.Action.IObjectOMAction = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::OM::Action::IObjectOMAction"
        ],
        -1, undefined, undefined, false);

    LXGrid.OM.Action.IObjectOMActionPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.OM.Action.IObjectOMAction.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.OM.Action.IObjectOMAction, LXGrid.OM.Action.IObjectOMActionPrx,
    {
        "Action": [, , , , , , [["LXGrid.OM.Action.LXActionInfo", true]], , , true, ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
