// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceSMS.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.SMS = __M.module("LXGrid.Main.SMS");

    Object.defineProperty(LXGrid.Main.SMS, 'IObjectSMSName', {
        value: "IObjectSMS"
    });

    LXGrid.Main.SMS.IObjectSMS = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::SMS::IObjectSMS"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.SMS.IObjectSMSPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.SMS.IObjectSMS.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.SMS.IObjectSMS, LXGrid.Main.SMS.IObjectSMSPrx,
    {
        "SendSMSCode": [, , , , , [LXGrid.Common.LXReturn], [[3], [7]], , , , ],
        "CheckSMSCode": [, , , , , [LXGrid.Common.LXReturn], [[3], [7], [7]], , , , ],
        "SendSMSMessage": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7], [7]], , , , ],
        "SendSMSMessageSeq": [, , , 1, , [LXGrid.Common.LXReturn], [[3], ["Ice.StringSeqHelper"], [7]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
