// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceMsgCenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.MsgCenter = __M.module("LXGrid.App.MsgCenter");

    LXGrid.App.MsgCenter.LXBitMsgType = Slice.defineEnum([
        ['MT_SYSTEM', 1], ['MT_COMMENT', 2], ['MT_THUMB', 4], ['MT_REWARD', 8]]);

    LXGrid.App.MsgCenter.LXNewMsgCount = Slice.defineObject(
        function(msg_type, unread_count, last_read_time)
        {
            Ice.Object.call(this);
            this.msg_type = msg_type !== undefined ? msg_type : 0;
            this.unread_count = unread_count !== undefined ? unread_count : 0;
            this.last_read_time = last_read_time !== undefined ? last_read_time : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::MsgCenter::LXNewMsgCount"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.msg_type);
            __os.writeInt(this.unread_count);
            __os.writeLong(this.last_read_time);
        },
        function(__is)
        {
            this.msg_type = __is.readInt();
            this.unread_count = __is.readInt();
            this.last_read_time = __is.readLong();
        },
        false);

    LXGrid.App.MsgCenter.LXNewMsgCountPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.MsgCenter.LXNewMsgCount.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.MsgCenter.LXNewMsgCount, LXGrid.App.MsgCenter.LXNewMsgCountPrx);
    Slice.defineSequence(LXGrid.App.MsgCenter, "LXNewMsgCountSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.MsgCenter.LXNewMsgCount");

    LXGrid.App.MsgCenter.LXMsgContent = Slice.defineObject(
        function(msg_time, text, app_id, sub_id, from_user)
        {
            Ice.Object.call(this);
            this.msg_time = msg_time !== undefined ? msg_time : 0;
            this.text = text !== undefined ? text : "";
            this.app_id = app_id !== undefined ? app_id : 0;
            this.sub_id = sub_id !== undefined ? sub_id : "";
            this.from_user = from_user !== undefined ? from_user : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::MsgCenter::LXMsgContent"
        ],
        -1,
        function(__os)
        {
            __os.writeLong(this.msg_time);
            __os.writeString(this.text);
            __os.writeInt(this.app_id);
            __os.writeString(this.sub_id);
            __os.writeInt(this.from_user);
        },
        function(__is)
        {
            this.msg_time = __is.readLong();
            this.text = __is.readString();
            this.app_id = __is.readInt();
            this.sub_id = __is.readString();
            this.from_user = __is.readInt();
        },
        false);

    LXGrid.App.MsgCenter.LXMsgContentPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.MsgCenter.LXMsgContent.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.MsgCenter.LXMsgContent, LXGrid.App.MsgCenter.LXMsgContentPrx);
    Slice.defineSequence(LXGrid.App.MsgCenter, "LXMsgContentSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.MsgCenter.LXMsgContent");

    Object.defineProperty(LXGrid.App.MsgCenter, 'IObjectName_MsgCenter', {
        value: "IObjectMsgCenter"
    });

    LXGrid.App.MsgCenter.IObjectMsgCenter = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::MsgCenter::IObjectMsgCenter",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.MsgCenter.IObjectMsgCenterPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.MsgCenter.IObjectMsgCenter.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.MsgCenter.IObjectMsgCenter, LXGrid.App.MsgCenter.IObjectMsgCenterPrx,
    {
        "GetNewMsgCount": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.MsgCenter.LXNewMsgCountSeqHelper"]], , , true],
        "GetMsgContent": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3]], [[3], ["LXGrid.App.MsgCenter.LXMsgContentSeqHelper"]], , , true],
        "AddMsg": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [4], [4]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
