// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceNewsChannel.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/News/LXSliceNewsDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.News = __M.module("LXGrid.App.News");

    Object.defineProperty(LXGrid.App.News, 'IObjectNewsChannelName', {
        value: "IObjectNewsChannel"
    });

    LXGrid.App.News.IObjectNewsChannel = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::News::IObjectNewsChannel",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.News.IObjectNewsChannelPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.News.IObjectNewsChannel.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.News.IObjectNewsChannel, LXGrid.App.News.IObjectNewsChannelPrx,
    {
        "GetChannelList": [, , , , , [LXGrid.Common.LXReturn], [[3], [LXGrid.App.News.LXEnumAttentionType.__helper], [LXGrid.App.News.LXEnumFixType.__helper]], [["LXGrid.App.News.LXChannelInfoSeqHelper"]], , , true],
        "GetChannelInfo": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.News.LXChannelBaseInfo", true]], , , true],
        "CreateChannel": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7], [7], [7], [7]], [[3]], , , ],
        "SetChannelInfo": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [LXGrid.App.News.LXEnumChannelModifyType.__helper], [7]], , , , ],
        "ChangeZoneChannelInfo": [, , , 1, , [LXGrid.Common.LXReturn], [["Ice.IntSeqHelper"], ["Ice.StringSeqHelper"], [3], [3], [3]], , , , ],
        "SetChannelAttention": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [1]], , , , ],
        "SubscribeChannel": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [1]], , , , ],
        "Login": [, , , 1, , [LXGrid.Common.LXReturn], [[3]], , , , ],
        "GetRecommendChannelList": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.News.LXRecommendChannelInfoSeqHelper"]], , , true],
        "CreateChannelByZone": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [3], [3], [3], [7], [7], [7], [7]], [[3]], , , ],
        "HasNew": [, , , 1, , [LXGrid.Common.LXReturn], [[3]], [[1]], , , ],
        "GetUserChannelProp": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [[1], [1], [1]], , , ],
        "GetUserChannelInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [["LXGrid.App.News.LXChannelInfo", true]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
