// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceNewsDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/Profile/LXSliceUserProfileDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.News = __M.module("LXGrid.App.News");

    Object.defineProperty(LXGrid.App.News, 'LXConstNewsLengthLimit', {
        value: 10000
    });

    LXGrid.App.News.LXEnumIdentityType = Slice.defineEnum([
        ['LXIdentityUnknown', 0], ['LXIdentityStudent', 1], ['LXIdentityParent', 2], ['LXIdentityTeacher', 4], ['LXIdentityOfficial', 8],
        ['LXIdentitySchoolMaster', 16], ['LXIdentitySchoolAdmin', 32], ['LXIdentitySchoolDean', 64], ['LXIdentitySchoolMasterAssistant', 128], ['LXIdentityCustomerServiceT1', 1024]]);

    LXGrid.App.News.LXEnumAttentionType = Slice.defineEnum([
        ['LXEnumAttentionIgnore', 0], ['LXEnumAttentionBeen', 1], ['LXEnumAttentionNone', 2]]);

    LXGrid.App.News.LXEnumFixType = Slice.defineEnum([
        ['LXEnumFixIgnore', 0], ['LXEnumFixBeen', 1], ['LXEnumFixNone', 2]]);

    LXGrid.App.News.LXEnumChannelModifyType = Slice.defineEnum([
        ['LXEnumChannelImage', 0], ['LXEnumChannelName', 1], ['LXEnumChannelSynopsis', 2], ['LXEnumChannelFirstImage', 3]]);

    LXGrid.App.News.LXEnumChannelZoneType = Slice.defineEnum([
        ['LXEnumChannelZoneArea', 1], ['LXEnumChannelZoneAgency', 2], ['LXEnumChannelZoneSchool', 3]]);

    LXGrid.App.News.LXEnumNewsState = Slice.defineEnum([
        ['LXNewsStateOutline', 0], ['LXNewsStateReview', 1], ['LXNewsStatePassed', 2], ['LXNewsStateUnPassed', 3]]);

    LXGrid.App.News.LXFilter = Slice.defineStruct(
        function(area, identity, segment)
        {
            this.area = area !== undefined ? area : null;
            this.identity = identity !== undefined ? identity : 0;
            this.segment = segment !== undefined ? segment : 0;
        },
        true,
        function(__os)
        {
            LXGrid.Main.Profile.LXUserPropertyAreaSeqHelper.write(__os, this.area);
            __os.writeInt(this.identity);
            __os.writeInt(this.segment);
        },
        function(__is)
        {
            this.area = LXGrid.Main.Profile.LXUserPropertyAreaSeqHelper.read(__is);
            this.identity = __is.readInt();
            this.segment = __is.readInt();
        },
        9, 
        false);

    LXGrid.App.News.LXChannelBaseInfo = Slice.defineObject(
        function(channel_id, channel_type, zone_id, province, city, county, channel_name, channel_img, channel_firstimg, channel_synopsis, creator_userid, creator_time, updater_userid, update_time, filter)
        {
            Ice.Object.call(this);
            this.channel_id = channel_id !== undefined ? channel_id : 0;
            this.channel_type = channel_type !== undefined ? channel_type : 0;
            this.zone_id = zone_id !== undefined ? zone_id : 0;
            this.province = province !== undefined ? province : 0;
            this.city = city !== undefined ? city : 0;
            this.county = county !== undefined ? county : 0;
            this.channel_name = channel_name !== undefined ? channel_name : "";
            this.channel_img = channel_img !== undefined ? channel_img : "";
            this.channel_firstimg = channel_firstimg !== undefined ? channel_firstimg : "";
            this.channel_synopsis = channel_synopsis !== undefined ? channel_synopsis : "";
            this.creator_userid = creator_userid !== undefined ? creator_userid : 0;
            this.creator_time = creator_time !== undefined ? creator_time : 0;
            this.updater_userid = updater_userid !== undefined ? updater_userid : 0;
            this.update_time = update_time !== undefined ? update_time : 0;
            this.filter = filter !== undefined ? filter : new LXGrid.App.News.LXFilter();
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::News::LXChannelBaseInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.channel_id);
            __os.writeInt(this.channel_type);
            __os.writeInt(this.zone_id);
            __os.writeInt(this.province);
            __os.writeInt(this.city);
            __os.writeInt(this.county);
            __os.writeString(this.channel_name);
            __os.writeString(this.channel_img);
            __os.writeString(this.channel_firstimg);
            __os.writeString(this.channel_synopsis);
            __os.writeInt(this.creator_userid);
            __os.writeLong(this.creator_time);
            __os.writeInt(this.updater_userid);
            __os.writeLong(this.update_time);
            LXGrid.App.News.LXFilter.write(__os, this.filter);
        },
        function(__is)
        {
            this.channel_id = __is.readInt();
            this.channel_type = __is.readInt();
            this.zone_id = __is.readInt();
            this.province = __is.readInt();
            this.city = __is.readInt();
            this.county = __is.readInt();
            this.channel_name = __is.readString();
            this.channel_img = __is.readString();
            this.channel_firstimg = __is.readString();
            this.channel_synopsis = __is.readString();
            this.creator_userid = __is.readInt();
            this.creator_time = __is.readLong();
            this.updater_userid = __is.readInt();
            this.update_time = __is.readLong();
            this.filter = LXGrid.App.News.LXFilter.read(__is, this.filter);
        },
        false);

    LXGrid.App.News.LXChannelBaseInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.News.LXChannelBaseInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.News.LXChannelBaseInfo, LXGrid.App.News.LXChannelBaseInfoPrx);
    Slice.defineSequence(LXGrid.App.News, "LXChannelBaseInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.News.LXChannelBaseInfo");

    LXGrid.App.News.LXChannelInfo = Slice.defineObject(
        function(channel_id, channel_type, zone_id, province, city, county, channel_name, channel_img, channel_firstimg, channel_synopsis, creator_userid, creator_time, updater_userid, update_time, filter, attention, fix, visiblerange, hasnew)
        {
            LXGrid.App.News.LXChannelBaseInfo.call(this, channel_id, channel_type, zone_id, province, city, county, channel_name, channel_img, channel_firstimg, channel_synopsis, creator_userid, creator_time, updater_userid, update_time, filter);
            this.attention = attention !== undefined ? attention : false;
            this.fix = fix !== undefined ? fix : false;
            this.visiblerange = visiblerange !== undefined ? visiblerange : false;
            this.hasnew = hasnew !== undefined ? hasnew : false;
        },
        LXGrid.App.News.LXChannelBaseInfo, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::App::News::LXChannelBaseInfo",
            "::LXGrid::App::News::LXChannelInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeBool(this.attention);
            __os.writeBool(this.fix);
            __os.writeBool(this.visiblerange);
            __os.writeBool(this.hasnew);
        },
        function(__is)
        {
            this.attention = __is.readBool();
            this.fix = __is.readBool();
            this.visiblerange = __is.readBool();
            this.hasnew = __is.readBool();
        },
        false);

    LXGrid.App.News.LXChannelInfoPrx = Slice.defineProxy(LXGrid.App.News.LXChannelBaseInfoPrx, LXGrid.App.News.LXChannelInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.News.LXChannelInfo, LXGrid.App.News.LXChannelInfoPrx);
    Slice.defineSequence(LXGrid.App.News, "LXChannelInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.News.LXChannelInfo");

    LXGrid.App.News.LXRecommendChannelInfo = Slice.defineObject(
        function(channel_type, zone_id, province, city, county)
        {
            Ice.Object.call(this);
            this.channel_type = channel_type !== undefined ? channel_type : 0;
            this.zone_id = zone_id !== undefined ? zone_id : 0;
            this.province = province !== undefined ? province : 0;
            this.city = city !== undefined ? city : 0;
            this.county = county !== undefined ? county : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::News::LXRecommendChannelInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.channel_type);
            __os.writeInt(this.zone_id);
            __os.writeInt(this.province);
            __os.writeInt(this.city);
            __os.writeInt(this.county);
        },
        function(__is)
        {
            this.channel_type = __is.readInt();
            this.zone_id = __is.readInt();
            this.province = __is.readInt();
            this.city = __is.readInt();
            this.county = __is.readInt();
        },
        false);

    LXGrid.App.News.LXRecommendChannelInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.News.LXRecommendChannelInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.News.LXRecommendChannelInfo, LXGrid.App.News.LXRecommendChannelInfoPrx);
    Slice.defineSequence(LXGrid.App.News, "LXRecommendChannelInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.News.LXRecommendChannelInfo");

    LXGrid.App.News.LXColumnBaseInfo = Slice.defineObject(
        function(columnid, channel_id, name, homepage, visible, contribute, creator_userid, creator_time, updater_userid, update_time, filter)
        {
            Ice.Object.call(this);
            this.columnid = columnid !== undefined ? columnid : 0;
            this.channel_id = channel_id !== undefined ? channel_id : 0;
            this.name = name !== undefined ? name : "";
            this.homepage = homepage !== undefined ? homepage : false;
            this.visible = visible !== undefined ? visible : false;
            this.contribute = contribute !== undefined ? contribute : false;
            this.creator_userid = creator_userid !== undefined ? creator_userid : 0;
            this.creator_time = creator_time !== undefined ? creator_time : 0;
            this.updater_userid = updater_userid !== undefined ? updater_userid : 0;
            this.update_time = update_time !== undefined ? update_time : 0;
            this.filter = filter !== undefined ? filter : new LXGrid.App.News.LXFilter();
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::News::LXColumnBaseInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.columnid);
            __os.writeInt(this.channel_id);
            __os.writeString(this.name);
            __os.writeBool(this.homepage);
            __os.writeBool(this.visible);
            __os.writeBool(this.contribute);
            __os.writeInt(this.creator_userid);
            __os.writeLong(this.creator_time);
            __os.writeInt(this.updater_userid);
            __os.writeLong(this.update_time);
            LXGrid.App.News.LXFilter.write(__os, this.filter);
        },
        function(__is)
        {
            this.columnid = __is.readInt();
            this.channel_id = __is.readInt();
            this.name = __is.readString();
            this.homepage = __is.readBool();
            this.visible = __is.readBool();
            this.contribute = __is.readBool();
            this.creator_userid = __is.readInt();
            this.creator_time = __is.readLong();
            this.updater_userid = __is.readInt();
            this.update_time = __is.readLong();
            this.filter = LXGrid.App.News.LXFilter.read(__is, this.filter);
        },
        false);

    LXGrid.App.News.LXColumnBaseInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.News.LXColumnBaseInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.News.LXColumnBaseInfo, LXGrid.App.News.LXColumnBaseInfoPrx);
    Slice.defineSequence(LXGrid.App.News, "LXColumnBaseInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.News.LXColumnBaseInfo");

    LXGrid.App.News.LXColumnInfo = Slice.defineObject(
        function(columnid, channel_id, name, homepage, visible, contribute, creator_userid, creator_time, updater_userid, update_time, filter, hasnew)
        {
            LXGrid.App.News.LXColumnBaseInfo.call(this, columnid, channel_id, name, homepage, visible, contribute, creator_userid, creator_time, updater_userid, update_time, filter);
            this.hasnew = hasnew !== undefined ? hasnew : false;
        },
        LXGrid.App.News.LXColumnBaseInfo, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::App::News::LXColumnBaseInfo",
            "::LXGrid::App::News::LXColumnInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeBool(this.hasnew);
        },
        function(__is)
        {
            this.hasnew = __is.readBool();
        },
        false);

    LXGrid.App.News.LXColumnInfoPrx = Slice.defineProxy(LXGrid.App.News.LXColumnBaseInfoPrx, LXGrid.App.News.LXColumnInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.News.LXColumnInfo, LXGrid.App.News.LXColumnInfoPrx);
    Slice.defineSequence(LXGrid.App.News, "LXColumnInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.News.LXColumnInfo");

    LXGrid.App.News.LXNewsBaseInfo = Slice.defineObject(
        function(channelid, columnid, newsid, newstitle, image, source, summary, vote, good, creatoruserid, createdate, updatedate, releasedate, state, auditid, audittime, failcause, delstatus, readusercnt, readcnt, collectcnt, newstype, createruname, createrzoneid, createrzonename, createrzonefullname, filter)
        {
            Ice.Object.call(this);
            this.channelid = channelid !== undefined ? channelid : 0;
            this.columnid = columnid !== undefined ? columnid : 0;
            this.newsid = newsid !== undefined ? newsid : "";
            this.newstitle = newstitle !== undefined ? newstitle : "";
            this.image = image !== undefined ? image : "";
            this.source = source !== undefined ? source : "";
            this.summary = summary !== undefined ? summary : "";
            this.vote = vote !== undefined ? vote : false;
            this.good = good !== undefined ? good : false;
            this.creatoruserid = creatoruserid !== undefined ? creatoruserid : 0;
            this.createdate = createdate !== undefined ? createdate : 0;
            this.updatedate = updatedate !== undefined ? updatedate : 0;
            this.releasedate = releasedate !== undefined ? releasedate : 0;
            this.state = state !== undefined ? state : LXGrid.App.News.LXEnumNewsState.LXNewsStateOutline;
            this.auditid = auditid !== undefined ? auditid : 0;
            this.audittime = audittime !== undefined ? audittime : 0;
            this.failcause = failcause !== undefined ? failcause : "";
            this.delstatus = delstatus !== undefined ? delstatus : false;
            this.readusercnt = readusercnt !== undefined ? readusercnt : 0;
            this.readcnt = readcnt !== undefined ? readcnt : 0;
            this.collectcnt = collectcnt !== undefined ? collectcnt : 0;
            this.newstype = newstype !== undefined ? newstype : 0;
            this.createruname = createruname !== undefined ? createruname : "";
            this.createrzoneid = createrzoneid !== undefined ? createrzoneid : 0;
            this.createrzonename = createrzonename !== undefined ? createrzonename : "";
            this.createrzonefullname = createrzonefullname !== undefined ? createrzonefullname : "";
            this.filter = filter !== undefined ? filter : new LXGrid.App.News.LXFilter();
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::News::LXNewsBaseInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.channelid);
            __os.writeInt(this.columnid);
            __os.writeString(this.newsid);
            __os.writeString(this.newstitle);
            __os.writeString(this.image);
            __os.writeString(this.source);
            __os.writeString(this.summary);
            __os.writeBool(this.vote);
            __os.writeBool(this.good);
            __os.writeInt(this.creatoruserid);
            __os.writeLong(this.createdate);
            __os.writeLong(this.updatedate);
            __os.writeLong(this.releasedate);
            LXGrid.App.News.LXEnumNewsState.__write(__os, this.state);
            __os.writeInt(this.auditid);
            __os.writeLong(this.audittime);
            __os.writeString(this.failcause);
            __os.writeBool(this.delstatus);
            __os.writeInt(this.readusercnt);
            __os.writeInt(this.readcnt);
            __os.writeInt(this.collectcnt);
            __os.writeInt(this.newstype);
            __os.writeString(this.createruname);
            __os.writeInt(this.createrzoneid);
            __os.writeString(this.createrzonename);
            __os.writeString(this.createrzonefullname);
            LXGrid.App.News.LXFilter.write(__os, this.filter);
        },
        function(__is)
        {
            this.channelid = __is.readInt();
            this.columnid = __is.readInt();
            this.newsid = __is.readString();
            this.newstitle = __is.readString();
            this.image = __is.readString();
            this.source = __is.readString();
            this.summary = __is.readString();
            this.vote = __is.readBool();
            this.good = __is.readBool();
            this.creatoruserid = __is.readInt();
            this.createdate = __is.readLong();
            this.updatedate = __is.readLong();
            this.releasedate = __is.readLong();
            this.state = LXGrid.App.News.LXEnumNewsState.__read(__is);
            this.auditid = __is.readInt();
            this.audittime = __is.readLong();
            this.failcause = __is.readString();
            this.delstatus = __is.readBool();
            this.readusercnt = __is.readInt();
            this.readcnt = __is.readInt();
            this.collectcnt = __is.readInt();
            this.newstype = __is.readInt();
            this.createruname = __is.readString();
            this.createrzoneid = __is.readInt();
            this.createrzonename = __is.readString();
            this.createrzonefullname = __is.readString();
            this.filter = LXGrid.App.News.LXFilter.read(__is, this.filter);
        },
        false);

    LXGrid.App.News.LXNewsBaseInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.News.LXNewsBaseInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.News.LXNewsBaseInfo, LXGrid.App.News.LXNewsBaseInfoPrx);
    Slice.defineSequence(LXGrid.App.News, "LXNewsBaseInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.News.LXNewsBaseInfo");

    LXGrid.App.News.LXNewsInfo = Slice.defineObject(
        function(channelid, columnid, newsid, newstitle, image, source, summary, vote, good, creatoruserid, createdate, updatedate, releasedate, state, auditid, audittime, failcause, delstatus, readusercnt, readcnt, collectcnt, newstype, createruname, createrzoneid, createrzonename, createrzonefullname, filter, isread, iscollect)
        {
            LXGrid.App.News.LXNewsBaseInfo.call(this, channelid, columnid, newsid, newstitle, image, source, summary, vote, good, creatoruserid, createdate, updatedate, releasedate, state, auditid, audittime, failcause, delstatus, readusercnt, readcnt, collectcnt, newstype, createruname, createrzoneid, createrzonename, createrzonefullname, filter);
            this.isread = isread !== undefined ? isread : false;
            this.iscollect = iscollect !== undefined ? iscollect : false;
        },
        LXGrid.App.News.LXNewsBaseInfo, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::App::News::LXNewsBaseInfo",
            "::LXGrid::App::News::LXNewsInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeBool(this.isread);
            __os.writeBool(this.iscollect);
        },
        function(__is)
        {
            this.isread = __is.readBool();
            this.iscollect = __is.readBool();
        },
        false);

    LXGrid.App.News.LXNewsInfoPrx = Slice.defineProxy(LXGrid.App.News.LXNewsBaseInfoPrx, LXGrid.App.News.LXNewsInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.News.LXNewsInfo, LXGrid.App.News.LXNewsInfoPrx);
    Slice.defineSequence(LXGrid.App.News, "LXNewsInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.News.LXNewsInfo");

    LXGrid.App.News.LXNewsAreaStat = Slice.defineObject(
        function(daynum, monthnum, totalnum)
        {
            Ice.Object.call(this);
            this.daynum = daynum !== undefined ? daynum : 0;
            this.monthnum = monthnum !== undefined ? monthnum : 0;
            this.totalnum = totalnum !== undefined ? totalnum : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::News::LXNewsAreaStat"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.daynum);
            __os.writeInt(this.monthnum);
            __os.writeInt(this.totalnum);
        },
        function(__is)
        {
            this.daynum = __is.readInt();
            this.monthnum = __is.readInt();
            this.totalnum = __is.readInt();
        },
        false);

    LXGrid.App.News.LXNewsAreaStatPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.News.LXNewsAreaStat.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.News.LXNewsAreaStat, LXGrid.App.News.LXNewsAreaStatPrx);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
