// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceSearchDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Search = __M.module("LXGrid.Main.Search");

    LXGrid.Main.Search.LXKeyword = Slice.defineStruct(
        function(word, weight)
        {
            this.word = word !== undefined ? word : "";
            this.weight = weight !== undefined ? weight : 0.0;
        },
        false,
        function(__os)
        {
            __os.writeString(this.word);
            __os.writeDouble(this.weight);
        },
        function(__is)
        {
            this.word = __is.readString();
            this.weight = __is.readDouble();
        },
        9, 
        false);
    Slice.defineSequence(LXGrid.Main.Search, "LXKeywordSeqHelper", "LXGrid.Main.Search.LXKeyword", false);

    LXGrid.Main.Search.LXQueryResult = Slice.defineStruct(
        function(doc_id, weight)
        {
            this.doc_id = doc_id !== undefined ? doc_id : 0;
            this.weight = weight !== undefined ? weight : 0.0;
        },
        false,
        function(__os)
        {
            __os.writeInt(this.doc_id);
            __os.writeDouble(this.weight);
        },
        function(__is)
        {
            this.doc_id = __is.readInt();
            this.weight = __is.readDouble();
        },
        12, 
        true);
    Slice.defineSequence(LXGrid.Main.Search, "LXQueryResultSeqHelper", "LXGrid.Main.Search.LXQueryResult", true);

    LXGrid.Main.Search.LXSearchResult = Slice.defineStruct(
        function(doc_key, doc_source, keywords)
        {
            this.doc_key = doc_key !== undefined ? doc_key : "";
            this.doc_source = doc_source !== undefined ? doc_source : 0;
            this.keywords = keywords !== undefined ? keywords : null;
        },
        false,
        function(__os)
        {
            __os.writeString(this.doc_key);
            __os.writeInt(this.doc_source);
            LXGrid.Main.Search.LXKeywordSeqHelper.write(__os, this.keywords);
        },
        function(__is)
        {
            this.doc_key = __is.readString();
            this.doc_source = __is.readInt();
            this.keywords = LXGrid.Main.Search.LXKeywordSeqHelper.read(__is);
        },
        6, 
        false);
    Slice.defineSequence(LXGrid.Main.Search, "LXSearchResultSeqHelper", "LXGrid.Main.Search.LXSearchResult", false);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
