// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceKeyword.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/Search/LXSliceSearchDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Search = __M.module("LXGrid.Main.Search");

    Object.defineProperty(LXGrid.Main.Search, 'IObjectName_Keyword', {
        value: "IObjectKeyword"
    });

    LXGrid.Main.Search.IObjectKeyword = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::Search::IObjectKeyword"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Search.IObjectKeywordPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Search.IObjectKeyword.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.Search.IObjectKeyword, LXGrid.Main.Search.IObjectKeywordPrx,
    {
        "GetKeywords": [, , , , , [LXGrid.Common.LXReturn], [[3], [7]], [["LXGrid.Main.Search.LXKeywordSeqHelper"]], , , ],
        "AddDocument": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [3], ["LXGrid.Main.Search.LXKeywordSeqHelper"]], , , , ],
        "AddDocumentEx": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [3], [7]], , , , ],
        "DeleteDocument": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [3]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
