// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceOpen.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/Open/LXSliceOpenDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Open = __M.module("LXGrid.Main.Open");

    Object.defineProperty(LXGrid.Main.Open, 'IObjectOpenAuthName', {
        value: "IObjectOpenAuth"
    });

    LXGrid.Main.Open.IObjectOpenAuth = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectMasterSlaveBase
        ], 3,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Common::IObjectMasterSlaveBase",
            "::LXGrid::Main::Open::IObjectOpenAuth"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Open.IObjectOpenAuthPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Open.IObjectOpenAuth.ice_staticId, [
        LXGrid.Common.IObjectMasterSlaveBasePrx]);

    Slice.defineOperations(LXGrid.Main.Open.IObjectOpenAuth, LXGrid.Main.Open.IObjectOpenAuthPrx,
    {
        "OpenAuthorize": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7], [3], [LXGrid.Main.Open.LXOpenAuthExtra]], [[LXGrid.Main.Open.LXTempCode]], , , ],
        "GetOpenToken": [, , , 1, , [LXGrid.Common.LXReturn], [[LXGrid.Main.Open.LXOpenApp], [7]], [[LXGrid.Main.Open.LXOpenToken]], , , ],
        "GetUserInfo": [, , , 1, , [LXGrid.Common.LXReturn], [[LXGrid.Main.Open.LXOpenApp], [7]], [[LXGrid.Main.Open.LXOpenUserInfo]], , , ],
        "GetUserId": [, , , 1, , [LXGrid.Common.LXReturn], [[7]], [[3]], , , ],
        "GetOpenId": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3]], [[7]], , , ]
    });

    Object.defineProperty(LXGrid.Main.Open, 'IObjectTempCodeName', {
        value: "IObjectTempCode"
    });

    LXGrid.Main.Open.IObjectTempCode = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectMasterSlaveBase
        ], 3,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Common::IObjectMasterSlaveBase",
            "::LXGrid::Main::Open::IObjectTempCode"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Open.IObjectTempCodePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Open.IObjectTempCode.ice_staticId, [
        LXGrid.Common.IObjectMasterSlaveBasePrx]);

    Slice.defineOperations(LXGrid.Main.Open.IObjectTempCode, LXGrid.Main.Open.IObjectTempCodePrx,
    {
        "SetTempCode": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [4], [LXGrid.Main.Open.LXTempCodeData]], , , , ],
        "GetTempCode": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [3]], [[LXGrid.Main.Open.LXTempCodeData]], , , ],
        "ChkTempCode": [, , , 1, , [LXGrid.Common.LXReturn], [[7]], [[LXGrid.Main.Open.LXTempCodeData]], , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
