// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceDealerAuth.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.OM/Dealer/LXSliceDealerDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Dealer = __M.module("LXGrid.Dealer");

    LXGrid.Dealer.Auth = __M.module("LXGrid.Dealer.Auth");

    Object.defineProperty(LXGrid.Dealer.Auth, 'IObjectDealerAuthName', {
        value: "IObjectDealerAuth"
    });

    LXGrid.Dealer.Auth.IObjectDealerAuth = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Dealer::Auth::IObjectDealerAuth"
        ],
        -1, undefined, undefined, false);

    LXGrid.Dealer.Auth.IObjectDealerAuthPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Dealer.Auth.IObjectDealerAuth.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Dealer.Auth.IObjectDealerAuth, LXGrid.Dealer.Auth.IObjectDealerAuthPrx,
    {
        "ActiveAccount": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [7], [7], [7], [LXGrid.Dealer.SJEnumDeviceType.__helper], [7], [7]], [[7], [3]], , , ],
        "Login": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [7], [7], [LXGrid.Dealer.SJEnumDeviceType.__helper], [7], [7], [7]], [[7], [3]], , , ],
        "Logout": [, , , 1, , [LXGrid.Common.LXReturn], [[7]], , , , ],
        "ChangePassword": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [7], [7], [7]], , , , ],
        "ResetPassword": [, , , 1, , [LXGrid.Common.LXReturn], [[3]], , , , ],
        "ChangePhoneNumber": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [7], [7], [7], [7], [7]], , , , ],
        "SendSMSCodeByToken": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [7]], [[7]], , , ],
        "SendSMSCodeByLoginname": [, , , 1, , [LXGrid.Common.LXReturn], [[7]], [[7]], , , ],
        "GetSecurityToken": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], [[7]], , , ],
        "CheckSecurityToken": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], , , , ],
        "GetOnlineStatus": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.Dealer.SJOnlineDeviceSeqHelper"]], , , true],
        "CheckUserToken": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.Dealer.SJOnlineDevice", true], [3]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
