// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceNewSignDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.NewSign = __M.module("LXGrid.App.NewSign");

    LXGrid.App.NewSign.ProtocolMsgSet = Slice.defineObject(
        function(stype, stype_name, sversion, strcontent)
        {
            Ice.Object.call(this);
            this.stype = stype !== undefined ? stype : 0;
            this.stype_name = stype_name !== undefined ? stype_name : "";
            this.sversion = sversion !== undefined ? sversion : 0;
            this.strcontent = strcontent !== undefined ? strcontent : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::ProtocolMsgSet"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.stype);
            __os.writeString(this.stype_name);
            __os.writeInt(this.sversion);
            __os.writeString(this.strcontent);
        },
        function(__is)
        {
            this.stype = __is.readInt();
            this.stype_name = __is.readString();
            this.sversion = __is.readInt();
            this.strcontent = __is.readString();
        },
        false);

    LXGrid.App.NewSign.ProtocolMsgSetPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.ProtocolMsgSet.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.ProtocolMsgSet, LXGrid.App.NewSign.ProtocolMsgSetPrx);
    Slice.defineSequence(LXGrid.App.NewSign, "ProtocolMsgSetSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.NewSign.ProtocolMsgSet");

    LXGrid.App.NewSign.SignTask = Slice.defineObject(
        function(task_id, task_name, task_day, reward_id, reward_type, reward_name, if_continuous, task_range, reward_number, task_start_ymd, task_end_ymd, if_valid, month_copy, all_month_task)
        {
            Ice.Object.call(this);
            this.task_id = task_id !== undefined ? task_id : "";
            this.task_name = task_name !== undefined ? task_name : "";
            this.task_day = task_day !== undefined ? task_day : 0;
            this.reward_id = reward_id !== undefined ? reward_id : "";
            this.reward_type = reward_type !== undefined ? reward_type : 0;
            this.reward_name = reward_name !== undefined ? reward_name : "";
            this.if_continuous = if_continuous !== undefined ? if_continuous : 0;
            this.task_range = task_range !== undefined ? task_range : 0;
            this.reward_number = reward_number !== undefined ? reward_number : 0;
            this.task_start_ymd = task_start_ymd !== undefined ? task_start_ymd : 0;
            this.task_end_ymd = task_end_ymd !== undefined ? task_end_ymd : 0;
            this.if_valid = if_valid !== undefined ? if_valid : 0;
            this.month_copy = month_copy !== undefined ? month_copy : 0;
            this.all_month_task = all_month_task !== undefined ? all_month_task : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::SignTask"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.task_id);
            __os.writeString(this.task_name);
            __os.writeInt(this.task_day);
            __os.writeString(this.reward_id);
            __os.writeInt(this.reward_type);
            __os.writeString(this.reward_name);
            __os.writeInt(this.if_continuous);
            __os.writeInt(this.task_range);
            __os.writeInt(this.reward_number);
            __os.writeLong(this.task_start_ymd);
            __os.writeLong(this.task_end_ymd);
            __os.writeInt(this.if_valid);
            __os.writeInt(this.month_copy);
            __os.writeInt(this.all_month_task);
        },
        function(__is)
        {
            this.task_id = __is.readString();
            this.task_name = __is.readString();
            this.task_day = __is.readInt();
            this.reward_id = __is.readString();
            this.reward_type = __is.readInt();
            this.reward_name = __is.readString();
            this.if_continuous = __is.readInt();
            this.task_range = __is.readInt();
            this.reward_number = __is.readInt();
            this.task_start_ymd = __is.readLong();
            this.task_end_ymd = __is.readLong();
            this.if_valid = __is.readInt();
            this.month_copy = __is.readInt();
            this.all_month_task = __is.readInt();
        },
        false);

    LXGrid.App.NewSign.SignTaskPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.SignTask.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.SignTask, LXGrid.App.NewSign.SignTaskPrx);
    Slice.defineSequence(LXGrid.App.NewSign, "SignTaskSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.NewSign.SignTask");

    LXGrid.App.NewSign.RewardRegister = Slice.defineObject(
        function(reward_id, reward_type, reward_name, if_valid)
        {
            Ice.Object.call(this);
            this.reward_id = reward_id !== undefined ? reward_id : "";
            this.reward_type = reward_type !== undefined ? reward_type : 0;
            this.reward_name = reward_name !== undefined ? reward_name : "";
            this.if_valid = if_valid !== undefined ? if_valid : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::RewardRegister"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.reward_id);
            __os.writeInt(this.reward_type);
            __os.writeString(this.reward_name);
            __os.writeInt(this.if_valid);
        },
        function(__is)
        {
            this.reward_id = __is.readString();
            this.reward_type = __is.readInt();
            this.reward_name = __is.readString();
            this.if_valid = __is.readInt();
        },
        false);

    LXGrid.App.NewSign.RewardRegisterPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.RewardRegister.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.RewardRegister, LXGrid.App.NewSign.RewardRegisterPrx);
    Slice.defineSequence(LXGrid.App.NewSign, "RewardRegisterSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.NewSign.RewardRegister");

    LXGrid.App.NewSign.SignGoldSet = Slice.defineObject(
        function(sign_id, sign_type, sign_type_name, gold_cnt)
        {
            Ice.Object.call(this);
            this.sign_id = sign_id !== undefined ? sign_id : 0;
            this.sign_type = sign_type !== undefined ? sign_type : 0;
            this.sign_type_name = sign_type_name !== undefined ? sign_type_name : "";
            this.gold_cnt = gold_cnt !== undefined ? gold_cnt : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::SignGoldSet"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.sign_id);
            __os.writeInt(this.sign_type);
            __os.writeString(this.sign_type_name);
            __os.writeInt(this.gold_cnt);
        },
        function(__is)
        {
            this.sign_id = __is.readInt();
            this.sign_type = __is.readInt();
            this.sign_type_name = __is.readString();
            this.gold_cnt = __is.readInt();
        },
        false);

    LXGrid.App.NewSign.SignGoldSetPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.SignGoldSet.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.SignGoldSet, LXGrid.App.NewSign.SignGoldSetPrx);
    Slice.defineSequence(LXGrid.App.NewSign, "SignGoldSetSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.NewSign.SignGoldSet");

    LXGrid.App.NewSign.UserSignInfo = Slice.defineObject(
        function(user_id, sign_cnt, sign)
        {
            Ice.Object.call(this);
            this.user_id = user_id !== undefined ? user_id : 0;
            this.sign_cnt = sign_cnt !== undefined ? sign_cnt : 0;
            this.sign = sign !== undefined ? sign : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::UserSignInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.user_id);
            __os.writeInt(this.sign_cnt);
            __os.writeInt(this.sign);
        },
        function(__is)
        {
            this.user_id = __is.readInt();
            this.sign_cnt = __is.readInt();
            this.sign = __is.readInt();
        },
        false);

    LXGrid.App.NewSign.UserSignInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.UserSignInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.UserSignInfo, LXGrid.App.NewSign.UserSignInfoPrx);

    LXGrid.App.NewSign.StuSignInfo = Slice.defineObject(
        function(stu_user_id, sign_cnt, month_sign_cnt, sign_continuous_days, redstar_cnt, sign, supplement_days)
        {
            Ice.Object.call(this);
            this.stu_user_id = stu_user_id !== undefined ? stu_user_id : 0;
            this.sign_cnt = sign_cnt !== undefined ? sign_cnt : 0;
            this.month_sign_cnt = month_sign_cnt !== undefined ? month_sign_cnt : 0;
            this.sign_continuous_days = sign_continuous_days !== undefined ? sign_continuous_days : 0;
            this.redstar_cnt = redstar_cnt !== undefined ? redstar_cnt : 0;
            this.sign = sign !== undefined ? sign : 0;
            this.supplement_days = supplement_days !== undefined ? supplement_days : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::StuSignInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.stu_user_id);
            __os.writeInt(this.sign_cnt);
            __os.writeInt(this.month_sign_cnt);
            __os.writeInt(this.sign_continuous_days);
            __os.writeInt(this.redstar_cnt);
            __os.writeInt(this.sign);
            __os.writeInt(this.supplement_days);
        },
        function(__is)
        {
            this.stu_user_id = __is.readInt();
            this.sign_cnt = __is.readInt();
            this.month_sign_cnt = __is.readInt();
            this.sign_continuous_days = __is.readInt();
            this.redstar_cnt = __is.readInt();
            this.sign = __is.readInt();
            this.supplement_days = __is.readInt();
        },
        false);

    LXGrid.App.NewSign.StuSignInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.StuSignInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.StuSignInfo, LXGrid.App.NewSign.StuSignInfoPrx);

    LXGrid.App.NewSign.StuSignDetailedInf = Slice.defineObject(
        function(stu_user_id, user_id, sign_ymd, sign_type, sign_datetime)
        {
            Ice.Object.call(this);
            this.stu_user_id = stu_user_id !== undefined ? stu_user_id : 0;
            this.user_id = user_id !== undefined ? user_id : 0;
            this.sign_ymd = sign_ymd !== undefined ? sign_ymd : 0;
            this.sign_type = sign_type !== undefined ? sign_type : 0;
            this.sign_datetime = sign_datetime !== undefined ? sign_datetime : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::StuSignDetailedInf"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.stu_user_id);
            __os.writeInt(this.user_id);
            __os.writeLong(this.sign_ymd);
            __os.writeInt(this.sign_type);
            __os.writeLong(this.sign_datetime);
        },
        function(__is)
        {
            this.stu_user_id = __is.readInt();
            this.user_id = __is.readInt();
            this.sign_ymd = __is.readLong();
            this.sign_type = __is.readInt();
            this.sign_datetime = __is.readLong();
        },
        false);

    LXGrid.App.NewSign.StuSignDetailedInfPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.StuSignDetailedInf.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.StuSignDetailedInf, LXGrid.App.NewSign.StuSignDetailedInfPrx);
    Slice.defineSequence(LXGrid.App.NewSign, "StuSignDetailedInfSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.NewSign.StuSignDetailedInf");

    LXGrid.App.NewSign.StuSignTaskInf = Slice.defineObject(
        function(task_id, task_name, reward_name, reward_number, task_day, if_continuous, qualified_day, task_start_ymd, task_end_ymd, task_receive)
        {
            Ice.Object.call(this);
            this.task_id = task_id !== undefined ? task_id : "";
            this.task_name = task_name !== undefined ? task_name : "";
            this.reward_name = reward_name !== undefined ? reward_name : "";
            this.reward_number = reward_number !== undefined ? reward_number : 0;
            this.task_day = task_day !== undefined ? task_day : 0;
            this.if_continuous = if_continuous !== undefined ? if_continuous : 0;
            this.qualified_day = qualified_day !== undefined ? qualified_day : 0;
            this.task_start_ymd = task_start_ymd !== undefined ? task_start_ymd : 0;
            this.task_end_ymd = task_end_ymd !== undefined ? task_end_ymd : 0;
            this.task_receive = task_receive !== undefined ? task_receive : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::StuSignTaskInf"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.task_id);
            __os.writeString(this.task_name);
            __os.writeString(this.reward_name);
            __os.writeInt(this.reward_number);
            __os.writeInt(this.task_day);
            __os.writeInt(this.if_continuous);
            __os.writeInt(this.qualified_day);
            __os.writeLong(this.task_start_ymd);
            __os.writeLong(this.task_end_ymd);
            __os.writeInt(this.task_receive);
        },
        function(__is)
        {
            this.task_id = __is.readString();
            this.task_name = __is.readString();
            this.reward_name = __is.readString();
            this.reward_number = __is.readInt();
            this.task_day = __is.readInt();
            this.if_continuous = __is.readInt();
            this.qualified_day = __is.readInt();
            this.task_start_ymd = __is.readLong();
            this.task_end_ymd = __is.readLong();
            this.task_receive = __is.readInt();
        },
        false);

    LXGrid.App.NewSign.StuSignTaskInfPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.StuSignTaskInf.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.StuSignTaskInf, LXGrid.App.NewSign.StuSignTaskInfPrx);
    Slice.defineSequence(LXGrid.App.NewSign, "StuSignTaskInfSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.NewSign.StuSignTaskInf");

    LXGrid.App.NewSign.StuSignRewardDetailedInf = Slice.defineObject(
        function(stu_user_id, reason, reward_ymd, reward_number, reward_type, reward_name, remark, subkey)
        {
            Ice.Object.call(this);
            this.stu_user_id = stu_user_id !== undefined ? stu_user_id : 0;
            this.reason = reason !== undefined ? reason : "";
            this.reward_ymd = reward_ymd !== undefined ? reward_ymd : 0;
            this.reward_number = reward_number !== undefined ? reward_number : 0;
            this.reward_type = reward_type !== undefined ? reward_type : 0;
            this.reward_name = reward_name !== undefined ? reward_name : "";
            this.remark = remark !== undefined ? remark : "";
            this.subkey = subkey !== undefined ? subkey : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::StuSignRewardDetailedInf"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.stu_user_id);
            __os.writeString(this.reason);
            __os.writeLong(this.reward_ymd);
            __os.writeInt(this.reward_number);
            __os.writeInt(this.reward_type);
            __os.writeString(this.reward_name);
            __os.writeString(this.remark);
            __os.writeString(this.subkey);
        },
        function(__is)
        {
            this.stu_user_id = __is.readInt();
            this.reason = __is.readString();
            this.reward_ymd = __is.readLong();
            this.reward_number = __is.readInt();
            this.reward_type = __is.readInt();
            this.reward_name = __is.readString();
            this.remark = __is.readString();
            this.subkey = __is.readString();
        },
        false);

    LXGrid.App.NewSign.StuSignRewardDetailedInfPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.StuSignRewardDetailedInf.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.StuSignRewardDetailedInf, LXGrid.App.NewSign.StuSignRewardDetailedInfPrx);
    Slice.defineSequence(LXGrid.App.NewSign, "StuSignRewardDetailedInfSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.NewSign.StuSignRewardDetailedInf");

    LXGrid.App.NewSign.ZoneSignInfo = Slice.defineObject(
        function(stu_user_id, sign_cnt)
        {
            Ice.Object.call(this);
            this.stu_user_id = stu_user_id !== undefined ? stu_user_id : 0;
            this.sign_cnt = sign_cnt !== undefined ? sign_cnt : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::ZoneSignInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.stu_user_id);
            __os.writeInt(this.sign_cnt);
        },
        function(__is)
        {
            this.stu_user_id = __is.readInt();
            this.sign_cnt = __is.readInt();
        },
        false);

    LXGrid.App.NewSign.ZoneSignInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.ZoneSignInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.ZoneSignInfo, LXGrid.App.NewSign.ZoneSignInfoPrx);
    Slice.defineSequence(LXGrid.App.NewSign, "ZoneSignInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.NewSign.ZoneSignInfo");

    LXGrid.App.NewSign.ZoneSignPercent = Slice.defineObject(
        function(stu_cnt, sign_cnt, stu_sign_cnt, zone_sign_percent)
        {
            Ice.Object.call(this);
            this.stu_cnt = stu_cnt !== undefined ? stu_cnt : 0;
            this.sign_cnt = sign_cnt !== undefined ? sign_cnt : 0;
            this.stu_sign_cnt = stu_sign_cnt !== undefined ? stu_sign_cnt : 0;
            this.zone_sign_percent = zone_sign_percent !== undefined ? zone_sign_percent : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::ZoneSignPercent"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.stu_cnt);
            __os.writeInt(this.sign_cnt);
            __os.writeInt(this.stu_sign_cnt);
            __os.writeInt(this.zone_sign_percent);
        },
        function(__is)
        {
            this.stu_cnt = __is.readInt();
            this.sign_cnt = __is.readInt();
            this.stu_sign_cnt = __is.readInt();
            this.zone_sign_percent = __is.readInt();
        },
        false);

    LXGrid.App.NewSign.ZoneSignPercentPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.ZoneSignPercent.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.ZoneSignPercent, LXGrid.App.NewSign.ZoneSignPercentPrx);

    LXGrid.App.NewSign.ZoneSignRewardInfo = Slice.defineObject(
        function(stu_user_id, reward_number)
        {
            Ice.Object.call(this);
            this.stu_user_id = stu_user_id !== undefined ? stu_user_id : 0;
            this.reward_number = reward_number !== undefined ? reward_number : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::ZoneSignRewardInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.stu_user_id);
            __os.writeInt(this.reward_number);
        },
        function(__is)
        {
            this.stu_user_id = __is.readInt();
            this.reward_number = __is.readInt();
        },
        false);

    LXGrid.App.NewSign.ZoneSignRewardInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.ZoneSignRewardInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.NewSign.ZoneSignRewardInfo, LXGrid.App.NewSign.ZoneSignRewardInfoPrx);
    Slice.defineSequence(LXGrid.App.NewSign, "ZoneSignRewardInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.NewSign.ZoneSignRewardInfo");
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
