// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceNewSign.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/NewSign/LXSliceNewSignDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.NewSign = __M.module("LXGrid.App.NewSign");

    Object.defineProperty(LXGrid.App.NewSign, 'IObjectName_NewSign_Protocol', {
        value: "IObjectNewSignProtocol"
    });

    LXGrid.App.NewSign.IObjectNewSignProtocol = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::IObjectNewSignProtocol",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.NewSign.IObjectNewSignProtocolPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.IObjectNewSignProtocol.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.NewSign.IObjectNewSignProtocol, LXGrid.App.NewSign.IObjectNewSignProtocolPrx,
    {
        "GetProtocolInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [["LXGrid.App.NewSign.ProtocolMsgSet", true]], , , true],
        "GetSignGoldSetInf": [, , , , , [LXGrid.Common.LXReturn], [[3]], [[3]], , , ],
        "GetSignRewardName": [, , , , , [LXGrid.Common.LXReturn], [[3]], [[7]], , , ]
    });

    Object.defineProperty(LXGrid.App.NewSign, 'IObjectName_NewSign_User', {
        value: "IObjectNewSignUser"
    });

    LXGrid.App.NewSign.IObjectNewSignUser = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::IObjectNewSignUser",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.NewSign.IObjectNewSignUserPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.IObjectNewSignUser.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.NewSign.IObjectNewSignUser, LXGrid.App.NewSign.IObjectNewSignUserPrx,
    {
        "GetUserSignInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [4]], [["LXGrid.App.NewSign.UserSignInfo", true]], , , true],
        "SignForStuId": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [4], [3]], [[3]], , , ]
    });

    Object.defineProperty(LXGrid.App.NewSign, 'IObjectName_NewSign_Student', {
        value: "IObjectNewSignStudent"
    });

    LXGrid.App.NewSign.IObjectNewSignStudent = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::IObjectNewSignStudent",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.NewSign.IObjectNewSignStudentPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.IObjectNewSignStudent.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.NewSign.IObjectNewSignStudent, LXGrid.App.NewSign.IObjectNewSignStudentPrx,
    {
        "CanSupplement": [, , , , , [LXGrid.Common.LXReturn], [[3], [4]], , , , ],
        "GetStuSignInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [4]], [["LXGrid.App.NewSign.StuSignInfo", true]], , , true],
        "GetStuSignDetailedInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [4], [4]], [["LXGrid.App.NewSign.StuSignDetailedInfSeqHelper"]], , , true],
        "GetSignSupplementDays": [, , , , , [LXGrid.Common.LXReturn], [[3], [4]], [["Ice.LongSeqHelper"]], , , ],
        "GetStuSignTaskInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [4]], [["LXGrid.App.NewSign.StuSignTaskInfSeqHelper"]], , , true],
        "GetStuSignTaskReward": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [[3]], , , ],
        "GetStuSignTaskRewardInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3]], [[3], [3], ["LXGrid.App.NewSign.StuSignRewardDetailedInfSeqHelper"]], , , true],
        "ReceiveSignTaskReward": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7], [7], [7], [7]], , , , ]
    });

    Object.defineProperty(LXGrid.App.NewSign, 'IObjectName_NewSign_Zone', {
        value: "IObjectNewSignZone"
    });

    LXGrid.App.NewSign.IObjectNewSignZone = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::NewSign::IObjectNewSignZone",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.NewSign.IObjectNewSignZonePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.NewSign.IObjectNewSignZone.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.NewSign.IObjectNewSignZone, LXGrid.App.NewSign.IObjectNewSignZonePrx,
    {
        "GetZoneSignInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [4], [4]], [["LXGrid.App.NewSign.ZoneSignInfoSeqHelper"]], , , true],
        "GetZoneSignRewardInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [["LXGrid.App.NewSign.ZoneSignRewardInfoSeqHelper"]], , , true],
        "GetZoneSignDetailedInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [4], [4], [3], [3]], [[3], ["LXGrid.App.NewSign.StuSignDetailedInfSeqHelper"]], , , true],
        "GetZoneSignPercentInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [4], [4]], [["LXGrid.App.NewSign.ZoneSignPercent", true], ["LXGrid.App.NewSign.ZoneSignInfoSeqHelper"]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
