// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceKVCache.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/KVCache/LXSliceKVCacheDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.KVCache = __M.module("LXGrid.Main.KVCache");

    Object.defineProperty(LXGrid.Main.KVCache, 'IObjectKVCacheName', {
        value: "IObjectKVCache"
    });

    LXGrid.Main.KVCache.IObjectKVCache = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::KVCache::IObjectKVCache"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.KVCache.IObjectKVCachePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.KVCache.IObjectKVCache.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.KVCache.IObjectKVCache, LXGrid.Main.KVCache.IObjectKVCachePrx,
    {
        "Set": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [7], [3]], , , , ],
        "Get": [, , , 1, , [LXGrid.Common.LXReturn], [[7]], [[7]], , , ],
        "Remove": [, , , 1, , [LXGrid.Common.LXReturn], [[7]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
