// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceGridAppDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    Object.defineProperty(LXGrid.App, 'ThisGridName', {
        value: "LXGridApp"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameNews', {
        value: "LXNews"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameInformation', {
        value: "LXInformation"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameCollect', {
        value: "LXCollect"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameQuestionnaire', {
        value: "LXQuestionnaire"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameNewSign', {
        value: "LXNewSign"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameLottery', {
        value: "LXLottery"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNamePoemsMatch', {
        value: "LXPoemsMatch"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNamePoemsBattle', {
        value: "LXPoemsBattle"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameMall', {
        value: "LXMall"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameGlobal', {
        value: "LXGlobal"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameVote', {
        value: "LXVoteRep"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameMsgCenter', {
        value: "LXMsgCenter"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameAppAdmin', {
        value: "LXAppAdmin"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameNotice', {
        value: "LXNotice"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameCoverImage', {
        value: "LXCoverImage"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameWeChatToken', {
        value: "LXWeChatToken"
    });

    Object.defineProperty(LXGrid.App, 'ClusterNameWeChatGateway', {
        value: "LXWeChatGateway"
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
