// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceStatistics.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Statistics = __M.module("LXGrid.Main.Statistics");

    Object.defineProperty(LXGrid.Main.Statistics, 'IObjectName_Statistics', {
        value: "IObjectStatistics"
    });

    LXGrid.Main.Statistics.IObjectStatistics = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::Statistics::IObjectStatistics"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Statistics.IObjectStatisticsPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Statistics.IObjectStatistics.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.Statistics.IObjectStatistics, LXGrid.Main.Statistics.IObjectStatisticsPrx,
    {
        "RunStatistics": [, , , 1, , [LXGrid.Common.LXReturn], [[4], [3]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
