// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceUserProfile.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/Profile/LXSliceUserProfileDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Profile = __M.module("LXGrid.Main.Profile");

    Object.defineProperty(LXGrid.Main.Profile, 'IObjectUserProfileName', {
        value: "IObjectUserProfile"
    });

    LXGrid.Main.Profile.IObjectUserProfile = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::Profile::IObjectUserProfile"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Profile.IObjectUserProfilePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Profile.IObjectUserProfile.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.Profile.IObjectUserProfile, LXGrid.Main.Profile.IObjectUserProfilePrx,
    {
        "GetUserProfile": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.Main.Profile.LXUserProfileBase", true], ["LXGrid.Main.Profile.LXUserProfileBaseSeqHelper"]], , , true],
        "GetUserProfileV2": [, , , , , [LXGrid.Common.LXReturn], [[3]], [[3], ["LXGrid.Main.Profile.LXUserProfileBase", true], ["LXGrid.Main.Profile.LXUserProfileBaseSeqHelper"]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
