// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceUserProfileDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/User/LXSliceUserDefine",
        "LXGrid.Main/Zone/LXSliceZoneEnum",
        "LXGrid.Main/ZoneBusiness/LXSliceZoneBusiness"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Profile = __M.module("LXGrid.Main.Profile");

    LXGrid.Main.Profile.LXEnumProfileType = Slice.defineEnum([
        ['LXProfileTypeTeacher', 0], ['LXProfileTypeStudent', 1], ['LXProfileTypeChild', 2], ['LXProfileTypeParent', 3], ['LXProfileTypeOfficial', 4],
        ['LXProfileTypeSocialEdu', 5]]);

    LXGrid.Main.Profile.LXUserPropertyPersonal = Slice.defineStruct(
        function(role, gender)
        {
            this.role = role !== undefined ? role : 0;
            this.gender = gender !== undefined ? gender : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.role);
            __os.writeInt(this.gender);
        },
        function(__is)
        {
            this.role = __is.readInt();
            this.gender = __is.readInt();
        },
        8, 
        true);

    LXGrid.Main.Profile.LXUserPropertyArea = Slice.defineStruct(
        function(province, city, county)
        {
            this.province = province !== undefined ? province : 0;
            this.city = city !== undefined ? city : 0;
            this.county = county !== undefined ? county : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.province);
            __os.writeInt(this.city);
            __os.writeInt(this.county);
        },
        function(__is)
        {
            this.province = __is.readInt();
            this.city = __is.readInt();
            this.county = __is.readInt();
        },
        12, 
        true);
    Slice.defineSequence(LXGrid.Main.Profile, "LXUserPropertyAreaSeqHelper", "LXGrid.Main.Profile.LXUserPropertyArea", true);

    LXGrid.Main.Profile.LXUserPropertyClass = Slice.defineStruct(
        function(classid, grade, stage, role)
        {
            this.classid = classid !== undefined ? classid : 0;
            this.grade = grade !== undefined ? grade : 0;
            this.stage = stage !== undefined ? stage : 0;
            this.role = role !== undefined ? role : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.classid);
            __os.writeInt(this.grade);
            __os.writeInt(this.stage);
            __os.writeInt(this.role);
        },
        function(__is)
        {
            this.classid = __is.readInt();
            this.grade = __is.readInt();
            this.stage = __is.readInt();
            this.role = __is.readInt();
        },
        16, 
        true);
    Slice.defineSequence(LXGrid.Main.Profile, "LXUserPropertyClassSeqHelper", "LXGrid.Main.Profile.LXUserPropertyClass", true);

    LXGrid.Main.Profile.LXUserPropertyOrganization = Slice.defineStruct(
        function(org_id, role, edu_role)
        {
            this.org_id = org_id !== undefined ? org_id : 0;
            this.role = role !== undefined ? role : 0;
            this.edu_role = edu_role !== undefined ? edu_role : 0;
        },
        true,
        function(__os)
        {
            __os.writeInt(this.org_id);
            __os.writeInt(this.role);
            __os.writeInt(this.edu_role);
        },
        function(__is)
        {
            this.org_id = __is.readInt();
            this.role = __is.readInt();
            this.edu_role = __is.readInt();
        },
        12, 
        true);

    LXGrid.Main.Profile.LXUserProfileBase = Slice.defineObject(
        function(profile_type, personal)
        {
            Ice.Object.call(this);
            this.profile_type = profile_type !== undefined ? profile_type : LXGrid.Main.Profile.LXEnumProfileType.LXProfileTypeTeacher;
            this.personal = personal !== undefined ? personal : new LXGrid.Main.Profile.LXUserPropertyPersonal();
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::Main::Profile::LXUserProfileBase"
        ],
        -1,
        function(__os)
        {
            LXGrid.Main.Profile.LXEnumProfileType.__write(__os, this.profile_type);
            LXGrid.Main.Profile.LXUserPropertyPersonal.write(__os, this.personal);
        },
        function(__is)
        {
            this.profile_type = LXGrid.Main.Profile.LXEnumProfileType.__read(__is);
            this.personal = LXGrid.Main.Profile.LXUserPropertyPersonal.read(__is, this.personal);
        },
        false);

    LXGrid.Main.Profile.LXUserProfileBasePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Profile.LXUserProfileBase.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Profile.LXUserProfileBase, LXGrid.Main.Profile.LXUserProfileBasePrx);
    Slice.defineSequence(LXGrid.Main.Profile, "LXUserProfileBaseSeqHelper", "Ice.ObjectHelper", false, "LXGrid.Main.Profile.LXUserProfileBase");

    LXGrid.Main.Profile.LXUserProfileTeacher = Slice.defineObject(
        function(profile_type, personal, area, organization, clss)
        {
            LXGrid.Main.Profile.LXUserProfileBase.call(this, profile_type, personal);
            this.area = area !== undefined ? area : new LXGrid.Main.Profile.LXUserPropertyArea();
            this.organization = organization !== undefined ? organization : new LXGrid.Main.Profile.LXUserPropertyOrganization();
            this.clss = clss !== undefined ? clss : null;
        },
        LXGrid.Main.Profile.LXUserProfileBase, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::Main::Profile::LXUserProfileBase",
            "::LXGrid::Main::Profile::LXUserProfileTeacher"
        ],
        -1,
        function(__os)
        {
            LXGrid.Main.Profile.LXUserPropertyArea.write(__os, this.area);
            LXGrid.Main.Profile.LXUserPropertyOrganization.write(__os, this.organization);
            LXGrid.Main.Profile.LXUserPropertyClassSeqHelper.write(__os, this.clss);
        },
        function(__is)
        {
            this.area = LXGrid.Main.Profile.LXUserPropertyArea.read(__is, this.area);
            this.organization = LXGrid.Main.Profile.LXUserPropertyOrganization.read(__is, this.organization);
            this.clss = LXGrid.Main.Profile.LXUserPropertyClassSeqHelper.read(__is);
        },
        false);

    LXGrid.Main.Profile.LXUserProfileTeacherPrx = Slice.defineProxy(LXGrid.Main.Profile.LXUserProfileBasePrx, LXGrid.Main.Profile.LXUserProfileTeacher.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Profile.LXUserProfileTeacher, LXGrid.Main.Profile.LXUserProfileTeacherPrx);

    LXGrid.Main.Profile.LXUserProfileStudent = Slice.defineObject(
        function(profile_type, personal, area, organization, cls)
        {
            LXGrid.Main.Profile.LXUserProfileBase.call(this, profile_type, personal);
            this.area = area !== undefined ? area : new LXGrid.Main.Profile.LXUserPropertyArea();
            this.organization = organization !== undefined ? organization : new LXGrid.Main.Profile.LXUserPropertyOrganization();
            this.cls = cls !== undefined ? cls : new LXGrid.Main.Profile.LXUserPropertyClass();
        },
        LXGrid.Main.Profile.LXUserProfileBase, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::Main::Profile::LXUserProfileBase",
            "::LXGrid::Main::Profile::LXUserProfileStudent"
        ],
        -1,
        function(__os)
        {
            LXGrid.Main.Profile.LXUserPropertyArea.write(__os, this.area);
            LXGrid.Main.Profile.LXUserPropertyOrganization.write(__os, this.organization);
            LXGrid.Main.Profile.LXUserPropertyClass.write(__os, this.cls);
        },
        function(__is)
        {
            this.area = LXGrid.Main.Profile.LXUserPropertyArea.read(__is, this.area);
            this.organization = LXGrid.Main.Profile.LXUserPropertyOrganization.read(__is, this.organization);
            this.cls = LXGrid.Main.Profile.LXUserPropertyClass.read(__is, this.cls);
        },
        false);

    LXGrid.Main.Profile.LXUserProfileStudentPrx = Slice.defineProxy(LXGrid.Main.Profile.LXUserProfileBasePrx, LXGrid.Main.Profile.LXUserProfileStudent.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Profile.LXUserProfileStudent, LXGrid.Main.Profile.LXUserProfileStudentPrx);

    LXGrid.Main.Profile.LXUserProfileParent = Slice.defineObject(
        function(profile_type, personal)
        {
            LXGrid.Main.Profile.LXUserProfileBase.call(this, profile_type, personal);
        },
        LXGrid.Main.Profile.LXUserProfileBase, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::Main::Profile::LXUserProfileBase",
            "::LXGrid::Main::Profile::LXUserProfileParent"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Profile.LXUserProfileParentPrx = Slice.defineProxy(LXGrid.Main.Profile.LXUserProfileBasePrx, LXGrid.Main.Profile.LXUserProfileParent.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Profile.LXUserProfileParent, LXGrid.Main.Profile.LXUserProfileParentPrx);

    LXGrid.Main.Profile.LXUserProfileOfficial = Slice.defineObject(
        function(profile_type, personal, area, organization)
        {
            LXGrid.Main.Profile.LXUserProfileBase.call(this, profile_type, personal);
            this.area = area !== undefined ? area : new LXGrid.Main.Profile.LXUserPropertyArea();
            this.organization = organization !== undefined ? organization : new LXGrid.Main.Profile.LXUserPropertyOrganization();
        },
        LXGrid.Main.Profile.LXUserProfileBase, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::Main::Profile::LXUserProfileBase",
            "::LXGrid::Main::Profile::LXUserProfileOfficial"
        ],
        -1,
        function(__os)
        {
            LXGrid.Main.Profile.LXUserPropertyArea.write(__os, this.area);
            LXGrid.Main.Profile.LXUserPropertyOrganization.write(__os, this.organization);
        },
        function(__is)
        {
            this.area = LXGrid.Main.Profile.LXUserPropertyArea.read(__is, this.area);
            this.organization = LXGrid.Main.Profile.LXUserPropertyOrganization.read(__is, this.organization);
        },
        false);

    LXGrid.Main.Profile.LXUserProfileOfficialPrx = Slice.defineProxy(LXGrid.Main.Profile.LXUserProfileBasePrx, LXGrid.Main.Profile.LXUserProfileOfficial.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Profile.LXUserProfileOfficial, LXGrid.Main.Profile.LXUserProfileOfficialPrx);

    LXGrid.Main.Profile.LXUserProfileSocialEdu = Slice.defineObject(
        function(profile_type, personal, area, organization)
        {
            LXGrid.Main.Profile.LXUserProfileBase.call(this, profile_type, personal);
            this.area = area !== undefined ? area : new LXGrid.Main.Profile.LXUserPropertyArea();
            this.organization = organization !== undefined ? organization : new LXGrid.Main.Profile.LXUserPropertyOrganization();
        },
        LXGrid.Main.Profile.LXUserProfileBase, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::Main::Profile::LXUserProfileBase",
            "::LXGrid::Main::Profile::LXUserProfileSocialEdu"
        ],
        -1,
        function(__os)
        {
            LXGrid.Main.Profile.LXUserPropertyArea.write(__os, this.area);
            LXGrid.Main.Profile.LXUserPropertyOrganization.write(__os, this.organization);
        },
        function(__is)
        {
            this.area = LXGrid.Main.Profile.LXUserPropertyArea.read(__is, this.area);
            this.organization = LXGrid.Main.Profile.LXUserPropertyOrganization.read(__is, this.organization);
        },
        false);

    LXGrid.Main.Profile.LXUserProfileSocialEduPrx = Slice.defineProxy(LXGrid.Main.Profile.LXUserProfileBasePrx, LXGrid.Main.Profile.LXUserProfileSocialEdu.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.Main.Profile.LXUserProfileSocialEdu, LXGrid.Main.Profile.LXUserProfileSocialEduPrx);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
