// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceStatisticsProcessor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.System/LXSliceBase",
        "LXGrid.OM/Statistics/LXSliceStatisticsDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Statistics = __M.module("LXGrid.Statistics");

    LXGrid.Statistics.Processor = __M.module("LXGrid.Statistics.Processor");

    Object.defineProperty(LXGrid.Statistics.Processor, 'IObjectStatisticsProcessorName', {
        value: "IObjectStatisticsProcessor"
    });

    LXGrid.Statistics.Processor.IObjectStatisticsProcessor = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Statistics::Processor::IObjectStatisticsProcessor"
        ],
        -1, undefined, undefined, false);

    LXGrid.Statistics.Processor.IObjectStatisticsProcessorPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Statistics.Processor.IObjectStatisticsProcessor.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Statistics.Processor.IObjectStatisticsProcessor, LXGrid.Statistics.Processor.IObjectStatisticsProcessorPrx,
    {
        "DispatchMessage": [, , , 1, , , [["LXGrid.Statistics.SJMessageInfo", true]], , , true, ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
