// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceVerifyDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Verify = __M.module("LXGrid.Main.Verify");

    LXGrid.Main.Verify.LXEnumErrorVerify = Slice.defineEnum([
        ['LXBusiErrorWrongCode', 10001], ['LXBusiErrorWrongCodeId', 10002], ['LXBusiErrorWrongUserName', 10010], ['LXBusiErrorSmsRetryLimit', 10020], ['LXBusiErrorSmsSendError', 10021]]);

    LXGrid.Main.Verify.LXEnumCodeType = Slice.defineEnum([
        ['LXCodeTypeSmsRegister', 1], ['LXCodeTypeSmsLogin', 2], ['LXCodeTypeSmsDevice', 3]]);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
