// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceVerify.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/Verify/LXSliceVerifyDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Verify = __M.module("LXGrid.Main.Verify");

    Object.defineProperty(LXGrid.Main.Verify, 'IObjectVerifyName', {
        value: "IObjectVerify"
    });

    LXGrid.Main.Verify.IObjectVerify = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::Verify::IObjectVerify"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Verify.IObjectVerifyPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Verify.IObjectVerify.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.Verify.IObjectVerify, LXGrid.Main.Verify.IObjectVerifyPrx,
    {
        "SendSms": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [LXGrid.Main.Verify.LXEnumCodeType.__helper]], [[7], [4], [4]], , , ],
        "VerifySms": [, , , 1, , [LXGrid.Common.LXReturn], [[7], [7], [7], [LXGrid.Main.Verify.LXEnumCodeType.__helper]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
