// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSlicePush.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Push = __M.module("LXGrid.Main.Push");

    Object.defineProperty(LXGrid.Main.Push, 'IObjectPushName', {
        value: "IObjectPush"
    });

    LXGrid.Main.Push.IObjectPush = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::Push::IObjectPush"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Push.IObjectPushPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Push.IObjectPush.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.Push.IObjectPush, LXGrid.Main.Push.IObjectPushPrx,
    {
        "PushUserMessage": [, , , 1, , [LXGrid.Common.LXReturn], [[3], ["Ice.IntSeqHelper"], [7], [7]], , , , ],
        "PushAreaMessage": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], ["Ice.IntSeqHelper"], ["Ice.IntSeqHelper"], [7], [7], [3, , 1]], , , , ],
        "PushSchoolMessage": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], ["Ice.IntSeqHelper"], ["Ice.IntSeqHelper"], [7], [7], [3, , 1]], , , , ],
        "PushClassMessage": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], ["Ice.IntSeqHelper"], ["Ice.IntSeqHelper"], [7], [7], [3, , 1]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
