// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXOrderRefundGooldsProduct.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.OrderCenter = __M.module("LXGrid.App.OrderCenter");

    LXGrid.App.OrderCenter.LXOrderRefundGooldsProduct = Slice.defineObject(
        function(refundGNo, masterNo, proId, LXRmb, LXLe, LXGold)
        {
            Ice.Object.call(this);
            this.refundGNo = refundGNo !== undefined ? refundGNo : "";
            this.masterNo = masterNo !== undefined ? masterNo : "";
            this.proId = proId !== undefined ? proId : "";
            this.LXRmb = LXRmb !== undefined ? LXRmb : 0;
            this.LXLe = LXLe !== undefined ? LXLe : 0;
            this.LXGold = LXGold !== undefined ? LXGold : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::OrderCenter::LXOrderRefundGooldsProduct"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.refundGNo);
            __os.writeString(this.masterNo);
            __os.writeString(this.proId);
            __os.writeInt(this.LXRmb);
            __os.writeInt(this.LXLe);
            __os.writeInt(this.LXGold);
        },
        function(__is)
        {
            this.refundGNo = __is.readString();
            this.masterNo = __is.readString();
            this.proId = __is.readString();
            this.LXRmb = __is.readInt();
            this.LXLe = __is.readInt();
            this.LXGold = __is.readInt();
        },
        false);

    LXGrid.App.OrderCenter.LXOrderRefundGooldsProductPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.OrderCenter.LXOrderRefundGooldsProduct.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.OrderCenter.LXOrderRefundGooldsProduct, LXGrid.App.OrderCenter.LXOrderRefundGooldsProductPrx);
    Slice.defineSequence(LXGrid.App.OrderCenter, "LXOrderRefundGooldsProductSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.OrderCenter.LXOrderRefundGooldsProduct");
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
