// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXOrderToExamineLog.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.OrderCenter = __M.module("LXGrid.App.OrderCenter");

    LXGrid.App.OrderCenter.LXOrderToExamineLog = Slice.defineObject(
        function(auditNo, masterNo, subNo, auditor, auditObject, inTime, auditTime, auditState, auditType)
        {
            Ice.Object.call(this);
            this.auditNo = auditNo !== undefined ? auditNo : "";
            this.masterNo = masterNo !== undefined ? masterNo : "";
            this.subNo = subNo !== undefined ? subNo : "";
            this.auditor = auditor !== undefined ? auditor : 0;
            this.auditObject = auditObject !== undefined ? auditObject : "";
            this.inTime = inTime !== undefined ? inTime : 0;
            this.auditTime = auditTime !== undefined ? auditTime : 0;
            this.auditState = auditState !== undefined ? auditState : 0;
            this.auditType = auditType !== undefined ? auditType : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::OrderCenter::LXOrderToExamineLog"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.auditNo);
            __os.writeString(this.masterNo);
            __os.writeString(this.subNo);
            __os.writeInt(this.auditor);
            __os.writeString(this.auditObject);
            __os.writeLong(this.inTime);
            __os.writeLong(this.auditTime);
            __os.writeInt(this.auditState);
            __os.writeInt(this.auditType);
        },
        function(__is)
        {
            this.auditNo = __is.readString();
            this.masterNo = __is.readString();
            this.subNo = __is.readString();
            this.auditor = __is.readInt();
            this.auditObject = __is.readString();
            this.inTime = __is.readLong();
            this.auditTime = __is.readLong();
            this.auditState = __is.readInt();
            this.auditType = __is.readInt();
        },
        false);

    LXGrid.App.OrderCenter.LXOrderToExamineLogPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.OrderCenter.LXOrderToExamineLog.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.OrderCenter.LXOrderToExamineLog, LXGrid.App.OrderCenter.LXOrderToExamineLogPrx);
    Slice.defineSequence(LXGrid.App.OrderCenter, "LXOrderToExamineLogSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.OrderCenter.LXOrderToExamineLog");
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
