// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXOrderReturnGoods.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.OrderCenter = __M.module("LXGrid.App.OrderCenter");

    LXGrid.App.OrderCenter.LXOrderReturnGoods = Slice.defineObject(
        function(refundGNo, masterNo, subNo, refundGState, applyTime, reason)
        {
            Ice.Object.call(this);
            this.refundGNo = refundGNo !== undefined ? refundGNo : "";
            this.masterNo = masterNo !== undefined ? masterNo : "";
            this.subNo = subNo !== undefined ? subNo : "";
            this.refundGState = refundGState !== undefined ? refundGState : 0;
            this.applyTime = applyTime !== undefined ? applyTime : 0;
            this.reason = reason !== undefined ? reason : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::OrderCenter::LXOrderReturnGoods"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.refundGNo);
            __os.writeString(this.masterNo);
            __os.writeString(this.subNo);
            __os.writeInt(this.refundGState);
            __os.writeLong(this.applyTime);
            __os.writeString(this.reason);
        },
        function(__is)
        {
            this.refundGNo = __is.readString();
            this.masterNo = __is.readString();
            this.subNo = __is.readString();
            this.refundGState = __is.readInt();
            this.applyTime = __is.readLong();
            this.reason = __is.readString();
        },
        false);

    LXGrid.App.OrderCenter.LXOrderReturnGoodsPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.OrderCenter.LXOrderReturnGoods.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.OrderCenter.LXOrderReturnGoods, LXGrid.App.OrderCenter.LXOrderReturnGoodsPrx);
    Slice.defineSequence(LXGrid.App.OrderCenter, "LXReturnGoodsSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.OrderCenter.LXOrderReturnGoods");
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
