// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXOrderUserAddress.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.OrderCenter = __M.module("LXGrid.App.OrderCenter");

    LXGrid.App.OrderCenter.LXOrderUserAddress = Slice.defineObject(
        function(masterNo, userId, recUser, recAddress, recPhone, recArea, recCity, recProvince)
        {
            Ice.Object.call(this);
            this.masterNo = masterNo !== undefined ? masterNo : "";
            this.userId = userId !== undefined ? userId : 0;
            this.recUser = recUser !== undefined ? recUser : "";
            this.recAddress = recAddress !== undefined ? recAddress : "";
            this.recPhone = recPhone !== undefined ? recPhone : "";
            this.recArea = recArea !== undefined ? recArea : "";
            this.recCity = recCity !== undefined ? recCity : "";
            this.recProvince = recProvince !== undefined ? recProvince : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::OrderCenter::LXOrderUserAddress"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.masterNo);
            __os.writeInt(this.userId);
            __os.writeString(this.recUser);
            __os.writeString(this.recAddress);
            __os.writeString(this.recPhone);
            __os.writeString(this.recArea);
            __os.writeString(this.recCity);
            __os.writeString(this.recProvince);
        },
        function(__is)
        {
            this.masterNo = __is.readString();
            this.userId = __is.readInt();
            this.recUser = __is.readString();
            this.recAddress = __is.readString();
            this.recPhone = __is.readString();
            this.recArea = __is.readString();
            this.recCity = __is.readString();
            this.recProvince = __is.readString();
        },
        false);

    LXGrid.App.OrderCenter.LXOrderUserAddressPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.OrderCenter.LXOrderUserAddress.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.OrderCenter.LXOrderUserAddress, LXGrid.App.OrderCenter.LXOrderUserAddressPrx);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
