// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXOrderStateLog.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = require("LXGrid.Common/LXSliceDefine").LXGrid;
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.OrderCenter = __M.module("LXGrid.App.OrderCenter");

    LXGrid.App.OrderCenter.LXOrderStateLog = Slice.defineObject(
        function(rowid, masterNo, startTime, originalState, targetState, opUser, opName, opPhone, isBackstage)
        {
            Ice.Object.call(this);
            this.rowid = rowid !== undefined ? rowid : 0;
            this.masterNo = masterNo !== undefined ? masterNo : "";
            this.startTime = startTime !== undefined ? startTime : 0;
            this.originalState = originalState !== undefined ? originalState : 0;
            this.targetState = targetState !== undefined ? targetState : 0;
            this.opUser = opUser !== undefined ? opUser : 0;
            this.opName = opName !== undefined ? opName : "";
            this.opPhone = opPhone !== undefined ? opPhone : 0;
            this.isBackstage = isBackstage !== undefined ? isBackstage : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::OrderCenter::LXOrderStateLog"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.rowid);
            __os.writeString(this.masterNo);
            __os.writeLong(this.startTime);
            __os.writeInt(this.originalState);
            __os.writeInt(this.targetState);
            __os.writeInt(this.opUser);
            __os.writeString(this.opName);
            __os.writeInt(this.opPhone);
            __os.writeInt(this.isBackstage);
        },
        function(__is)
        {
            this.rowid = __is.readInt();
            this.masterNo = __is.readString();
            this.startTime = __is.readLong();
            this.originalState = __is.readInt();
            this.targetState = __is.readInt();
            this.opUser = __is.readInt();
            this.opName = __is.readString();
            this.opPhone = __is.readInt();
            this.isBackstage = __is.readInt();
        },
        false);

    LXGrid.App.OrderCenter.LXOrderStateLogPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.OrderCenter.LXOrderStateLog.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.OrderCenter.LXOrderStateLog, LXGrid.App.OrderCenter.LXOrderStateLogPrx);
    Slice.defineSequence(LXGrid.App.OrderCenter, "LXOrderStateLogSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.OrderCenter.LXOrderStateLog");
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
