// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceOrderStateService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/OrderCenter/LXSliceOrderDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.OrderCenter = __M.module("LXGrid.App.OrderCenter");

    Object.defineProperty(LXGrid.App.OrderCenter, 'IObjectOrderStateServiceName', {
        value: "IObjectOrderStateService"
    });

    LXGrid.App.OrderCenter.IObjectOrderStateService = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::OrderCenter::IObjectOrderStateService",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.OrderCenter.IObjectOrderStateServicePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.OrderCenter.IObjectOrderStateService.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.OrderCenter.IObjectOrderStateService, LXGrid.App.OrderCenter.IObjectOrderStateServicePrx,
    {
        "NotifyMerchant": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7], [7], [3]], [[1]], , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
