// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceOrderPayManage.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/OrderCenter/LXSliceOrderDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.OrderCenter = __M.module("LXGrid.App.OrderCenter");

    Object.defineProperty(LXGrid.App.OrderCenter, 'IObjectOrderPayManagerName', {
        value: "IObjectOrderPayManage"
    });

    LXGrid.App.OrderCenter.IObjectOrderPayManage = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectMasterSlaveBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::OrderCenter::IObjectOrderPayManage",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Common::IObjectMasterSlaveBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.OrderCenter.IObjectOrderPayManagePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.OrderCenter.IObjectOrderPayManage.ice_staticId, [
        LXGrid.Common.IObjectMasterSlaveBasePrx]);

    Slice.defineOperations(LXGrid.App.OrderCenter.IObjectOrderPayManage, LXGrid.App.OrderCenter.IObjectOrderPayManagePrx,
    {
        "GetPayNoDetail": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.App.OrderCenter.LXOrderPrice", true]], , , true],
        "NotifyPayNoComplete": [, , , , , [LXGrid.Common.LXReturn], [[7]], [["LXGrid.App.OrderCenter.LXOrderPrice", true]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
