// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceRelation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/Relation/LXSliceRelationDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.Main = __M.module("LXGrid.Main");

    LXGrid.Main.Relation = __M.module("LXGrid.Main.Relation");

    Object.defineProperty(LXGrid.Main.Relation, 'IObjectRelationName', {
        value: "IObjectRelation"
    });

    LXGrid.Main.Relation.IObjectRelation = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 2,
        [
            "::Ice::Object",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Main::Relation::IObjectRelation"
        ],
        -1, undefined, undefined, false);

    LXGrid.Main.Relation.IObjectRelationPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.Main.Relation.IObjectRelation.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.Main.Relation.IObjectRelation, LXGrid.Main.Relation.IObjectRelationPrx,
    {
        "AddContact": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7]], , , , ],
        "ProcessInvitation": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [LXGrid.Main.Relation.LXEnumInvitationState.__helper]], , , , ],
        "DeleteContact": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3]], , , , ],
        "SetContactRemark": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7]], , , , ],
        "SetContactStar": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [1]], , , , ],
        "GetContactList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3], [3]], [[3], ["LXGrid.Main.Relation.LXContactSeqHelper"]], , , true],
        "GetContactListSeq": [, , , , , [LXGrid.Common.LXReturn], [["Ice.IntSeqHelper"], [3], [3]], [[3], ["LXGrid.Main.Relation.LXContactDictHelper"]], , , true],
        "GetContactIDList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3]], [["Ice.IntSeqHelper"]], , , ],
        "GetContactIDListSeq": [, , , , , [LXGrid.Common.LXReturn], [["Ice.IntSeqHelper"], [3], [3]], [[3], ["LXGrid.Main.Relation.LXContactIDDictHelper"]], , , ],
        "GetInvitationList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3], [3], [4], [4]], [[3], ["LXGrid.Main.Relation.LXInvitationSeqHelper"]], , , true],
        "GetUserFamilyUserIDList": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["Ice.IntSeqHelper"]], , , ],
        "AddRelation": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [LXGrid.Main.Relation.LXEnumRelationModeProp.__helper]], , , , ],
        "RemoveRelation": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3]], , , , ],
        "RemoveUserRelation": [, , , 1, , [LXGrid.Common.LXReturn], [[3]], , , , ],
        "IsContactExist": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
