// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceQuestionnaireStat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/Questionnaire/LXSliceQuestionnaireDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.Questionnaire = __M.module("LXGrid.App.Questionnaire");

    Object.defineProperty(LXGrid.App.Questionnaire, 'IObjectQuestionnaireStatName', {
        value: "IObjectQuestionnaireStat"
    });

    LXGrid.App.Questionnaire.IObjectQuestionnaireStat = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectMasterSlaveBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Questionnaire::IObjectQuestionnaireStat",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Common::IObjectMasterSlaveBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.Questionnaire.IObjectQuestionnaireStatPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Questionnaire.IObjectQuestionnaireStat.ice_staticId, [
        LXGrid.Common.IObjectMasterSlaveBasePrx]);

    Slice.defineOperations(LXGrid.App.Questionnaire.IObjectQuestionnaireStat, LXGrid.App.Questionnaire.IObjectQuestionnaireStatPrx,
    {
        "GetQuestScopeStat": [, , , , , [LXGrid.Common.LXReturn], [[7], ["LXGrid.App.Questionnaire.LXConditionSeqHelper"], [3], [3]], [["LXGrid.App.Questionnaire.LXStatScopeDictHelper"], ["LXGrid.App.Questionnaire.LXStatQuestionSeqHelper"]], , true, ],
        "GetQuestScopeDataStat": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3], [4]], [["LXGrid.App.Questionnaire.LXDataStatDictHelper"]], , , ],
        "GetQuestScopeUserList": [, , , , , [LXGrid.Common.LXReturn], [[7], ["LXGrid.App.Questionnaire.LXConditionSeqHelper"], [3], [3], [3], [3]], [[3], ["Ice.IntSeqHelper"]], , true, ],
        "GetQuestSubmitCount": [, , , , , [LXGrid.Common.LXReturn], [[7]], [[3]], , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
