// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceInformationAdmin.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/Information/LXSliceInformationDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.Information = __M.module("LXGrid.App.Information");

    Object.defineProperty(LXGrid.App.Information, 'IObjectInformationAdminName', {
        value: "IObjectInformationAdmin"
    });

    LXGrid.App.Information.IObjectInformationAdmin = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectMasterSlaveBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::IObjectInformationAdmin",
            "::LXGrid::Common::IObjectBase",
            "::LXGrid::Common::IObjectMasterSlaveBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.Information.IObjectInformationAdminPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Information.IObjectInformationAdmin.ice_staticId, [
        LXGrid.Common.IObjectMasterSlaveBasePrx]);

    Slice.defineOperations(LXGrid.App.Information.IObjectInformationAdmin, LXGrid.App.Information.IObjectInformationAdminPrx,
    {
        "GetAdminList": [, , , , , [LXGrid.Common.LXReturn], , [["Ice.IntSeqHelper"]], , , ],
        "CheckAdmin": [, , , 1, , [LXGrid.Common.LXReturn], [[3]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
