// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceInformationCommon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/Information/LXSliceInformationDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.Information = __M.module("LXGrid.App.Information");

    Object.defineProperty(LXGrid.App.Information, 'IObjectInformationCommonName', {
        value: "IObjectInformationCommon"
    });

    LXGrid.App.Information.IObjectInformationCommon = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::IObjectInformationCommon",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.Information.IObjectInformationCommonPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Information.IObjectInformationCommon.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.Information.IObjectInformationCommon, LXGrid.App.Information.IObjectInformationCommonPrx,
    {
        "GetAuditLabelList": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.Information.LXAuditLabelInfoSeqHelper"]], , , true],
        "CreateAuditLabel": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], [[3]], , , ],
        "DeleteAuditLabel": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3]], , , , ],
        "ModifyAuditLabel": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7]], , , , ],
        "GetCarouselImages": [, , , , , [LXGrid.Common.LXReturn], [[3]], [[7]], , , ],
        "SetCarouselImages": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7]], , , , ],
        "GetRandomCoverImages": [, , , , , [LXGrid.Common.LXReturn], , [[7]], , , ],
        "GetInformationStatCount": [, , , , , [LXGrid.Common.LXReturn], , [["LXGrid.App.Information.LXInformationStatCount", true]], , , true]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
