// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceInformationDefine.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.Main/Profile/LXSliceUserProfileDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.Information = __M.module("LXGrid.App.Information");

    LXGrid.App.Information.LXEnumErrorInformation = Slice.defineEnum([
        ['LXINFErrorAlreadyDelete', 5001], ['LXINFErrorAlreadyAudit', 5002], ['LXINFErrorNotOwn', 5003], ['LXINFErrorAlreadyChange', 5004], ['LXINFErrorAlreadyPass', 5005],
        ['LXINFErrorNotPass', 5006]]);

    LXGrid.App.Information.LXEnumIdentityType = Slice.defineEnum([
        ['LXIdentityUnknown', 0], ['LXIdentityStudent', 1], ['LXIdentityParent', 2], ['LXIdentityTeacher', 4], ['LXIdentityAll', 7]]);

    LXGrid.App.Information.LXEnumInformationState = Slice.defineEnum([
        ['LXInformationStateOutline', 1], ['LXInformationStateReview', 2], ['LXInformationStatePassed', 4], ['LXInformationStateUnPassed', 8]]);

    LXGrid.App.Information.LXEnumDeleteState = Slice.defineEnum([
        ['LXDeleteNone', 0], ['LXDeleteUser', 1], ['LXDeleteAdmin', 2], ['LXDeleteDelete', 4]]);

    LXGrid.App.Information.LXColumnInfo = Slice.defineObject(
        function(columnid, name, synopsis, creator, createtime, identity)
        {
            Ice.Object.call(this);
            this.columnid = columnid !== undefined ? columnid : 0;
            this.name = name !== undefined ? name : "";
            this.synopsis = synopsis !== undefined ? synopsis : "";
            this.creator = creator !== undefined ? creator : 0;
            this.createtime = createtime !== undefined ? createtime : 0;
            this.identity = identity !== undefined ? identity : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::LXColumnInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.columnid);
            __os.writeString(this.name);
            __os.writeString(this.synopsis);
            __os.writeInt(this.creator);
            __os.writeLong(this.createtime);
            __os.writeInt(this.identity);
        },
        function(__is)
        {
            this.columnid = __is.readInt();
            this.name = __is.readString();
            this.synopsis = __is.readString();
            this.creator = __is.readInt();
            this.createtime = __is.readLong();
            this.identity = __is.readInt();
        },
        false);

    LXGrid.App.Information.LXColumnInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Information.LXColumnInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.Information.LXColumnInfo, LXGrid.App.Information.LXColumnInfoPrx);
    Slice.defineSequence(LXGrid.App.Information, "LXColumnInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.Information.LXColumnInfo");

    LXGrid.App.Information.LXColumnInfoModifyType = Slice.defineEnum([
        ['LXEnumColumnInfoModifyName', 0], ['LXEnumColumnInfoModifySynopsis', 1], ['LXEnumColumnInfoModifyIdentity', 2]]);

    LXGrid.App.Information.LXStatPersonal = Slice.defineObject(
        function(recommend, audit, pass, unpass, drafts)
        {
            Ice.Object.call(this);
            this.recommend = recommend !== undefined ? recommend : 0;
            this.audit = audit !== undefined ? audit : 0;
            this.pass = pass !== undefined ? pass : 0;
            this.unpass = unpass !== undefined ? unpass : 0;
            this.drafts = drafts !== undefined ? drafts : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::LXStatPersonal"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.recommend);
            __os.writeInt(this.audit);
            __os.writeInt(this.pass);
            __os.writeInt(this.unpass);
            __os.writeInt(this.drafts);
        },
        function(__is)
        {
            this.recommend = __is.readInt();
            this.audit = __is.readInt();
            this.pass = __is.readInt();
            this.unpass = __is.readInt();
            this.drafts = __is.readInt();
        },
        false);

    LXGrid.App.Information.LXStatPersonalPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Information.LXStatPersonal.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.Information.LXStatPersonal, LXGrid.App.Information.LXStatPersonalPrx);

    LXGrid.App.Information.LXInformationBase = Slice.defineObject(
        function(title, image, source, summary, vote, good, segment, columnid, context)
        {
            Ice.Object.call(this);
            this.title = title !== undefined ? title : "";
            this.image = image !== undefined ? image : "";
            this.source = source !== undefined ? source : "";
            this.summary = summary !== undefined ? summary : "";
            this.vote = vote !== undefined ? vote : false;
            this.good = good !== undefined ? good : false;
            this.segment = segment !== undefined ? segment : null;
            this.columnid = columnid !== undefined ? columnid : 0;
            this.context = context !== undefined ? context : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::LXInformationBase"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.title);
            __os.writeString(this.image);
            __os.writeString(this.source);
            __os.writeString(this.summary);
            __os.writeBool(this.vote);
            __os.writeBool(this.good);
            Ice.IntSeqHelper.write(__os, this.segment);
            __os.writeInt(this.columnid);
            __os.writeString(this.context);
        },
        function(__is)
        {
            this.title = __is.readString();
            this.image = __is.readString();
            this.source = __is.readString();
            this.summary = __is.readString();
            this.vote = __is.readBool();
            this.good = __is.readBool();
            this.segment = Ice.IntSeqHelper.read(__is);
            this.columnid = __is.readInt();
            this.context = __is.readString();
        },
        false);

    LXGrid.App.Information.LXInformationBasePrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Information.LXInformationBase.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.Information.LXInformationBase, LXGrid.App.Information.LXInformationBasePrx);

    LXGrid.App.Information.LXInformationInfo = Slice.defineObject(
        function(title, image, source, summary, vote, good, segment, columnid, context, informationid, creator, auditor, createtime, audittime, publishtime, updatetime, reason, auditstate, deletestate)
        {
            LXGrid.App.Information.LXInformationBase.call(this, title, image, source, summary, vote, good, segment, columnid, context);
            this.informationid = informationid !== undefined ? informationid : "";
            this.creator = creator !== undefined ? creator : 0;
            this.auditor = auditor !== undefined ? auditor : 0;
            this.createtime = createtime !== undefined ? createtime : 0;
            this.audittime = audittime !== undefined ? audittime : 0;
            this.publishtime = publishtime !== undefined ? publishtime : 0;
            this.updatetime = updatetime !== undefined ? updatetime : 0;
            this.reason = reason !== undefined ? reason : "";
            this.auditstate = auditstate !== undefined ? auditstate : 0;
            this.deletestate = deletestate !== undefined ? deletestate : 0;
        },
        LXGrid.App.Information.LXInformationBase, undefined, 2,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::LXInformationBase",
            "::LXGrid::App::Information::LXInformationInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.informationid);
            __os.writeInt(this.creator);
            __os.writeInt(this.auditor);
            __os.writeLong(this.createtime);
            __os.writeLong(this.audittime);
            __os.writeLong(this.publishtime);
            __os.writeLong(this.updatetime);
            __os.writeString(this.reason);
            __os.writeInt(this.auditstate);
            __os.writeInt(this.deletestate);
        },
        function(__is)
        {
            this.informationid = __is.readString();
            this.creator = __is.readInt();
            this.auditor = __is.readInt();
            this.createtime = __is.readLong();
            this.audittime = __is.readLong();
            this.publishtime = __is.readLong();
            this.updatetime = __is.readLong();
            this.reason = __is.readString();
            this.auditstate = __is.readInt();
            this.deletestate = __is.readInt();
        },
        false);

    LXGrid.App.Information.LXInformationInfoPrx = Slice.defineProxy(LXGrid.App.Information.LXInformationBasePrx, LXGrid.App.Information.LXInformationInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.Information.LXInformationInfo, LXGrid.App.Information.LXInformationInfoPrx);
    Slice.defineSequence(LXGrid.App.Information, "LXInformationInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.Information.LXInformationInfo");

    LXGrid.App.Information.LXAuditLabelInfo = Slice.defineObject(
        function(labelid, label)
        {
            Ice.Object.call(this);
            this.labelid = labelid !== undefined ? labelid : 0;
            this.label = label !== undefined ? label : "";
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::LXAuditLabelInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.labelid);
            __os.writeString(this.label);
        },
        function(__is)
        {
            this.labelid = __is.readInt();
            this.label = __is.readString();
        },
        false);

    LXGrid.App.Information.LXAuditLabelInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Information.LXAuditLabelInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.Information.LXAuditLabelInfo, LXGrid.App.Information.LXAuditLabelInfoPrx);
    Slice.defineSequence(LXGrid.App.Information, "LXAuditLabelInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.Information.LXAuditLabelInfo");

    LXGrid.App.Information.LXRankInfo = Slice.defineObject(
        function(informationid, rate)
        {
            Ice.Object.call(this);
            this.informationid = informationid !== undefined ? informationid : "";
            this.rate = rate !== undefined ? rate : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::LXRankInfo"
        ],
        -1,
        function(__os)
        {
            __os.writeString(this.informationid);
            __os.writeLong(this.rate);
        },
        function(__is)
        {
            this.informationid = __is.readString();
            this.rate = __is.readLong();
        },
        false);

    LXGrid.App.Information.LXRankInfoPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Information.LXRankInfo.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.Information.LXRankInfo, LXGrid.App.Information.LXRankInfoPrx);
    Slice.defineSequence(LXGrid.App.Information, "LXRankInfoSeqHelper", "Ice.ObjectHelper", false, "LXGrid.App.Information.LXRankInfo");

    LXGrid.App.Information.LXInformationStatCount = Slice.defineObject(
        function(daynum, monthnum, totalnum)
        {
            Ice.Object.call(this);
            this.daynum = daynum !== undefined ? daynum : 0;
            this.monthnum = monthnum !== undefined ? monthnum : 0;
            this.totalnum = totalnum !== undefined ? totalnum : 0;
        },
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::LXInformationStatCount"
        ],
        -1,
        function(__os)
        {
            __os.writeInt(this.daynum);
            __os.writeInt(this.monthnum);
            __os.writeInt(this.totalnum);
        },
        function(__is)
        {
            this.daynum = __is.readInt();
            this.monthnum = __is.readInt();
            this.totalnum = __is.readInt();
        },
        false);

    LXGrid.App.Information.LXInformationStatCountPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Information.LXInformationStatCount.ice_staticId, undefined);

    Slice.defineOperations(LXGrid.App.Information.LXInformationStatCount, LXGrid.App.Information.LXInformationStatCountPrx);
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
