// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceInformationDetail.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/Information/LXSliceInformationDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.Information = __M.module("LXGrid.App.Information");

    Object.defineProperty(LXGrid.App.Information, 'IObjectInformationDetailName', {
        value: "IObjectInformationDetail"
    });

    LXGrid.App.Information.IObjectInformationDetail = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::IObjectInformationDetail",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.Information.IObjectInformationDetailPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Information.IObjectInformationDetail.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.Information.IObjectInformationDetail, LXGrid.App.Information.IObjectInformationDetailPrx,
    {
        "GetRecomInformationList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3]], [[3], ["LXGrid.App.Information.LXRankInfoSeqHelper"]], , , true],
        "GetInformationList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3]], [[3], ["Ice.StringSeqHelper"]], , , ],
        "GetPublishList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3], [3]], [[3], ["Ice.StringSeqHelper"]], , , ],
        "GetAuditList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3], [3]], [[3], ["Ice.StringSeqHelper"]], , , ],
        "GetWaitAuditList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3]], [[3], ["Ice.StringSeqHelper"]], , , ],
        "GetSimilarList": [, , , , , [LXGrid.Common.LXReturn], [[3], [7]], [["LXGrid.App.Information.LXRankInfoSeqHelper"]], , , true],
        "GetHotList": [, , , , , [LXGrid.Common.LXReturn], [[3], [7]], [["Ice.StringSeqHelper"]], , , ],
        "GetInformationInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [7]], [["LXGrid.App.Information.LXInformationInfo", true]], , , true],
        "GetInformationStat": [, , , , , [LXGrid.Common.LXReturn], [[3], [7]], [[3]], , , ],
        "GetRecommendList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3]], [[3], ["LXGrid.App.Information.LXRankInfoSeqHelper"]], , , true],
        "GetBeRecommendList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3], [3], [3]], [[3], ["LXGrid.App.Information.LXRankInfoSeqHelper"]], , , true],
        "GetStatPersonal": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.Information.LXStatPersonal", true]], , , true],
        "GetInformationText": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], [[7]], , , ],
        "CreateInformation": [, , , 1, , [LXGrid.Common.LXReturn], [[3], ["LXGrid.App.Information.LXInformationBase", true], [7]], [[7], [7]], , true, ],
        "ModifyInformation": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7], ["LXGrid.App.Information.LXInformationBase", true], [7]], [[7]], , true, ],
        "PublishInformation": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [7]], [[7]], , , ],
        "AuditInformation": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7], [1], [7], [7]], , , , ],
        "DeleteInformation": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], , , , ],
        "RecommendInformation": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7], [1]], , , , ],
        "GetALLInformationList": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [[3], ["Ice.StringSeqHelper"]], , , ],
        "CommentInformation": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7]], , , , ],
        "ResetSimilarDataBase": [, , , 1, , [LXGrid.Common.LXReturn], , , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
