// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `LXSliceInformationColumn.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var LXGrid = __M.require(module, 
    [
        "LXGrid.Common/LXSliceDefine",
        "LXGrid.App/Information/LXSliceInformationDefine"
    ]).LXGrid;
    
    var Slice = Ice.Slice;

    LXGrid.App = __M.module("LXGrid.App");

    LXGrid.App.Information = __M.module("LXGrid.App.Information");

    Object.defineProperty(LXGrid.App.Information, 'IObjectInformationColumnName', {
        value: "IObjectInformationColumn"
    });

    LXGrid.App.Information.IObjectInformationColumn = Slice.defineObject(
        undefined,
        Ice.Object,
        [
            LXGrid.Common.IObjectBase
        ], 1,
        [
            "::Ice::Object",
            "::LXGrid::App::Information::IObjectInformationColumn",
            "::LXGrid::Common::IObjectBase"
        ],
        -1, undefined, undefined, false);

    LXGrid.App.Information.IObjectInformationColumnPrx = Slice.defineProxy(Ice.ObjectPrx, LXGrid.App.Information.IObjectInformationColumn.ice_staticId, [
        LXGrid.Common.IObjectBasePrx]);

    Slice.defineOperations(LXGrid.App.Information.IObjectInformationColumn, LXGrid.App.Information.IObjectInformationColumnPrx,
    {
        "GetColumnIDList": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["Ice.IntSeqHelper"]], , , ],
        "GetColumnList": [, , , , , [LXGrid.Common.LXReturn], [[3]], [["LXGrid.App.Information.LXColumnInfoSeqHelper"]], , , true],
        "SetColumnOrder": [, , , , , [LXGrid.Common.LXReturn], [[3], ["Ice.IntSeqHelper"]], , , , ],
        "SetOwnColumnOrder": [, , , , , [LXGrid.Common.LXReturn], [[3], ["Ice.IntSeqHelper"]], , , , ],
        "GetColumnInfo": [, , , , , [LXGrid.Common.LXReturn], [[3], [3]], [["LXGrid.App.Information.LXColumnInfo", true]], , , true],
        "CreateColumn": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [7], [7], [3]], [[3]], , , ],
        "DeleteColumn": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3]], , , , ],
        "SetColumnInfo": [, , , 1, , [LXGrid.Common.LXReturn], [[3], [3], [LXGrid.App.Information.LXColumnInfoModifyType.__helper], [7]], , , , ]
    });
    exports.LXGrid = LXGrid;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
